[原创-05-06]：Jenkins 插件开发之旅：两天内从 idea 到发布(上篇)
jenkins-infra/wechat pull request #103
Opened 2019-04-27 07:04 UTC by donhui

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-04-27 12:12 UTC, LinuxSuRen commented
这种从零到一的过程介绍类的原创文章非常地好，相信能带给很多有意愿参与社区的同学一些很好的经验和帮助。

2019-04-27 15:48 UTC, zacker330 commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +
很奇怪，为什么这里需要换这么多行？其它地方的段落也是这样、

2019-04-28 01:19 UTC, donhui commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +
可能这是我个人的习惯，
这里换行的话，阅读起来比较方便，对 review 者来说也一样；
另外， markdown 渲染的时候会将它渲染成一个段落的。

2019-04-28 01:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +
嗯，是的，短行会方便 review

2019-04-28 05:06 UTC, LinuxSuRen requested changes

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +这里是通过在 Jenkins 构建时做校验实现的。
> 这里是通过在 Jenkins 构建时做校验实现的。

这一段还是在说你的构思过程，所以可能还不清楚最终的实现是什么样的。

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +打开一个命令行终端，切换到你想存放 Jenins 插件的目录，运行如下命令：
> 打开一个命令行终端，切换到你想存放 Jenins 插件的目录，运行如下命令

打开一个命令行终端，切换到你想存放 Jenins 插件源代码的目录，运行如下命令

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +它提供了一种便利的方式来运行一个 Jenkins 实例和你的插件：
> 它提供了一种便利的方式来运行一个 Jenkins 实例和你的插件：

它提供了一种便利的方式来运行一个已经包含了当前插件的 Jenkins 实例：

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +在 Jenkins 中创建一个自由风格的 Job ，然后给它取个名字。
> Job

我们已经把这个翻译为`任务`了，还是要保持一致。

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +![say hello world](../../../images/articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01/say-hello-world.png)
这个图片没有显示出来。

https://github.com/jenkins-infra/wechat/blob/a394950687cefdb52020ba6869d34dc1ad8ef96a/articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md#%E6%9E%84%E5%BB%BA%E5%8F%8A%E8%BF%90%E8%A1%8C%E6%8F%92%E4%BB%B6

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +开发人员可以对其进行扩展自定义实现一些功能。
这两个应该是一行把。https://github.com/jenkins-infra/wechat/blob/a394950687cefdb52020ba6869d34dc1ad8ef96a/articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md#%E5%AE%9A%E5%88%B6%E5%BC%80%E5%8F%91%E6%8F%92%E4%BB%B6

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +开发人员可以对其进行扩展自定义实现一些功能。
还有下面有一些也是这样的，建议看看预览的页面。

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +前端 `config.jelly` 页面代码片段如下：
建议对数据绑定的规则多点描述，方便读者。

2019-04-28 05:06 UTC, LinuxSuRen commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +Jenkins 是 Master/Slave 架构，
> Slave

社区已经不在使用这个词了，有一些歧视嫌疑。

2019-04-28 07:44 UTC, donhui commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +这里是通过在 Jenkins 构建时做校验实现的。
> > 这里是通过在 Jenkins 构建时做校验实现的。
> 
> 这一段还是在说你的构思过程，所以可能还不清楚最终的实现是什么样的。

我再加个案例说明吧

2019-04-28 07:45 UTC, donhui commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +![say hello world](../../../images/articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01/say-hello-world.png)
> 这个图片没有显示出来。
> 
> https://github.com/jenkins-infra/wechat/blob/a394950687cefdb52020ba6869d34dc1ad8ef96a/articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md#%E6%9E%84%E5%BB%BA%E5%8F%8A%E8%BF%90%E8%A1%8C%E6%8F%92%E4%BB%B6

图片是有的 
和文字在同一行了
我调整下

2019-04-28 07:48 UTC, donhui commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +开发人员可以对其进行扩展自定义实现一些功能。
嗯，这里我是在行尾加了两个空格，markdown 渲染的时候，会加换行

2019-04-28 07:48 UTC, donhui commented on articles/2019/05/2019-05-06-jenkins-plugin-develop-within-two-days-part01.md
> +Jenkins 是 Master/Slave 架构，
嗯，了解了，我改成 agent

2019-04-28 08:02 UTC, LinuxSuRen approved these changes
LGTM

2019-04-29 13:12 UTC, LinuxSuRen commented
`could not determine a constructor for the tag !`

看起来是感叹号（！）引起的问题，目前还没有找到解决办法。

2019-04-29 13:18 UTC, donhui commented
> `could not determine a constructor for the tag !`
> 
> 看起来是感叹号（！）引起的问题，目前还没有找到解决办法。

我看 Jenkinsfile 中用的是 readYaml 
理论上讲 这个 Markdown 不是纯粹的 yaml 文件
只是文件头遵循 yaml 格式
所以它读到下面就出错了

2019-04-29 13:22 UTC, LinuxSuRen commented
那我们可以截取一下头部信息，只对头部进行解析。

2019-04-29 13:54 UTC, donhui commented
或者 是不是可以把文件头 单独放到一个 yaml 文件 这样解析比较简单
不过这样可能需要改我们的规范

2019-04-30 00:11 UTC, LinuxSuRen commented
拆开不太好，GitHub 上也看不到那个信息了

2019-04-30 02:32 UTC, LinuxSuRen commented
为了触发构建，关闭后重新打开。

2019-05-06 06:33 UTC, merged

2019-05-13 13:33 UTC, zacker330 commented
* 简书：https://www.jianshu.com/p/391c89827ea5
* 掘金：https://juejin.im/post/5cd971e551882520354209ee