[原创-05-08]：Jenkins 插件开发之旅：两天内从 idea 到发布(下篇)
jenkins-infra/wechat pull request #104
Opened 2019-04-27 07:07 UTC by donhui

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-04-28 03:53 UTC, LinuxSuRen requested changes

2019-04-28 03:53 UTC, LinuxSuRen commented on articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02.md
> +poster: ![journey](../../../images/articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02/journey.png)
字段 `poster` 只支持字符串的。

另外，也可以把封面放到文章的开头

2019-04-28 04:56 UTC, donhui commented on articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02.md
> +poster: ![journey](../../../images/articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02/journey.png)
> 字段 `poster` 只支持字符串的。
> 
> 另外，也可以把封面放到文章的开头

已调整

2019-04-30 02:35 UTC, LinuxSuRen commented
为了触发构建，关闭后重新打开。

2019-05-07 15:15 UTC, LinuxSuRen requested changes
总体是个非常棒的教程

2019-05-07 15:15 UTC, LinuxSuRen commented on articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02.md
> +##### Artifact ID
建议统一使用 `artifactId` ，这样和 `pom.xml` 中也是对应的

2019-05-07 15:15 UTC, LinuxSuRen commented on articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02.md
> +因此需要在 GitHub 上有一个用户帐户，并且需要有一个公共仓库来存放插件源代码。
> 用户帐户?

感觉“账号”就可以了吧，或者你有其他的含义

2019-05-07 15:15 UTC, LinuxSuRen commented on articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02.md
> +### 开启托管请求
发起托管请求？

2019-05-07 15:15 UTC, LinuxSuRen commented on articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02.md
> +poster: 江边落日
这里可以放地址，这样的话，方便后续自动化程序获取。

../../../images/articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02/sunset.png

2019-05-07 15:20 UTC, donhui commented on articles/2019/05/2019-05-08-jenkins-plugin-develop-within-two-days-part02.md
> +##### Artifact ID
可以的

2019-05-07 15:28 UTC, LinuxSuRen approved these changes
LGTM

2019-05-08 00:10 UTC, merged

2019-05-13 13:41 UTC, zacker330 commented
* 简书：https://www.jianshu.com/p/c4d89d2c38d5
* 掘金：https://juejin.im/post/5cd973ebe51d453a4d530d9a