[原创-2019-05-07] Jenkins 自动化安装插件
jenkins-infra/wechat pull request #105
Opened 2019-04-27 15:43 UTC by zacker330

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-04-28 01:31 UTC, donhui commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +install-plugins 本质上做的事情就只是将插件从云端下载到 JENKINS_HOME 下的 plugins 目录中。要使安装的插件生效，还需要重启 Jenkins。
看到这里我有一个疑问：自动安装插件时它会安装相关依赖么？
当我去看了 shell 脚本后，我确定了它会自动安装相关依赖。
这里我建议增加"自动安装插件时它会自动解析相关依赖并进行安装"的说明。

2019-04-28 01:45 UTC, donhui commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +Jenkins 插件有两个名称。一个叫 display name，一个叫 short name。比如 Ansible 插件的 disply name 为 Ansible plugin，short  name 为 ansible。
看到这里的话，我查看了下 Jenkins 插件管理的 xml API 
![image](https://user-images.githubusercontent.com/5702065/56856996-cbb41400-6999-11e9-984b-47dd025bc3d9.png)
这里会有 longName 和 shortName 两个术语
而在 Jenkins 插件页面，会有 ID （对应 short name ）和 DisplayName（对应 longName ）
我想可不可以在这里进一步对术语进行说明。

2019-04-28 07:36 UTC, zacker330 commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +install-plugins 本质上做的事情就只是将插件从云端下载到 JENKINS_HOME 下的 plugins 目录中。要使安装的插件生效，还需要重启 Jenkins。
这个第 4 点，要说明的是为什么要重启。出现你这个疑问，可能是因为我在前文没有把“自动下载依赖”写清楚。

2019-04-28 07:41 UTC, zacker330 commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +Jenkins 插件有两个名称。一个叫 display name，一个叫 short name。比如 Ansible 插件的 disply name 为 Ansible plugin，short  name 为 ansible。
事实上，Jenkins 插件页面上使用的是插件的 displayName 属性。不是 longName。具体可以看这部分代码：https://github.com/jenkinsci/jenkins/blob/25f4e71977ba1e5326592876f0285c60faf948e9/core/src/main/resources/hudson/PluginManager/installed.jelly#L70

再看 PluginWrapper 类：displayName 与 longName 之间的关系：

```
  public String getDisplayName() {
        return StringUtils.removeStart(getLongName(), "Jenkins ");
  }
    @Exported
    public String getLongName() {
        String name = manifest.getMainAttributes().getValue("Long-Name");
        if(name!=null)      return name;
        return shortName;
    }
```

至于这两者的关系是否需要在文章里体现，个人觉得没有必要了。本文的重点不在这里。

2019-04-28 09:03 UTC, donhui commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +Jenkins 插件有两个名称。一个叫 display name，一个叫 short name。比如 Ansible 插件的 disply name 为 Ansible plugin，short  name 为 ansible。
了解了～

2019-04-30 12:05 UTC, donhui approved these changes

2019-04-30 12:49 UTC, LinuxSuRen requested changes
你的这个自动安装插件的例子很好，建议再加上一些描述这和在界面上安装的不同之处，例如：可以实现批量安装等。

2019-04-30 12:49 UTC, LinuxSuRen commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +幸运的是，Jenkins 的 Docker 镜像的代码仓库里的 install-plugins.sh 脚本已经实现。只不过需要我们拿过来小小修改才能使用。笔者修改后创建了相应的代码仓库：jenkins-install-plugins-shell 。链接在文章末尾。
> jenkins-install-plugins-shell

这个虽然下面有链接，这里也可以添加一个。

2019-04-30 12:49 UTC, LinuxSuRen commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +chmod +x install-plugins.sh jenkins-support
git 是支持把文件属性也一并提交的，也就说，如果你提交 install-plugins.sh jenkins-support 这两个文件时加了可执行权限，这里就不需要再次添加了。

2019-04-30 12:49 UTC, LinuxSuRen commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +author: zacker330
我们加个封面图片吧，字段里可以加 `poster`

2019-04-30 12:49 UTC, LinuxSuRen commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +description: "Jenkins 自动安装插件"
描述部分，尽量可以和标题不太一样

2019-05-05 00:19 UTC, zacker330 commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +chmod +x install-plugins.sh jenkins-support
嗯。我单独给 git 仓库里加上。文章里觉得写明会更好，让读者还知道有一个 jenkins-support 文件需要可执行权限。

2019-05-09 02:55 UTC, arjenzhou requested changes
提出一些语法上的修改意见

2019-05-09 02:55 UTC, raychou1203 commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +第一种方法是无法指定插件的版本。第二种方式必须自己找到该插件的依赖树，一个个依赖的安装。是的，手工上传插件的这种方法，Jenkins 是不会自动下载依赖的。
`一个个依赖的安装`
这里的 `的` 应该使用 `地`。同时建议改成 `根据依赖关系一个个地安装` 比较通顺

2019-05-09 02:55 UTC, raychou1203 commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +而且，这两种方式都无法实现批量安装。
这里上下文感觉是转折的关系。然而或者但是感觉更好一点

2019-05-09 02:55 UTC, raychou1203 commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +笔者为什么一定要确定 Jenkins 插件的版本？是因为插件的版本会影响 Jenkins 流水线的可靠性。所以，笔者才会这么在意 Jenkins 插件的版本。
感觉这里算不上是总结，可以增加一些对文章的概述。或者称为注意事项等。

2019-05-09 13:43 UTC, zacker330 commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +笔者为什么一定要确定 Jenkins 插件的版本？是因为插件的版本会影响 Jenkins 流水线的可靠性。所以，笔者才会这么在意 Jenkins 插件的版本。
其实，我就是想最后表达一下我为什么在意插件的版本化，毕竟很多人不在意。但是又不知道以什么标题。习惯在最后“总结”，所以沿用了。

2019-05-09 14:13 UTC, LinuxSuRen approved these changes

2019-05-09 14:13 UTC, donhui commented on articles/2019/04/2019-05-07-jenkins-install-plugins-shell.md
> +笔者为什么一定要确定 Jenkins 插件的版本？是因为插件的版本会影响 Jenkins 流水线的可靠性。所以，笔者才会这么在意 Jenkins 插件的版本。
后记？

2019-05-09 14:34 UTC, merged

2019-05-13 13:48 UTC, zacker330 commented
* 简书：https://www.jianshu.com/p/a01b8b41cd43
* 掘金：https://juejin.im/post/5cd975396fb9a03228618911