[原创-2019-05-13]Jenkins 公众号送书福利
jenkins-infra/wechat pull request #113
Opened 2019-05-08 23:48 UTC by zacker330

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-05-09 14:16 UTC, donhui commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +description: "两天内，从产生 idea 到编写插件，最后发布到 Jenkins 插件更新中心"
描述这里要改下

2019-05-09 14:17 UTC, donhui commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +1. 关注本公众号，关在后台回复【抽奖】，根据二维码进入小程序抽奖。
并在后台回复？

2019-05-09 14:31 UTC, LinuxSuRen requested changes

2019-05-09 14:31 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![](../../../images/wechat-qrcode.jpg)
公众号的二维码感觉可以不用在这里贴了。每篇文章的底部都会有的

2019-05-09 14:31 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![image.png](../../../images/articles/2019/05/2019-05-13-jenkins-book-gift/book-qrcode.png)
太多二维码了，感觉会不太合适

2019-05-09 14:31 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +当然，它也会为公众号的粉丝发放福利。
我们希望获奖的同学能够在收到书后，把书拍照（公众号的二维码，可选）发到自己的社交圈子里，例如：微信朋友圈

2019-05-09 23:42 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +description: "两天内，从产生 idea 到编写插件，最后发布到 Jenkins 插件更新中心"
额，这么低级的错误。

2019-05-09 23:42 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +1. 关注本公众号，关在后台回复【抽奖】，根据二维码进入小程序抽奖。
是错别字。

2019-05-09 23:42 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![](../../../images/wechat-qrcode.jpg)
如果你默认加，我就不用加了。

2019-05-09 23:43 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![image.png](../../../images/articles/2019/05/2019-05-13-jenkins-book-gift/book-qrcode.png)
这个二维码我觉得是有必要的。有些人是会想直接购买的。我见其他公众号都会这样做的。

2019-05-09 23:50 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +当然，它也会为公众号的粉丝发放福利。
嗯。理解你的意思。只是，我想不到如何让用户有那样的动机。

2019-05-10 00:23 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +1. 关注本公众号，并在后台回复【抽奖】，根据二维码进入小程序抽奖。
后台回复这具体怎么操作？

2019-05-10 00:27 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +当然，它也会为公众号的粉丝发放福利。
我们直接在文章上加上就好了，我相信这个对收到书的人来说不是件很难的事情，而且，对于其他类似活动来说，也都会这么做。

2019-05-10 01:15 UTC, donhui commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![image.png](../../../images/articles/2019/05/2019-05-13-jenkins-book-gift/book-qrcode.png)
建议加个换行，预览里 文字和图片在一行

2019-05-10 10:56 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +1. 关注本公众号，并在后台回复【抽奖】，根据二维码进入小程序抽奖。
额。就是给公众号发信息。

2019-05-10 11:01 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +当然，它也会为公众号的粉丝发放福利。
我在“参与方式”后加上一段鼓励的话吧。

2019-05-10 11:01 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![image.png](../../../images/articles/2019/05/2019-05-13-jenkins-book-gift/book-qrcode.png)
已加。

2019-05-11 07:38 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +1. 关注本公众号，并在后台回复【抽奖】，根据二维码进入小程序抽奖。
给公众号发信息，怎么根据二维码进入小程序呢？那你可能需要在 https://github.com/jenkins-infra/wechat/tree/master/management/auto-reply 这里参考其他的添加 PR 了

2019-05-11 07:40 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![image.png](../../../images/articles/2019/05/2019-05-13-jenkins-book-gift/book-qrcode.png)
图片1.64MB，是否可以压缩一下呢？

2019-05-11 07:42 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +中奖的同学，不要忘记发朋友圈分享支持噢~
这里既然是建议的话，我们可以直接加上更加明确的建议，例如：
收到书后，拍照并附言是通过参加 Jenkins 中文社区的活动得到的书。

2019-05-11 10:47 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![image.png](../../../images/articles/2019/05/2019-05-13-jenkins-book-gift/book-qrcode.png)
好的。

2019-05-11 10:49 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +中奖的同学，不要忘记发朋友圈分享支持噢~
感觉这样不好吧。我觉得嘛，要让用户自己心肝情愿的分享才行。

2019-05-11 10:50 UTC, LinuxSuRen commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +中奖的同学，不要忘记发朋友圈分享支持噢~
只是建议大家这么做，并不是强制的

2019-05-11 14:08 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +![image.png](../../../images/articles/2019/05/2019-05-13-jenkins-book-gift/book-qrcode.png)
已经修改。

2019-05-11 14:12 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +中奖的同学，不要忘记发朋友圈分享支持噢~
额。我感觉意图很明显了。

2019-05-11 14:58 UTC, zacker330 commented on articles/2019/05/2019-05-13-jenkins-book-gift.md
> +1. 关注本公众号，并在后台回复【抽奖】，根据二维码进入小程序抽奖。
有些操作上的失误，导致新的 pr 不成功。就不另提 pr 了。直接 commit 在这个 pr 中了。

2019-05-11 15:33 UTC, LinuxSuRen requested changes

2019-05-11 15:33 UTC, LinuxSuRen commented on management/auto-reply/keywords-lottery.yml
> +        <图片地址-要等13号早上生成>
这里建议修改为：抽奖尚未开始，请耐心等待。因为，这个 PR 一旦合并后，这个关键字就立马生效了。

2019-05-11 15:50 UTC, zacker330 commented on management/auto-reply/keywords-lottery.yml
> +        <图片地址-要等13号早上生成>
这样的？我改一下。

2019-05-12 00:23 UTC, LinuxSuRen approved these changes

2019-05-12 00:30 UTC, donhui approved these changes
LGTM

2019-05-12 14:25 UTC, merged