[翻译-2019-05-16]：与云无关的用于 Kubernetes 的自动化 CI/CD
jenkins-infra/wechat pull request #114
Opened 2019-05-09 16:02 UTC by donhui

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://dzone.com/articles/cloud-agnostic-automated-cicd-for-k8s)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-05-11 08:00 UTC, LinuxSuRen requested changes

2019-05-11 08:00 UTC, LinuxSuRen commented on articles/2019/04/2019-05-16-cloud-agnostic-automated-cicd-for-k8s.md
> +original: https://dzone.com/articles/cloud-agnostic-automated-cicd-for-k8s
缺少封面，我们需要在头信息以及首行加封面，这样方便同步到其他的平台

2019-05-11 08:00 UTC, LinuxSuRen commented on articles/2019/04/2019-05-16-cloud-agnostic-automated-cicd-for-k8s.md
> +希望本文为您提供一些输入，当您计划为多个云提供商提供生产级环境置备时，可以考虑这些输入。
> 输入

这里的意思虽然没有问题，但感觉读起来有点别扭。参考建议：

`希望本文为您提供一些参考，当您计划为多个云提供商提供生产级环境置备时，可以考虑这些参考。`

2019-05-11 08:00 UTC, LinuxSuRen commented on articles/2019/04/2019-05-16-cloud-agnostic-automated-cicd-for-k8s.md
> +这个模型帮助我们自动化所有的三个环境的置备。
> 置备

准备？预备？

2019-05-11 08:57 UTC, donhui commented on articles/2019/04/2019-05-16-cloud-agnostic-automated-cicd-for-k8s.md
> +这个模型帮助我们自动化所有的三个环境的置备。
Provisioning  很纠结这个词翻译成什么。。。
我看有的地方翻译成供应，有的翻译成准备，有的翻译成置备
或者按你的经验来说，这个翻译成什么比较好呢？

2019-05-11 09:01 UTC, donhui commented on articles/2019/04/2019-05-16-cloud-agnostic-automated-cicd-for-k8s.md
> +希望本文为您提供一些输入，当您计划为多个云提供商提供生产级环境置备时，可以考虑这些输入。
已调整

2019-05-11 10:48 UTC, LinuxSuRen commented on articles/2019/04/2019-05-16-cloud-agnostic-automated-cicd-for-k8s.md
> +这个模型帮助我们自动化所有的三个环境的置备。
我建议翻译为“准备”

2019-05-11 10:49 UTC, LinuxSuRen requested changes
封面图片的分辨率太高了，我们尽量让图片保持在300K以内，这样加载会比较快一点

2019-05-11 11:03 UTC, donhui commented on articles/2019/04/2019-05-16-cloud-agnostic-automated-cicd-for-k8s.md
> +这个模型帮助我们自动化所有的三个环境的置备。
已调整

2019-05-11 11:03 UTC, donhui commented
> 封面图片的分辨率太高了，我们尽量让图片保持在300K以内，这样加载会比较快一点

ok，已调整

2019-05-11 15:08 UTC, LinuxSuRen approved these changes

2019-05-15 23:32 UTC, merged

2019-05-17 23:55 UTC, zacker330 commented
* 简书：https://juejin.im/post/5cdf4994f265da1bd3052885
* 掘金：https://juejin.im/post/5cdf4994f265da1bd3052885

2019-05-18 10:30 UTC, yJunS commented
> * 简书：https://juejin.im/post/5cdf4994f265da1bd3052885
> * 掘金：https://juejin.im/post/5cdf4994f265da1bd3052885

简书的是投稿没批还是没投稿呢？

2019-05-18 10:32 UTC, yJunS commented
- CSDN：https://blog.csdn.net/u014249394/article/details/90318730
- 开源中国：https://my.oschina.net/jenkinszh/blog/3050662