[翻译-2019-05-20] 从 Jenkins 到 Jenkins X
jenkins-infra/wechat pull request #119
Opened 2019-05-12 12:08 UTC by donhui

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://medium.com/dailymotion/from-jenkins-to-jenkins-x-604b6cde0ce3)
    - x ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-05-13 11:55 UTC, LinuxSuRen requested changes
有一些小的问题要调整

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +description: "这是一个关于 dailymotion 从 Jenkins 到 Jenkins X 的旅程，我们遇到的问题，以及我们是如何解决它们的故事。"
描述语句的结尾不需要句号，并不是一个完整的段落语句

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +在 [dailymotion](https://www.dailymotion.com/) ，我们坚信 devops 最佳实践，并且在 Kubernetes 进行了大量投资。
> 并且在 Kubernetes 进行了大量投资

并且在 Kubernetes 投入了大量投资

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +我们的目标是**授权给我们的开发人员**，**缩短我们的上市时间**以及**降低我们的运营成本**。
> 上市

这个很容易理解为公司上市，但从上下文感觉应该是上线的意思。

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +Jenkins X 的设置相当简单，并且[在他们的网站上已经有很好的文档](https://jenkins-x.io/getting-started/create-cluster/)（译注：译者曾对 Jenkins X 文档中文本地化做了一些贡献，同时也期待更多的人参与以完善中文文档）。
这个地址，我们可以替换为中文的

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +每个应用程序都打包为一个" chart "，然后可以通过使用 helm 命令行工具作为一个 "release" 被部署。
> " chart "

这里的引号可以和英文去掉空格

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +但现在是 2018 年（译注：作者是在2018年写的这篇文章），没有人再使用 http 了。
2018不需要空格，后面的也没有

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +这给了我们一个机会来看看 Jenkins X的 源代码——它也是用 Go 开发的。
> Jenkins X的

空格

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +现在我们可以使用 [let 's encrypt](https://letsencrypt.org/) 提供的自动化证书来享受安全的预览环境。
> let 's encrypt

let's encrypt

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +我注意到的第一件事是 Jenkins  Pod 最近重新启动过。
> Jenkins  Pod

多余的空格

2019-05-13 11:55 UTC, LinuxSuRen commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +这将提高您的上市时间，降低您的成本，如果您对测试也很认真，那么请对您的软件质量充满信心。
上市？

2019-05-13 13:31 UTC, donhui commented on articles/2019/05/2019-05-17-from-jenkins-to-jenkins-x.md
> +我们的目标是**授权给我们的开发人员**，**缩短我们的上市时间**以及**降低我们的运营成本**。
是的～

2019-05-17 00:24 UTC, LinuxSuRen approved these changes

2019-05-17 00:24 UTC, merged

2019-05-27 23:25 UTC, zacker330 commented
* juejin: https://juejin.im/post/5cec700ef265da1b6e658291
* jianshu: https://www.jianshu.com/p/cfb2f4a891d0