[原创-20190520] 使用 Jenkins + Ansible 实现 Springboot 自动化部署101
jenkins-infra/wechat pull request #122
Opened 2019-05-15 00:27 UTC by zacker330

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-05-15 01:54 UTC, LinuxSuRen requested changes
图片还是按照我们新的规范来存放吧

2019-05-15 14:20 UTC, donhui commented
目录有点问题 # 后面要有空格

2019-05-15 22:20 UTC, zacker330 commented
> 图片还是按照我们新的规范来存放吧

fix

2019-05-15 22:20 UTC, zacker330 commented
> 目录有点问题 # 后面要有空格

fix

2019-05-16 13:51 UTC, donhui commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +description: ""
描述这里加下

2019-05-16 13:53 UTC, donhui commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +1. 自动化整个实验环境：包括 Jenkins 的配置，Jenkins slave 的配置等。
之前 晓杰 讲过 slave 这个不用被社区了（有歧视），建议改成 agent

2019-05-16 13:55 UTC, donhui commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +1. 自动化整个实验环境：包括 Jenkins 的配置，Jenkins slave 的配置等。
slave 被 agent 替代了

2019-05-16 13:59 UTC, donhui commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +title: "使用 Jenkins + Ansible 实现 Springboot 自动化部署101"
Spring Boot 我看一般这么写

2019-05-16 14:03 UTC, donhui commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +所有代码，均放在 GitHub: [https://github.com/cd-in-practice](https://github.com/cd-in-practice)
均放在 GitHub:
这里的冒号是英文，换成中文？

2019-05-16 14:04 UTC, donhui commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +使用 Vagrant  是为了启动虚拟机，用于部署 Springboot 应用。如果你的开发机器无法使用 Vagrant，使用 VirtualBox 也可以达到同样的效果。但是有一点需要注意，那就是网络。如果在虚拟机中要访问 Docker 容器内提供的服务，需要在 DNS 上或者 hosts 上做相应的调整。所有的虚拟机的镜像使用 Centos7。
使用 Vagrant  是为了启动虚拟机
Vagrant 后多了一个空格

2019-05-16 14:42 UTC, donhui commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +2. 简单易懂Ansible系列 —— 解决了什么[https://showme.codes/2017-06-12/ansible-introduce/](https://showme.codes/2017-06-12/ansible-introduce/)
中文后面建议加冒号 和上面保持一致

2019-05-17 00:21 UTC, zacker330 commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +1. 自动化整个实验环境：包括 Jenkins 的配置，Jenkins slave 的配置等。
有时，我还是混用。。

2019-05-17 00:24 UTC, zacker330 commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +description: ""
当时，也想过要加。但是想来想去，好像标题就已经说明问题了。不需要特别描述了。

2019-05-17 00:40 UTC, LinuxSuRen commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +description: ""
既然我们有规范，还是尽量按照规范来吧。如果规范有问题，我们可以修改规范。

2019-05-17 00:41 UTC, LinuxSuRen commented
你现在提交的记录里，应该用的不是你在 GitHub 中设置的邮箱地址

2019-05-17 00:47 UTC, LinuxSuRen requested changes

2019-05-17 00:47 UTC, LinuxSuRen commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +1. 使用 Jenkins + Ansible 实现自动化部署 Nginx：[https://showme.codes/2019-04-22/jenkins-ansible-nginx/](https://showme.codes/2019-04-22/jenkins-ansible-nginx/)
不建议添加个人站点的链接，可以在文中相关的位置增加超链接，而不是贴出域名网址来。

2019-05-17 15:21 UTC, donhui commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +      mvn clean test install
mvn 命令这里我个人提点建议：
我一般会用 `mvn clean package` ，而不是 `mvn clean install`
为什么这样呢？
如果共享本地 maven 仓库，install 会把一些组件 install 到本地仓库，会对其它引用这些组件的仓库带来不稳定影响，
而实际上外部依赖都应该来自 Maven 私服。
这是我个人的一些经验。

2019-05-17 23:30 UTC, zacker330 commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +description: ""
fix

2019-05-17 23:31 UTC, zacker330 commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +      mvn clean test install
你说的是对的。我改一下。我之前在本地都是 install 的。因为当时没有仓库。

2019-05-17 23:33 UTC, zacker330 commented
> 你现在提交的记录里，应该用的不是你在 GitHub 中设置的邮箱地址

我忘记 git config user.email zacker330@gmail.com 了。现在加上了。

2019-05-17 23:34 UTC, zacker330 commented on articles/2019/05/2019-05-20-jenkins-ansible-springboot.md
> +1. 使用 Jenkins + Ansible 实现自动化部署 Nginx：[https://showme.codes/2019-04-22/jenkins-ansible-nginx/](https://showme.codes/2019-04-22/jenkins-ansible-nginx/)
贴域名网址，还是为了照顾把文章发到公众号里的情况。因为公众号里不能外链的。只能这样。这样读者才能访问复制这个链接，然后访问。

2019-05-18 01:30 UTC, LinuxSuRen approved these changes
LGTM

2019-05-18 14:40 UTC, donhui approved these changes
LGTM

2019-05-19 12:08 UTC, merged

2019-05-27 23:30 UTC, zacker330 commented
* juejin: https://juejin.im/post/5cec71ef6fb9a07eec59a9bc
* jianshu: https://www.jianshu.com/p/02111c3a9367