[维护]增加转载规范声明
jenkins-infra/wechat pull request #127
Opened 2019-05-17 10:16 UTC by yJunS

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-05-17 11:41 UTC, LinuxSuRen requested changes

2019-05-17 11:41 UTC, LinuxSuRen commented on articles/2019/05/2019-05-20-translation-norms.md
> +首先感谢对 Jenkins 中文社区内容的认可。传播有道，我们希望每一篇文章的发声不仅能被看见，也都能得到尊重。因此，若需转载本社区的文章，请先获取本社区授权，未经授权禁止转载。
> 感谢对（谁）？

2019-05-17 11:41 UTC, LinuxSuRen commented on articles/2019/05/2019-05-20-translation-norms.md
> +2. 不论通过何种渠道获得本站文章，若想要转载，均可在文章下方留言，获得授权后方可进行在转载。
其他的行都没有句号，这个也不要了吧

2019-05-17 11:41 UTC, LinuxSuRen commented on articles/2019/05/2019-05-20-translation-norms.md
> +如需转载，请仔细阅读并遵守以下转载须知：
这个是要换行吗？看预览的效果没有换行。

2019-05-17 11:41 UTC, LinuxSuRen commented on articles/2019/05/2019-05-20-translation-norms.md
> +首先感谢对 Jenkins 中文社区内容的认可。传播有道，我们希望每一篇文章的发声不仅能被看见，也都能得到尊重。因此，若需转载本社区的文章，请先获取本社区授权，未经授权禁止转载。
我建议说明，如果未经许可的转载会怎么样？例如：我们会有专人负责沟通，对不听劝解的，会添加到社区官网的黑名单中公示。

2019-05-17 11:41 UTC, LinuxSuRen commented on articles/2019/05/2019-05-20-translation-norms.md
> +3. 转载前，原文标题不得进行修改，但标题前需注明`[转载]`
我感觉标题上可以不添加“转载”，而是在文章的第一行添加：本文转载自：Jenkins 中文社区，并添加链接

2019-05-17 12:49 UTC, yJunS commented on articles/2019/05/2019-05-20-translation-norms.md
> +3. 转载前，原文标题不得进行修改，但标题前需注明`[转载]`
那这条就可以把第五条替换掉来

2019-05-17 12:51 UTC, yJunS commented on articles/2019/05/2019-05-20-translation-norms.md
> +首先感谢对 Jenkins 中文社区内容的认可。传播有道，我们希望每一篇文章的发声不仅能被看见，也都能得到尊重。因此，若需转载本社区的文章，请先获取本社区授权，未经授权禁止转载。
我个人感觉在社区官网添加黑名单实际体现出来的意义没那么大

2019-05-17 15:31 UTC, LinuxSuRen commented on articles/2019/05/2019-05-20-translation-norms.md
> +首先感谢对 Jenkins 中文社区内容的认可。传播有道，我们希望每一篇文章的发声不仅能被看见，也都能得到尊重。因此，若需转载本社区的文章，请先获取本社区授权，未经授权禁止转载。
暂时的效果可能不明显，但还是有意义的。

2019-05-17 15:33 UTC, LinuxSuRen approved these changes
LGTM

2019-05-17 15:46 UTC, donhui commented on articles/2019/05/2019-05-20-translation-norms.md
> +- 转载规范
这里可否换成英文？ spec ？

2019-05-17 15:46 UTC, donhui commented on articles/2019/05/2019-05-20-translation-norms.md
> +date: 2019-05-17
日期也修改下

2019-05-18 14:42 UTC, donhui approved these changes
LGTM

2019-05-19 12:08 UTC, merged