[翻译-2019-05-24] 使用 Jenkins X、Kubernetes 和 Spring Boot 实现 CI/CD
jenkins-infra/wechat pull request #130
Opened 2019-05-18 09:43 UTC by yJunS

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-05-18 14:46 UTC, donhui commented
翻译地址 链接改下

2019-05-18 14:51 UTC, donhui commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +以 Kubernetes 为例。Google 于2014年开源，现在所有主流的公有云供应商都支持它---为开发人员提供了一种很好的方式，可以将应用程序打包到 Docker 容器种，并部署到任意 Kubernetes 集群中。
Docker 容器种
-->
Docker 容器中

2019-05-18 14:52 UTC, donhui commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +以 Kubernetes 为例。Google 于2014年开源，现在所有主流的公有云供应商都支持它---为开发人员提供了一种很好的方式，可以将应用程序打包到 Docker 容器种，并部署到任意 Kubernetes 集群中。
为开发人员提供了一种很好的方式
-->
它为开发人员提供了一种很好的方式
？

2019-05-18 14:52 UTC, donhui commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +```
代码片段 不翻译

2019-05-18 22:04 UTC, yJunS commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +```
。。。 这块我还记得改了一次

2019-05-21 03:20 UTC, donhui commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +提示：你可能会注意到,我必须为 `e2e-update` 和 `e2e-test` 分两次不同的执行。我发现运行 `npm e2e` 与 frontend-maven-plugin 不兼容，因为它只调用其他 `npm run` 命令。看来你需要在使用 frontend-maven-plugin 时直接调用二进制文件。
这里有 英文逗号

2019-05-21 06:07 UTC, zacker330 commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +当你在里面，添加一些秘密：`OKTA_APP_ID`、`E2E_USERNAME` 和 `E2E_PASSWORD`。第一个是你创建的 `Jenkins X` OIDC 应用程序的 ID。您可以通过在 Okta 上导航到您的应用程序并从 URL 复制值来获得它的值。该  `E2E-*` 密钥应该是要用来运行终端到终端（Protractor）测试的凭证。你可能想为此创建一个新用户。
秘密 -->  密文？ 会不会更好？

2019-05-21 06:07 UTC, zacker330 commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +当你在里面，添加一些秘密：`OKTA_APP_ID`、`E2E_USERNAME` 和 `E2E_PASSWORD`。第一个是你创建的 `Jenkins X` OIDC 应用程序的 ID。您可以通过在 Okta 上导航到您的应用程序并从 URL 复制值来获得它的值。该  `E2E-*` 密钥应该是要用来运行终端到终端（Protractor）测试的凭证。你可能想为此创建一个新用户。
其实，我觉得翻译成：“凭证”更好。虽然原文使用的是 secret

2019-05-21 06:07 UTC, zacker330 commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +在 Okta 中自动添加重定向 URI
原文这里是一个标题吧？
![image](https://user-images.githubusercontent.com/3665451/58071900-a305ef80-7bd0-11e9-84db-8c621fc16bf6.png)

2019-05-21 08:11 UTC, LinuxSuRen commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +当你在里面，添加一些秘密：`OKTA_APP_ID`、`E2E_USERNAME` 和 `E2E_PASSWORD`。第一个是你创建的 `Jenkins X` OIDC 应用程序的 ID。您可以通过在 Okta 上导航到您的应用程序并从 URL 复制值来获得它的值。该  `E2E-*` 密钥应该是要用来运行终端到终端（Protractor）测试的凭证。你可能想为此创建一个新用户。
https://github.com/jenkins-zh/translation-spec/blob/master/specification.md
我们这里有规范，secret 不翻译

2019-05-21 08:13 UTC, LinuxSuRen requested changes

2019-05-21 08:13 UTC, LinuxSuRen commented on management/operators/README.md
> +我们在每周一、三、五晚上九至十点发布文章。
这个提交记录是不是有问题？这里的变动已经合并过了。

2019-05-21 12:44 UTC, yJunS commented on management/operators/README.md
> +我们在每周一、三、五晚上九至十点发布文章。
这个有可能。。。

2019-05-21 12:59 UTC, LinuxSuRen commented
你不能这样直接删除文件，会把代码库中的删除了的。另外，现在冲突了。

2019-05-21 14:29 UTC, yJunS commented
这样应该可以了。  这个分支rebase的时候，被另一个分支占用了，没删除，导致重复提交了，这下应该可以了

2019-05-22 00:28 UTC, LinuxSuRen requested changes

2019-05-22 00:28 UTC, LinuxSuRen commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +poster: "../05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring/218555ae4b7cda6108cb48d15e26a7b07bae408f50b13845496a07be904ac03e.png"
这个图片不太适合做封面，只是个截图。另外，这个文件名太长了。

2019-05-22 00:28 UTC, LinuxSuRen commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +注意：如果你的帐户启用了双因素身份验证，则 GitHub 集成将失败。如果你希望成功完成该过程，则需要在 GitHub 上禁用它。
> 双因素身份验证

好多地方都翻译为“两步认证”

2019-05-22 00:29 UTC, LinuxSuRen commented on articles/2019/05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring.md
> +poster: "../05/2019-05-24-achieve-cicd-with-jenkins-x-kubernetes-and-spring/218555ae4b7cda6108cb48d15e26a7b07bae408f50b13845496a07be904ac03e.png"
文章的开头要加封面

2019-05-24 00:59 UTC, LinuxSuRen approved these changes

2019-05-24 01:18 UTC, donhui approved these changes
LGTM

2019-05-24 03:33 UTC, zacker330 approved these changes
LGTM

2019-05-24 10:59 UTC, merged