[翻译-2019-05-27] Jenkins 文档特别兴趣小组
jenkins-infra/wechat pull request #133
Opened 2019-05-22 15:00 UTC by donhui

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2019/05/11/docs-sig-announcement/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-05-23 00:39 UTC, LinuxSuRen approved these changes
LGTM

2019-05-23 12:29 UTC, zacker330 approved these changes
Jenkins 和 Jenkins X，乍一看还以为一行重复了2次。

LGTM

2019-05-25 06:45 UTC, LinuxSuRen requested changes

2019-05-25 06:45 UTC, LinuxSuRen commented on articles/2019/05/2019-05-27-docs-sig-announcement.md
> +author: markewaite
补充一下 keywords 吧，方便搜索引擎检索。由于我们的内容是中文的，因此关键字也应该是中文的（除了术语）

2019-05-25 06:45 UTC, LinuxSuRen commented on articles/2019/05/2019-05-27-docs-sig-announcement.md
> +![Jenkins_Needs_You](./2019-05-27-docs-sig-announcement/Jenkins_Needs_You-02.png)
按照我们的最新规范来定义图片的路径吧，可以从预览地址中看到预览效果。  

`![Jenkins_Needs_You](Jenkins_Needs_You-02.png)`

预览地址如下  
http://wechat-pr-133.preview.jenkins-zh.cn/wechat/articles/2019/05/2019-05-27-docs-sig-announcement/

2019-05-25 14:24 UTC, donhui commented on articles/2019/05/2019-05-27-docs-sig-announcement.md
> +author: markewaite
发现文章格式校验会有问题：

2019-05-25 14:30 UTC, donhui commented on articles/2019/05/2019-05-27-docs-sig-announcement.md
> +![Jenkins_Needs_You](./2019-05-27-docs-sig-announcement/Jenkins_Needs_You-02.png)
已调整

2019-05-26 01:50 UTC, yJunS commented on articles/2019/05/2019-05-27-docs-sig-announcement.md
> +- Jenkins X文档
- Jenkins文档特别兴趣小组
- Jenkins文档
- Jenkins X文档
是否应该把中英文之间加空格
或者为了检索度更高的话，可以把两种都加上

2019-05-26 01:56 UTC, donhui commented on articles/2019/05/2019-05-27-docs-sig-announcement.md
> +- Jenkins X文档
我用百度/必应试了下，加不加搜索结果一样的

2019-05-26 02:10 UTC, yJunS commented on articles/2019/05/2019-05-27-docs-sig-announcement.md
> +- Jenkins X文档
嗯。   那也可以。   那这里我们要不要统一一下，是否中英文之间空格

2019-05-26 02:12 UTC, donhui commented on articles/2019/05/2019-05-27-docs-sig-announcement.md
> +- Jenkins X文档
统一下吧 中英文之间加上空格
我改下

2019-05-26 05:32 UTC, LinuxSuRen approved these changes

2019-05-26 13:55 UTC, yJunS approved these changes
LGTM

2019-05-27 00:07 UTC, merged