[翻译-2019-6-17] 10节课带你深入学习 DevOps 工程
jenkins-infra/wechat pull request #158
Opened 2019-06-12 08:35 UTC by linan607

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-06-12 09:38 UTC, donhui reviewed
翻译的还不错
有几个小细节需要调整下
加油～

2019-06-12 09:38 UTC, donhui commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +description: "对那些想要涉足DevOps领域的工程师来说，这些多样的课程提供了一个很好的开始。"
DevOps 前后加空格
同时，description 最后面的句号去掉

2019-06-12 09:38 UTC, donhui commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +Devops 最重要的优势,它可以帮助你更好地发布软件并且利用现代自动化工具对环境和软件开发过程中提供更多控制。这就是 DevOps 专业人员需求呈指数增长的原因。除了 [Data Science](http://javarevisited.blogspot.sg/2018/02/top-10-highest-paying-technical-jobs-programmers-software-
Devops 最重要的优势,
英文逗号要改成中文

2019-06-12 09:38 UTC, donhui commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +为了成为一名有效的 DevOps 工程师，您必须扩展对软件开发中使用的不同工具的知识，包括构建工具（如 [Maven](https://www.java67.com/2018/02/6-free-maven-and-jenkins-online-courses-for-java-developers.html)、 [Ant](http://javarevisited.blogspot.sg/20
源代码。控制工具
这里是不是多了个句号

2019-06-12 09:38 UTC, donhui commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +为了成为一名有效的 DevOps 工程师，您必须扩展对软件开发中使用的不同工具的知识，包括构建工具（如 [Maven](https://www.java67.com/2018/02/6-free-maven-and-jenkins-online-courses-for-java-developers.html)、 [Ant](http://javarevisited.blogspot.sg/20
Jenkins和
中英文之间空格

2019-06-12 14:40 UTC, yJunS requested changes

2019-06-12 14:40 UTC, yJunS commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +简而言之，这是一门很好的[入门课程](https://www.udemy.com/modern-devops/?ranMID=39197&ranEAID=JVFxdTr9V80&ranSiteID=JVFxdTr9V80-eT7gjFt1RQj79SW2rayyXA&LSNPUBID=JVFxdTr9V80)，适用于系统管理员、开发人员和IT专业人员等 DevOps 领域的新手，还提供了对基本
开发人员和IT专业人员 ->
开发人员和 IT 专业人员

2019-06-12 21:57 UTC, zacker330 approved these changes

2019-06-13 02:32 UTC, linan607 commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +description: "对那些想要涉足DevOps领域的工程师来说，这些多样的课程提供了一个很好的开始。"
好的。下次注意描述的格式

2019-06-13 02:33 UTC, linan607 commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +Devops 最重要的优势,它可以帮助你更好地发布软件并且利用现代自动化工具对环境和软件开发过程中提供更多控制。这就是 DevOps 专业人员需求呈指数增长的原因。除了 [Data Science](http://javarevisited.blogspot.sg/2018/02/top-10-highest-paying-technical-jobs-programmers-software-
OK

2019-06-13 02:34 UTC, linan607 commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +简而言之，这是一门很好的[入门课程](https://www.udemy.com/modern-devops/?ranMID=39197&ranEAID=JVFxdTr9V80&ranSiteID=JVFxdTr9V80-eT7gjFt1RQj79SW2rayyXA&LSNPUBID=JVFxdTr9V80)，适用于系统管理员、开发人员和IT专业人员等 DevOps 领域的新手，还提供了对基本
OK

2019-06-13 03:09 UTC, donhui approved these changes
LGTM

2019-06-13 17:24 UTC, yJunS requested changes

2019-06-13 17:24 UTC, yJunS commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +它提供了一个关于 DevOps 基本技术的完整教程。您将通过实践指导学习 Docker Mastery、Jenkins、Git、Vagrant 和Maven。
和Maven ->
和 Maven

2019-06-13 17:24 UTC, yJunS commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +这意味着这是一个学习 DevOps 并进入这个更负责任、高薪和令人兴奋的领域的绝佳机会。如果你打算在2019年成为一名DevOps 工程师，那么这些课程是一个很好的起点。
一名DevOps   ->
一名 DevOps

2019-06-14 02:02 UTC, linan607 commented on articles/2019/06/2019-06-17-10-courses-to-learn-devops-engineering-in-depth.md
> +这意味着这是一个学习 DevOps 并进入这个更负责任、高薪和令人兴奋的领域的绝佳机会。如果你打算在2019年成为一名DevOps 工程师，那么这些课程是一个很好的起点。
已修正

2019-06-16 13:36 UTC, merged