提交一篇原创文章
jenkins-infra/wechat pull request #164
Opened 2019-06-19 09:53 UTC by eryajf

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-06-20 00:39 UTC, zacker330 commented
建议标题的 PR 规范一些，别人一眼看不出这个 PR 的具体内容。

2019-06-20 00:43 UTC, zacker330 commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +Jenkins角色权限控制Role-Based-Strategy（小黄锁）探微
这一行不需要了。

2019-06-20 00:43 UTC, zacker330 commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +- tags: Jenkins，plugin
这应该是英文逗号啊。

2019-06-20 00:43 UTC, zacker330 commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +- original: [原文链接](http://www.eryajf.net/1445.html "原文链接")
original: http://www.eryajf.net/1445.html

应该这样。

2019-06-20 01:53 UTC, LinuxSuRen commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +- original: [原文链接](http://www.eryajf.net/1445.html "原文链接")
这个字段是针对翻译的文章的

2019-06-20 01:53 UTC, LinuxSuRen commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +- tags: Jenkins，plugin
这里不是逗号分割，请参考其他的文章

2019-06-20 01:54 UTC, LinuxSuRen requested changes
请参考其他的 PR 标题

2019-06-20 01:59 UTC, eryajf commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +- tags: Jenkins，plugin
> 这里不是逗号分割

是无序列表的样式么？逗号问题我已经在处理

2019-06-20 06:06 UTC, LinuxSuRen commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +- title: **Jenkins角色权限控制Role-Based-Strategy（小黄锁）探微**
这里的格式和其他的是不一样的

2019-06-20 16:17 UTC, yJunS requested changes

2019-06-20 16:17 UTC, yJunS commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +![](http://t.eryajf.net/imgs/2019/05/2edabcc2be850178.jpg)
建议图片及路径尽量使用本地都好一些，避免万一其他服务停止，导致访问不到

2019-06-20 16:17 UTC, yJunS commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +如果公司比较小，有可能所有环境（此处的环境指测试，预发，线上）的Jenkins都在一台之上，那么在这种情况下，做好Jenkins项目视图以及权限的控制就显得非常重要了。
文章内容中建议让中英文之间添加空格
基本规范如下：
1.数字与中文之间无需空格
2.英文与中文之间需要空格（如：等 Jenkins 都在一台之上）
3.连接符号如括号、减号与中文间无需空格

2019-06-20 16:17 UTC, yJunS commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +如果公司稍微大一些，项目可能七七八八有不少，如此多项目的情况下，如何让负责`开发a`的同学就只能看到`a项目`，负责`开发b`的同学只能看到`b项目`呢，这就要请出我们今天的主角了，Jenkins当中的`角色控制`。
中英文之间空格问题

2019-06-20 16:17 UTC, yJunS commented on articles/2019/06/2019-06-22-Jenkins角色权限控制Role-Based-Strategy(小黄锁)探微.md
> +Jenkins的角色控制依赖于插件：[Role-Based Strategy](https://wiki.jenkins.io/display/JENKINS/Role+Strategy+Plugin "Role-Based Strategy")。点击链接可以跳转到插件对应的官方文档。
当前以及下方应该还有中英文空格问题，尽量仔细检查一下

2019-06-23 23:46 UTC, zacker330 approved these changes
主要问题还是格式上有一些不一致，但是问题不大。希望下次行文格式能更统一一些。

2019-07-05 08:40 UTC, yJunS commented
此PR还继续吗？  因为文件名及文件夹名带中文名格式等问题未修复，并且日期也已过期，如暂不修改的话。可以暂时先关闭此PR，后续如要修改的话，可随时打开

2019-07-05 10:27 UTC, closed without merging