提交另外一篇原创文章
jenkins-infra/wechat pull request #165
Opened 2019-06-19 09:58 UTC by eryajf

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-06-19 09:59 UTC, eryajf commented
图片过大可能是因为我用习惯了台式电脑，然后截取的页面实在小不下来，后续会注意此问题

2019-06-19 10:02 UTC, LinuxSuRen commented
> 图片过大可能是因为我用习惯了台式电脑，然后截取的页面实在小不下来，后续会注意此问题

理解，主要是图片太大的话，会导致我们拉取仓库比较慢。

2019-06-20 00:26 UTC, zacker330 commented
> 图片过大可能是因为我用习惯了台式电脑，然后截取的页面实在小不下来，后续会注意此问题

图片过大，如果不借助第三方工具，会很麻烦，我个人亲身体验。所以，我自己的做法是将图片拷贝到简书的编辑器中，它会对图片进行压缩。然后，你再把图片弄到你自己的博客中。

另外，你自己的博客也是需要考虑图片大小的，太大了，网络占用会过多，用用户体验不好。

2019-06-20 00:31 UTC, eryajf commented
之前一直在用新浪的图床，没考虑大小的问题，现在新浪不开放了，就自建了一个，更多时候还是考虑到图片是否清晰，是否将意思传达到位了。不过我也有用压缩工具进行压缩，叫Imagine，压缩比以及清晰度控制的都还不错，这次的文章也都会经过一次压缩才上传的

2019-06-20 01:55 UTC, LinuxSuRen requested changes
请参考我们对 PR 标题的规范

2019-06-20 06:05 UTC, LinuxSuRen commented
文件头的格式，和其他的文章也是不一样的，建议还是先参考一下其他的文章

2019-06-20 09:58 UTC, donhui reviewed
图片路径，请修改下，使用本地相对路径

2019-06-20 16:20 UTC, yJunS commented
之前提交的pr可以修改的。不是必须重新提交一个新的pr才可以。如果是文章类的，请保证一篇文章对应一个pr

2019-06-20 23:09 UTC, LinuxSuRen approved these changes
谢谢投稿。后续的原创文章，我们希望首次提交到这里来。

2019-06-20 23:11 UTC, LinuxSuRen commented
大家应该遵守经过讨论后确定下来的规则（格式、规范等），不然的话，每个人都有各自的风格，整体看起来就会有拼凑的感觉。

2019-06-21 01:09 UTC, eryajf commented
恩恩，整个流程也在慢慢熟悉当中，之前没有想到还能继续基于那个pr进行改造，万事开头难，非常感谢诸位耐心指导，我先去把图片路径更改一下去

2019-06-21 01:10 UTC, eryajf commented
对了，我使用typora进行日常笔记的编写，然后图片的话都是放在自己的图床上了，，你们平时写的时候，图片路径都是怎么快捷方便的编辑的呢

2019-06-21 08:59 UTC, donhui approved these changes

2019-06-21 09:07 UTC, LinuxSuRen commented
> 对了，我使用typora进行日常笔记的编写，然后图片的话都是放在自己的图床上了，，你们平时写的时候，图片路径都是怎么快捷方便的编辑的呢

把图片全部提交的代码仓库里也不一定是最好的办法，图床是个不错的主意。如果有办法结合起来的话也是可以的。

2019-06-21 09:19 UTC, eryajf commented
> 图床是个不错的主意

我在使用自建图床之前，用的图床工具是PicGo，也是非常优秀的一款工具，它支持多种图床的图片快速上传，其中还支持github，所以感觉上我们可以把图片和代码分离，单独创建一个项目作为图片仓库，然后通过那个工具进行push，也算是一种思路。而且还免费！！

2019-06-21 09:38 UTC, LinuxSuRen commented
赞同，我和其他的一些人可能不是特别了解这个流程。如果你方便的话，可以整体考虑下流程、操作、说明等内容，出个方案，大家讨论下。

> On Jun 21, 2019, at 17:19, eryajf <notifications@github.com> wrote:
> 
> 图床是个不错的主意
> 
> 我在使用自建图床之前，用的图床工具是PicGo，也是非常优秀的一款工具，它支持多种图床的图片快速上传，其中还支持github，所以感觉上我们可以把图片和代码分离，单独创建一个项目作为图片仓库，然后通过那个工具进行push，也算是一种思路。而且还免费！！
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/jenkins-infra/wechat/pull/165?email_source=notifications&email_token=AALCFPI2GUYC55P4RRBAFMTP3SMLXA5CNFSM4HZH5CE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYH564Y#issuecomment-504356723>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AALCFPJELA6PNRBLXMNWB3DP3SMLXANCNFSM4HZH5CEQ>.
>

2019-06-21 09:41 UTC, eryajf commented
没问题，周末我整理出一个方案出来

2019-06-26 02:02 UTC, merged

2019-07-05 00:28 UTC, zacker330 commented
* https://juejin.im/post/5d1e99766fb9a07eff00a6dd
* https://www.jianshu.com/p/f396b48aed5e