[原创-20190708]Jenkins 中文社区技术交流微信群问题集之一
jenkins-infra/wechat pull request #174
Opened 2019-07-03 04:36 UTC by zacker330

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-07-03 11:05 UTC, donhui reviewed
有几处中英文之间没有空格～

2019-07-03 11:05 UTC, donhui commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +### 4. 怎么把 slave 的内容copy到master机器上？
中英文空格

2019-07-05 08:00 UTC, yJunS requested changes

2019-07-05 08:00 UTC, yJunS commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +> 因为比如我用有一个windows节点，然后我代码拉取后，需要进行一些测试，测试完成后生成数据和HTML报告，这部分测试全都在节点上完成，我想把测试完成后到数据发到master上，然后由master生成html报告
因为比如我用有一个windows节点，然后我代码拉取后，需要进行一些测试，测试完成后生成数据和HTML报告，这部分测试全都在节点上完成，我想把测试完成后到数据发到master上，然后由master生成html报告
-->
 因为比如我用有一个 windows 节点，然后我代码拉取后，需要进行一些测试，测试完成后生成数据和 HTML 报告，这部分测试全都在节点上完成，我想把测试完成后到数据发到 master 上，然后由 master 生成 html 报告

2019-07-05 08:00 UTC, yJunS commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +不确定，我是否理解正确。可以考虑这样做，把你现在的事情分成两个阶段，阶段一在windows上测试，然后将数据和html报告上传到某个地方，阶段二，将数据和报告下载回来，比如下载到 master 上。接着，想干嘛就干嘛了。
阶段一在windows上测试，然后将数据和html报告上传到某个地方
-->
阶段一在 windows 上测试，然后将数据和 html 报告上传到某个地方

2019-07-05 08:00 UTC, yJunS commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +> 我的仓库一共有4个 分别存放 代码 战斗脚本 资源 协议。4个代码仓库各有3个分支  名字都是对应的，比如1号仓库分支 master develop production.  2号仓库 也是这几个分支 以此类推  我拉取代码进行打包的时候 会拉取 4个仓库名字都叫master的分支 或者名字都叫develop的分支进行打包
都叫master的分支 或者名字都叫develop的分支进行打包
-->
都叫 master 的分支 或者名字都叫 develop 的分支进行打包

2019-07-05 08:00 UTC, yJunS commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +现在问题就出在 我拉取4分仓库都叫master 的分支的时候 拉取完代码后 最后一个仓库的代码会把前个仓库的代码覆盖掉，后来有老哥给了建议  用dir  分别存到workspace下的好几个目录
都叫master 的分支的时候 拉取完代码后 最后一个仓库的代码会把前个仓库的代码覆盖掉，后来有老哥给了建议  用dir  分别存到workspace下的好几个目录
-->
都叫 master 的分支的时候 拉取完代码后 最后一个仓库的代码会把前个仓库的代码覆盖掉，后来有老哥给了建议  用 dir 分别存到 workspace 下的好几个目录

2019-07-05 08:00 UTC, yJunS commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +现在遇到的问题是  我多分支流水线第一次启动时，会把1号仓库的代码直接拉到workspace下
拉到workspace下
-->
拉到 workspace 下

2019-07-05 08:00 UTC, yJunS commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +建立一条流水线，接受gitlab触发，然后根据触发请求中的数据，决定拉取哪个代码仓库。参考 [Generic Webhook Trigger 插件](https://wiki.jenkins.io/display/JENKINS/Generic+Webhook+Trigger+Plugin)。
接受gitlab触发
-->
接受 gitlab 触发

2019-07-05 08:00 UTC, yJunS commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +> pipeline 中怎么指定这个流水线的工作目录，我在开头定义WORKSPACE但是没用
我在开头定义WORKSPACE但是没用
-->
我在开头定义 WORKSPACE 但是没用

2019-07-05 08:00 UTC, yJunS commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +> 请教下pipeline需要引用第三方jar包时，要放在哪里才能被import进来啊，我放到classpath下还是不行，总是提示找不到包[皱眉]在本地执行groovy，import进来没有问题
请教下pipeline需要引用第三方jar包时，要放在哪里才能被import进来啊，我放到classpath下还是不行，总是提示找不到包[皱眉]在本地执行groovy，import进来没有问题
-->
请教下 pipeline 需要引用第三方 jar 包时，要放在哪里才能被 import 进来啊，我放到 classpath 下还是不行，总是提示找不到包[皱眉]在本地执行 groovy，import 进来没有问题

2019-07-05 13:03 UTC, LinuxSuRen requested changes

2019-07-05 13:03 UTC, LinuxSuRen commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +title: "Jenkins 中文社区技术交流微信群问题集之一"
> Jenkins 中文社区技术交流微信群问题集之一

修改为`Jenkins 常见问题总结系列～第一篇`怎么样？我们在标题上可以不用体现中文社区，而在描述中再说明是有中文社区总结出来的。

2019-07-05 13:03 UTC, LinuxSuRen commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +description: "问题太多，只能挑选一些记录下来"
描述通常是可以单独说明白一件事情的，这里的表述有点像是在补充说明，缺少上下文。`问题太多`可能会导致读者误以为太差，而我的理解是：群里讨论过的问题（使用方法、缺陷）太多，无法全部包含。

2019-07-05 13:03 UTC, LinuxSuRen commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +### 1. 同一流水线，如何做某个阶段定时执行代码扫描
我们之前的规范是，一级标题两个井号`##`

2019-07-05 13:03 UTC, LinuxSuRen commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +这个需求的意思是存在一条流水线，流水线中的阶段为：构建阶段 --> 代码扫描阶段 --> 发布测试环境阶段 --> ... 而提问者希望当有代码提交时，就执行整条流水线。当到某个时间点时，就只执行扫描阶段。
> 这个需求的意思是存在一条流水线，流水线中的阶段为：构建阶段 --> 代码扫描阶段 --> 发布测试环境阶段 --> ...

这个需求希望的效果是，某条包含类似阶段：构建阶段 --> 代码扫描阶段 --> 发布测试环境阶段 --> ... 的流水线，当有代码提交后，执行整条流水线。当到某个时间点时，就只执行扫描阶段。

2019-07-05 13:03 UTC, LinuxSuRen commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +这个需求的意思是存在一条流水线，流水线中的阶段为：构建阶段 --> 代码扫描阶段 --> 发布测试环境阶段 --> ... 而提问者希望当有代码提交时，就执行整条流水线。当到某个时间点时，就只执行扫描阶段。
这个问题没有回答吗？如果没有的话，是否明确写出来，不然读者会感觉困惑。

2019-07-05 13:03 UTC, LinuxSuRen commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +增量包，四五年前我弄过，构建工具也是 ant。记得当初是根据修改的文件路径，解析出 ant target 列表，然后根据事先声明好的依赖关系对它排序，然后执行 ant 构建命令，最后将生成的二进制包挑出来生成增量包，大致这么个思路。
> 弄过

建议使用更加书面的表述。

2019-07-05 13:13 UTC, donhui commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +增量包，四五年前我弄过，构建工具也是 ant。记得当初是根据修改的文件路径，解析出 ant target 列表，然后根据事先声明好的依赖关系对它排序，然后执行 ant 构建命令，最后将生成的二进制包挑出来生成增量包，大致这么个思路。
> > 弄过
> 
> 建议使用更加书面的表述。

可以改为：有过相关实践

2019-07-06 21:32 UTC, zacker330 commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +title: "Jenkins 中文社区技术交流微信群问题集之一"
为什么要这样的标题，是想宣传我们的这个技术交流群。让更多人加入到这个群里。

2019-07-06 21:35 UTC, zacker330 commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +增量包，四五年前我弄过，构建工具也是 ant。记得当初是根据修改的文件路径，解析出 ant target 列表，然后根据事先声明好的依赖关系对它排序，然后执行 ant 构建命令，最后将生成的二进制包挑出来生成增量包，大致这么个思路。
这是回答者的原话。我原本觉得是没有必要加工处理的。

2019-07-07 01:23 UTC, LinuxSuRen commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +增量包，四五年前我弄过，构建工具也是 ant。记得当初是根据修改的文件路径，解析出 ant target 列表，然后根据事先声明好的依赖关系对它排序，然后执行 ant 构建命令，最后将生成的二进制包挑出来生成增量包，大致这么个思路。
读者从目前的表述上分辨不出来是我们官方给出的答案，还是收集的答案，我认为还是区分开比较好。不然，肯定是会有歧义的。

2019-07-07 01:25 UTC, LinuxSuRen commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +title: "Jenkins 中文社区技术交流微信群问题集之一"
我们更重要的是宣传社区，大家不加这个群也没关系，只要能解决了自己的问题即可。群的人数多，并不是我们的目标。

2019-07-07 21:26 UTC, zacker330 commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +title: "Jenkins 中文社区技术交流微信群问题集之一"
了解。我也认为宣传社区是更重要的。而这个微信群是宣传社区的非常好的手段，所以，我才用这个标题。从目前来看，微信群给我们带来了一些新人。

2019-07-07 21:32 UTC, zacker330 commented on articles/2019/07/2019-07-08-wechat-answer-1.md
> +增量包，四五年前我弄过，构建工具也是 ant。记得当初是根据修改的文件路径，解析出 ant target 列表，然后根据事先声明好的依赖关系对它排序，然后执行 ant 构建命令，最后将生成的二进制包挑出来生成增量包，大致这么个思路。
这个说的对。我在文章前面加入一段申明的描述，让读者了解。

2019-07-08 08:01 UTC, LinuxSuRen approved these changes

2019-07-08 08:02 UTC, merged