[翻译-2019-07-18] weekly release from 2.180 to 2.184
jenkins-infra/wechat pull request #185
Opened 2019-07-16 13:54 UTC by LinuxSuRen

对应的 PR https://github.com/jenkins-infra/cn.jenkins.io/pull/214

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-07-16 14:26 UTC, zacker330 approved these changes

2019-07-17 15:01 UTC, yJunS requested changes

2019-07-17 15:01 UTC, yJunS commented on articles/2019/07/2019-07-18-jenkins-weekly-release.md
> +* 更新 Remoting 3.29 到 3.33. (issue 57959, issue 50095, issue 57713, 完整变更日志)
> 更新 Remoting 3.29 到 3.33.
去掉最后的‘.’或者改成‘。’?

2019-07-17 15:01 UTC, yJunS commented on articles/2019/07/2019-07-18-jenkins-weekly-release.md
> +* 更新 args4j 2.0.31 到 2.33. (issue 57959)
> 2.33. 
后面的‘.’是不是应该去掉或者改成中文'。'？

2019-07-18 07:44 UTC, donhui approved these changes

2019-07-18 08:24 UTC, merged