[翻译-2019-07-29] 在 Kubernetes 上使用 Jenkins
jenkins-infra/wechat pull request #188
Opened 2019-07-22 06:46 UTC by baobeizuoshoubuli

[翻译-2019-07-29] 在 Kubernetes 上使用 Jenkins 

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-07-22 08:06 UTC, LinuxSuRen requested changes
有一些格式上的小问题需要调整下。

2019-07-22 08:06 UTC, LinuxSuRen commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +description: " Jenkins 是一个功能强大的自动化和 CI / CD 工具，可以成为 Kubernetes 流水线的重要组成部分。"
> CI / CD

一般这里不会有空格 `CI/CD`

2019-07-22 08:06 UTC, LinuxSuRen commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +description: " Jenkins 是一个功能强大的自动化和 CI / CD 工具，可以成为 Kubernetes 流水线的重要组成部分。"
描述语句不需要有`句号`结尾

2019-07-22 08:06 UTC, LinuxSuRen commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +# 在 Kubernetes 上使用 Jenkins
已经有了一级标题了，这里就不需要了

2019-07-22 08:06 UTC, LinuxSuRen commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +
如果没有特殊理由的话，不建议保留很多空行

2019-07-22 08:06 UTC, LinuxSuRen commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +## **CI/CD** **流水线**
标题本身就是加粗过的，不需要再次加粗了。

2019-07-22 08:56 UTC, baobeizuoshoubuli commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +## **CI/CD** **流水线**
ok

2019-07-22 11:37 UTC, donhui reviewed
感谢你的贡献！
有一些细节需要调整下～

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​由于 Jenkins 和 Kubernetes 的本地兼容性，设置自己的 CI/CD 流水线非常容易。与基于 VM-based 的部署相比，在 Kubernetes 上部署 Jenkins 优势更明显。例如，获得按需拥有特定于 Jenkins slaves (代理)项目的能力，而不是让一个 vm 池空闲等待作业。它将使用 master-agent  体系结构来完全自动化微服务的创建和部署以及测
本地兼容性
-->
原生兼容性

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​由于 Jenkins 和 Kubernetes 的本地兼容性，设置自己的 CI/CD 流水线非常容易。与基于 VM-based 的部署相比，在 Kubernetes 上部署 Jenkins 优势更明显。例如，获得按需拥有特定于 Jenkins slaves (代理)项目的能力，而不是让一个 vm 池空闲等待作业。它将使用 master-agent  体系结构来完全自动化微服务的创建和部署以及测
基于 VM-based
-->
基于 VM

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​由于 Jenkins 和 Kubernetes 的本地兼容性，设置自己的 CI/CD 流水线非常容易。与基于 VM-based 的部署相比，在 Kubernetes 上部署 Jenkins 优势更明显。例如，获得按需拥有特定于 Jenkins slaves (代理)项目的能力，而不是让一个 vm 池空闲等待作业。它将使用 master-agent  体系结构来完全自动化微服务的创建和部署以及测
作业
-->
任务

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​可以使用 [Helm](https://github.com/helm/helm)、[kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/) 或 GUIs 部署 Jenkins ，以便将新的 pods 部署到集群中。安装后，下一步是为 [K8s](https://plugins.jenkins.io/kubernete
配置设置
建议：
配置系统设置

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​可以使用 [Helm](https://github.com/helm/helm)、[kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/) 或 GUIs 部署 Jenkins ，以便将新的 pods 部署到集群中。安装后，下一步是为 [K8s](https://plugins.jenkins.io/kubernete
设置 Jenkins-controlled 集群
-->
设置 Jenkins 控制的集群

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​获得 Jenkins 只是一个开始，下一步是在Jenkins本身内配置 CI / CD 流水线。 你可以先运行Minikube Service Jenkins ，然后使用其 Web UI 访问 Jenkins。
​获得 Jenkins 只是一个开始，下一步是在Jenkins本身内配置 CI / CD 流水线。
-->
让 Jenkins 启动只是一个开始，下一步是在 Jenkins 内配置 CI/CD 流水线。

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​获得 Jenkins 只是一个开始，下一步是在Jenkins本身内配置 CI / CD 流水线。 你可以先运行Minikube Service Jenkins ，然后使用其 Web UI 访问 Jenkins。
代码或命令行保留原文
Minikube Service Jenkins 
-->
`minikube service Jenkins`
前后加 "`"

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​另一个值得讨论的插件是 [Kubernetes Continuous Deploy 插件](https://plugins.jenkins.io/kubernetes-cd)，它专门为处理流水线的连续交付设计的。 该插件将处理为测试创建新的pods以及测试和部署之间的转换。
连续交付
-->
持续交付

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​另一个值得讨论的插件是 [Kubernetes Continuous Deploy 插件](https://plugins.jenkins.io/kubernetes-cd)，它专门为处理流水线的连续交付设计的。 该插件将处理为测试创建新的pods以及测试和部署之间的转换。
创建新的pods
英文前后空格

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​配置完所有插件后，重新启动 Jenkins。 Jenkins 提供的一个很好的功能能够自动执行这些手动更改，因此下次您配置 CI/CD 系统（例如，在基础结构迁移的情况下）时，不必再次通过手动更改。 您只需接收一个具有与以前相同配置和插件的实例。嵌入到 Jenkins Docker 映像和 Jenkins 配置文件 config.xml 中的脚本 install_plugins.sh 实现了这
Docker 映像
-->
Docker 镜像

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​在 Jenkins 用户界面上，有一个 build now 命令用于运行新的构建。构建完成后，下次使用 Minikube 运行应用程序时，您将看到所做的更改。 Jenkins 流水线的配置方式使该工具非常有用。
build now
-->
Build Now
或
立即构建

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​例如，您可以使用 Jenkins 来支持多团队开发。Jenkins流水线作为代码运行，这意味着具有正确凭据的任何用户都可以提交更改并执行流水线中内置的流程。
Jenkins流水线
中英文空格

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​另一个伟大的插件是[流水线](https://github.com/jenkinsci/pipeline-plugin)和[多分支流水线](https://plugins.jenkins.io/workflow-multibranch)，它帮助我们可视化 CI/CD 流。它允许在 repo 中定义一个 jenkins 文件，包括我们希望 jenkins 执行的所有步骤。不需要从GUI进行手动配
​另一个
-->
​另外的
（后面有两个插件）

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​另一个伟大的插件是[流水线](https://github.com/jenkinsci/pipeline-plugin)和[多分支流水线](https://plugins.jenkins.io/workflow-multibranch)，它帮助我们可视化 CI/CD 流。它允许在 repo 中定义一个 jenkins 文件，包括我们希望 jenkins 执行的所有步骤。不需要从GUI进行手动配
不需要从GUI进行
中英文空格

2019-07-22 11:37 UTC, donhui commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​让我们回到我们的主要观点：在 Kubernetes 上利用 Jenkins 。从 Jenkins 工具的工作方式来看，很容易看出这种自动化度量如何完美地补充了 Kubernetes 。一旦配置了插件，每次触发新的构建/任务， Jenkins 都会在 K8s 中创建一个 Pod （通过设计用于执行该工作的按需代理）。一旦完成， Pod 将被销毁，从而避免了有固定的代理池等待任务执行的需要。如您所
在 Kubernetes 上利用 Jenkins
-->
在 Kubernetes 上使用 Jenkins
上下文保持一致

2019-07-23 05:48 UTC, baobeizuoshoubuli commented on articles/2019/07/2019-07-29-leveraging-jenkins-on-kubernetes.md
> +​让我们回到我们的主要观点：在 Kubernetes 上利用 Jenkins 。从 Jenkins 工具的工作方式来看，很容易看出这种自动化度量如何完美地补充了 Kubernetes 。一旦配置了插件，每次触发新的构建/任务， Jenkins 都会在 K8s 中创建一个 Pod （通过设计用于执行该工作的按需代理）。一旦完成， Pod 将被销毁，从而避免了有固定的代理池等待任务执行的需要。如您所
ok thanks

2019-07-23 08:13 UTC, donhui approved these changes
lgtm

2019-07-23 08:17 UTC, baobeizuoshoubuli commented
> 
> 
> lgtm

？？？

2019-07-23 08:20 UTC, LinuxSuRen approved these changes
LGTM 是 look good to me 的缩写，GitHub 用语

2019-07-24 15:58 UTC, yJunS approved these changes

2019-07-29 10:49 UTC, merged

2019-07-29 11:03 UTC, LinuxSuRen commented
https://github.com/jenkins-infra/wechat/tree/master/management/contributors
你可以在这里添加你的署名备注

2019-07-29 11:06 UTC, baobeizuoshoubuli commented
好的！

------------------


__________________________________________________________________





 




------------------ 原始邮件 ------------------
发件人: "Zhao Xiaojie"<notifications@github.com>;
发送时间: 2019年7月29日(星期一) 晚上7:03
收件人: "jenkins-infra/wechat"<wechat@noreply.github.com>;
抄送: "王艳"<809122235@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jenkins-infra/wechat] [翻译-2019-07-29] 在 Kubernetes 上使用 Jenkins  (#188)




https://github.com/jenkins-infra/wechat/tree/master/management/contributors
 你可以在这里添加你的署名备注
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.