[活动]8.24开源人线下见面会
jenkins-infra/wechat pull request #192
Opened 2019-07-25 06:50 UTC by linan607

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-07-25 06:59 UTC, LinuxSuRen requested changes

2019-07-25 06:59 UTC, LinuxSuRen commented on articles/2019/07/2019-07-30-jenkins-meetup.md
> +| 16:00-16:30 | 尽情期待 |
这个也确定了，https://jenkins-zh.cn/event/beijing-2019-08-24/

2019-07-25 06:59 UTC, LinuxSuRen commented on articles/2019/07/2019-07-30-jenkins-meetup.md
> +毕业于北京工业大学，2003年加入 Sun Microsystems，负责嵌入式 Java 虚拟机的研发。曾于2008年创建了 PSP 上的JavaME 模拟器项目——PSPKVM，在 PSP 自制软件社区有很高的普及度。目前在北京卓晟互联网络技术有限公司任 CTO，创建并主持了 JOSH 开源项目，致力于为微小型物联网终端设备提供 Java 应用开发与运行环境。"
缺少平安云的讲师信息

2019-07-25 06:59 UTC, LinuxSuRen commented on articles/2019/07/2019-07-30-jenkins-meetup.md
> +![公众号封面首图](shou.png)
> 公众号封面首图

这个建议修改为`开源人线下见面会海报`

2019-07-25 07:16 UTC, linan607 commented on articles/2019/07/2019-07-30-jenkins-meetup.md
> +![公众号封面首图](shou.png)
已修正

2019-07-25 11:10 UTC, LinuxSuRen approved these changes

2019-07-26 13:48 UTC, donhui commented
有的逗号是英文逗号，统一改成中文的？

2019-07-29 01:05 UTC, linan607 commented
> 
> 
> 有的逗号是英文逗号，统一改成中文的？
已修正

2019-07-29 01:22 UTC, donhui approved these changes

2019-07-30 02:22 UTC, merged