[翻译-2019-08-14] 持续测试的那些事
jenkins-infra/wechat pull request #201
Opened 2019-08-04 15:37 UTC by tomatofrommars

[翻译-2019-08-14] 持续测试的那些事

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://dzone.com/articles/continuous-testing-what-why-and-how)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-08-05 02:02 UTC, LinuxSuRen commented
如果希望有自己的署名的话，请按照[这里的说明](https://github.com/jenkins-infra/wechat/blob/master/management/contributors/README.md)添加。

2019-08-05 04:30 UTC, tomatofrommars commented
> 如果希望有自己的署名的话，请按照[这里的说明](https://github.com/jenkins-infra/wechat/blob/master/management/contributors/README.md)添加。

GitHub ID 就行😋

2019-08-05 05:45 UTC, LinuxSuRen commented
建议使用你的GitHub 绑定的邮箱来提交

2019-08-05 07:40 UTC, tomatofrommars commented
> 建议使用你的GitHub 绑定的邮箱来提交

👌

2019-08-05 07:50 UTC, donhui commented on articles/2019/08/2019-08-14-continuous-testing-what-why-and-how.md
> +date: 2019-08-04
2019-08-04
这里的日期，包括图片日期需要调整下，和要发布的日期保持一致

2019-08-05 08:03 UTC, tomatofrommars commented on articles/2019/08/2019-08-14-continuous-testing-what-why-and-how.md
> +date: 2019-08-04
Done.

2019-08-06 15:18 UTC, LinuxSuRen requested changes
有一些格式上的小问题

2019-08-06 15:18 UTC, LinuxSuRen commented on articles/2019/08/2019-08-14-continuous-testing-what-why-and-how.md
> +![图片](./2019-08-14-continuous-testing-what-why-and-how/1440x950_canvas_test_automation.jpg)
这里不需要有目录

`![test_automation](1440x950_canvas_test_automation.jpg)`

2019-08-06 15:18 UTC, LinuxSuRen commented on articles/2019/08/2019-08-14-continuous-testing-what-why-and-how.md
> +![图片](./2019-08-14-continuous-testing-what-why-and-how/continuous-testing-main-hold-ups.png)
尽量避免使用无意义的图片描述，这个会最终影响搜索引擎

2019-08-06 15:18 UTC, LinuxSuRen commented on articles/2019/08/2019-08-14-continuous-testing-what-why-and-how.md
> +![图片](./2019-08-14-continuous-testing-what-why-and-how/continuous-testing-main-hold-ups.png)
另外，参考下其他文章的图片路径

2019-08-06 15:18 UTC, LinuxSuRen commented on articles/2019/08/2019-08-14-continuous-testing-what-why-and-how.md
> +![图片](./2019-08-14-continuous-testing-what-why-and-how/testing-embedded-throughout-sdlc.png)
同上

2019-08-06 16:05 UTC, tomatofrommars commented on articles/2019/08/2019-08-14-continuous-testing-what-why-and-how.md
> +![图片](./2019-08-14-continuous-testing-what-why-and-how/testing-embedded-throughout-sdlc.png)
好的

2019-08-07 02:17 UTC, LinuxSuRen approved these changes
LGTM

非常赞👍的一篇文章

2019-08-07 02:55 UTC, donhui approved these changes

2019-08-07 03:43 UTC, yJunS approved these changes
LGTM

2019-08-14 05:46 UTC, merged