[原创-2019-08-12]黑客松活动导师招募
jenkins-infra/wechat pull request #207
Opened 2019-08-07 06:37 UTC by linan607

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-08-07 09:59 UTC, donhui commented on articles/2019/08/2019-08-12-tutor-recruitment.md
> +**如果你拥有**
如果你拥有
-->
如果你在
？
这样和下面念起来通顺

2019-08-07 09:59 UTC, donhui commented on articles/2019/08/2019-08-12-tutor-recruitment.md
> +### 导师义务相关
导师义务相关
-->
导师相关义务
?

2019-08-07 09:59 UTC, donhui commented on articles/2019/08/2019-08-12-tutor-recruitment.md
> +* Jenkins pipeline 应用实践
pipeline 首字母大写？

2019-08-12 02:12 UTC, LinuxSuRen commented on articles/2019/08/2019-08-12-tutor-recruitment.md
> +* Docker 、 K8S 等先进工具最佳实践案例
英文之间是否用英文的标点符号会好一些呢

2019-08-12 12:11 UTC, Shunw19 commented on articles/2019/08/2019-08-12-tutor-recruitment.md
> +* Docker 、 K8S 等先进工具最佳实践案例
为你的团队招揽精英

2019-08-13 08:22 UTC, linan607 commented on articles/2019/08/2019-08-12-tutor-recruitment.md
> +### 导师义务相关
已修正

2019-08-13 08:23 UTC, linan607 commented on articles/2019/08/2019-08-12-tutor-recruitment.md
> +### 导师义务相关
请帮忙在看看导师相关义务内容还需增加啥吗？

2019-08-13 08:28 UTC, LinuxSuRen requested changes
多了一个文件

2019-08-13 08:39 UTC, yJunS reviewed
你是直接改的文件名。而不是git mv a b

2019-08-13 08:39 UTC, yJunS commented on articles/2019/08/2019-08-12-tutor-recruitment.md
> +- CI/CD、敏捷等 DevOps
> CI/CD、敏捷等 DevOps
放到
CI/CD、敏捷等 DevOps 相关领域拥有丰富的经验、独到的见解及建树
会不会好一些？

2019-08-13 10:37 UTC, LinuxSuRen approved these changes

2019-08-13 12:36 UTC, yJunS approved these changes
LGTM

2019-08-14 02:10 UTC, LinuxSuRen commented on articles/2019/08/2019-08-16-tutor-recruitment.md
> +toc: false
这里为啥是 `false` 呢

2019-08-16 00:01 UTC, merged