[维护]增加黑客松关键字
jenkins-infra/wechat pull request #209
Opened 2019-08-13 08:55 UTC by linan607

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-08-13 10:35 UTC, LinuxSuRen requested changes
需要使用新的活动的描述。

2019-08-13 10:35 UTC, LinuxSuRen commented on management/auto-reply/keywords-hackthon.yml
> +        Jenkins 中文社区计划于2019年10月25日发起一场以 DevOps 为主题的开源黑客松编程比赛，
> 发起

现在已经是“举办”了

2019-08-13 10:36 UTC, LinuxSuRen commented
注意下，PR 模板中的检查列表是需要检查后并勾选的。

2019-08-14 05:45 UTC, LinuxSuRen requested changes

2019-08-14 05:45 UTC, LinuxSuRen commented on management/auto-reply/keywords-hackthon.yml
>          该活动旨在为当下金融、能源、政务、交通等场景面临的 IT 挑战提出解决方案，
> 该活动旨在为当下金融、能源、政务、交通等场景面临的 IT 挑战提出解决方案，我们希望本次赛事期间您也能够收获业内同行间最有价值的碰撞成果。

这句话不要了，和其他的活动有冲突。

2019-08-14 09:14 UTC, yJunS requested changes

2019-08-14 09:14 UTC, yJunS commented on management/auto-reply/keywords-hackthon.yml
> +        如果你的团队或项目涉及 CI/CD 以及 DevOps ，我们诚邀你参加由Jenkins 中文社区发起的
> 由Jenkins
->
由 Jenkins

2019-08-15 02:41 UTC, LinuxSuRen approved these changes

2019-08-15 02:41 UTC, merged