提名 Jenkins 中文社区激励候选人
jenkins-infra/wechat pull request #212
Opened 2019-08-16 01:56 UTC by LinuxSuRen

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [x] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-08-16 11:46 UTC, yJunS requested changes

2019-08-16 11:46 UTC, yJunS commented on articles/2019/08/2019-08-17-award.md
> +Hold on!!没有赶上第一期活动的同学们，请往这里看——第二期激励投票活动马上开始 了，在这个炎热的夏天，让我们一起行动起来吧!
> 请往这里看——第二期激励投票活动马上开始 了
这句是不是多处一个空格？

2019-08-16 11:46 UTC, yJunS commented on articles/2019/08/2019-08-17-award.md
> +评选规则: 社区秉承公平，公正，公开的原则，希望每位社区贡献者都有机会参与评选，本次活动将采 取邮件征集投票的形式，选出本期最佳社区贡献者
> 本次活动将采 取邮件征集投票的形式
形式 -> 方式 是不是好一些？
也是多一个空格？
===========================
> 选出本期最佳社区贡献者
最佳会不会特指一名？  
最佳 -> 突出
会不会好一些？

2019-08-16 11:46 UTC, yJunS commented on articles/2019/08/2019-08-17-award.md
> +- 在 Jenkins 中文社区有开源贡献(eg:提交新的特性代码，提交补丁优化代码，撰写和改进项 目的文档 etc.)
> 撰写和改进项 目的文档
还是空格的问题

2019-08-16 11:46 UTC, yJunS commented on articles/2019/08/2019-08-17-award.md
> +- 加入 Jenkins 社区贡献者名单，并展现在 Jenkins 中文社区官网 https://jenkins-zh.cn/ -获得由与社区合作的“人民邮电出版社”提供的技术书籍
> Jenkins 中文社区官网 https://jenkins-zh.cn/
->
[Jenkins 中文社区](https://jenkins-zh.cn)官网
==================================
> “人民邮电出版社”
-> 
*人民邮电出版社*

2019-08-16 11:46 UTC, yJunS commented on articles/2019/08/2019-08-17-award.md
> +评选结果将在“Jenkins 中文社区官方微信公众号”进行公布 -合作的出版社将直接邮寄奖品。
“Jenkins 中文社区官方微信公众号”
->
*Jenkins 官方微信公众号*
这块是不是改为这个合适一些？

2019-08-16 11:46 UTC, yJunS commented on articles/2019/08/2019-08-17-award.md
> +激励让社区活动更加有趣，让我们一起构建伟大，无所不能。还不快快行动，让更多的人因 为你的贡献打开通往新世界的大门!
让更多的人因 为你的贡献打开通往新世界的大门
多余空格

2019-08-17 05:11 UTC, donhui commented
除了彦军指出的空格问题，还有好几处空格问题，可以从头开始看看

2019-08-17 05:17 UTC, LinuxSuRen commented
这个是志愿者小伙伴写的，是否可以考虑适当地兼容一些小问题呢。

2019-08-17 10:08 UTC, yJunS requested changes

2019-08-17 10:08 UTC, yJunS commented on articles/2019/08/2019-08-17-award.md
> +评选规则: 社区秉承公平，公正，公开的原则，希望每位社区贡献者都有机会参与评选，本次活动将采取邮件征集投票的方式，选出本期社区突出贡献者
> 社区秉承公平，公正，公开的原则
->
社区秉承公平、公正、公开的原则

2019-08-17 10:08 UTC, yJunS commented on articles/2019/08/2019-08-17-award.md
> +- 邮件投票截止时间2019年8月28日23点59分——我们会在社区的例会上对从邮件中征集的候选人进行公开投票，最终选出五位最佳贡献者给予奖励（从直接参与社区贡献的人中挑选四位，从社区技术群积极帮助他人的人中挑选一位）
截止时间点要不要标记一下
`2019年8月28日23点59分`

2019-08-17 10:27 UTC, donhui commented on articles/2019/08/2019-08-17-award.md
> +- 邮件投票截止时间2019年8月28日23点59分——我们会在社区的例会上对从邮件中征集的候选人进行公开投票，最终选出五位最佳贡献者给予奖励（从直接参与社区贡献的人中挑选四位，从社区技术群积极帮助他人的人中挑选一位）
也可以

2019-08-17 12:32 UTC, merged