[原创-2019-08-30] 庆祝开源人线下见面会圆满结束
jenkins-infra/wechat pull request #218
Opened 2019-08-27 17:21 UTC by yJunS

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-08-27 21:46 UTC, LinuxSuRen commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +最后，衷心庆祝本次`开源人线下见面会`圆满结束
后面是否加个句号呢。？

2019-08-27 21:46 UTC, LinuxSuRen commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +在此，非常感谢`京东云`、`平安云 GitHub`、`翊翎资本`提供对[Jenkins 中文社区](https://jenkins-zh.cn)的大力赞助，同时也感谢`开源社`与我们一起举办此次活动
句号？

2019-08-27 21:53 UTC, LinuxSuRen requested changes
有几个地方需要调整一下

- 图片的描述都要有意义，文件名也最好不是一个数字序列

- 图片不能太大了，建议200k左右，原始图片可以放另外一个地方

- 封面图片和本文几乎没有什么关系，是否可以把合影作为封面图片，或者其他更有相关性的图片呢

2019-08-27 21:53 UTC, LinuxSuRen commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +![551566921548_.pic_hd](551566921548_.pic_hd.jpg)
> `![551566921548_.pic_hd](551566921548_.pic_hd.jpg)`

建议加上描述，方便搜索引擎的记录 `![复盘环节](551566921548_.pic_hd.jpg)`

2019-08-27 21:53 UTC, LinuxSuRen commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +**慕睿涛** 北京卓晟互联网络技术有限公司 CTO
落了一个人 https://jenkins-zh.cn/event/beijing-2019-08-24/

2019-08-27 21:53 UTC, LinuxSuRen commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +于2019年8月24日（周六）下午2点举办的开源人线下见面会圆满结束啦。本次活动是由[Jenkins 中文社区](https://jenkins-zh.cn)与[开源社](https://kaiyuanshe.cn)联合主办的一次以`社区`、`开源`为主题的活动。
> 联合主办

首次联合主办

2019-08-28 02:26 UTC, LinuxSuRen approved these changes

2019-08-28 02:27 UTC, LinuxSuRen commented
活动地址 https://jenkins-zh.cn/event/beijing-2019-08-24/

2019-08-28 05:46 UTC, LinuxSuRen approved these changes

2019-08-30 08:22 UTC, merged

2019-08-30 14:04 UTC, donhui commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +* **幕锐涛**为我们讲解了他从 Sun 公司的一些精力，以及跟开源开始结缘的一些事宜。从`自由软件运动回顾`、`自由的代价`、`开放标准与开源代码`、`Android 与 Java 的纷争`、`Android 与 Linux 社区的分歧`几个方面回顾与分析了开源与开放的本质区别。
精力
-->
经历

2019-08-30 14:10 UTC, LinuxSuRen commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +* **幕锐涛**为我们讲解了他从 Sun 公司的一些精力，以及跟开源开始结缘的一些事宜。从`自由软件运动回顾`、`自由的代价`、`开放标准与开源代码`、`Android 与 Java 的纷争`、`Android 与 Linux 社区的分歧`几个方面回顾与分析了开源与开放的本质区别。
See also https://github.com/jenkins-infra/wechat/pull/220