[维护] 修改错别字“精力”为“经历”
jenkins-infra/wechat pull request #220
Opened 2019-08-30 14:10 UTC by LinuxSuRen

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-08-30 14:12 UTC, donhui approved these changes

2019-08-30 14:13 UTC, donhui commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +* **幕锐涛**为我们讲解了他从 Sun 公司的一些经历，以及跟开源开始结缘的一些事宜。从`自由软件运动回顾`、`自由的代价`、`开放标准与开源代码`、`Android 与 Java 的纷争`、`Android 与 Linux 社区的分歧`几个方面回顾与分析了开源与开放的本质区别。
从
这个是不是应该换成 在？

2019-08-31 13:52 UTC, yJunS requested changes
经历和这块都在发微信文章都时候有提示，睿字是刚刚看到，也更改了

2019-08-31 13:52 UTC, yJunS commented on articles/2019/08/2019-08-30-open-source-meeting.md
> +* **幕锐涛**为我们讲解了他在 Sun 公司的一些经历，以及跟开源开始结缘的一些事宜。从`自由软件运动回顾`、`自由的代价`、`开放标准与开源代码`、`Android 与 Java 的纷争`、`Android 与 Linux 社区的分歧`几个方面回顾与分析了开源与开放的本质区别。
> 幕锐涛
->
慕睿涛

2019-08-31 14:24 UTC, yJunS approved these changes
LGTM

2019-09-01 06:41 UTC, merged