[原创-活动-2019-09-10] Add an online activity
jenkins-infra/wechat pull request #223
Opened 2019-09-07 02:50 UTC by LinuxSuRen

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-09-07 02:50 UTC, LinuxSuRen commented
还缺少海报+报名方法

2019-09-09 14:04 UTC, yJunS commented on articles/2019/09/2019-09-10-online-activity.md
> +description: "各种技术群里交流不过瘾？来 zoom 呀！"
> 来 zoom 呀

这块“来 zoom” 是不是有点不太好？  下文体现zoom了。在这块凸显主题是不是会更好一些？

2019-09-10 01:57 UTC, LinuxSuRen commented on articles/2019/09/2019-09-10-online-activity.md
> +description: "各种技术群里交流不过瘾？来 zoom 呀！"
标题里不是已经有主题里吗。有没有好的表述建议呢。

2019-09-10 02:11 UTC, donhui commented on articles/2019/09/2019-09-10-online-activity.md
> +值得您注意的是，任何人都可以在下次活动发布之前，申请作为分享人。您通过如下的几种方式进行申请：
您通过如下的几种方式进行申请
-->
您可以通过如下的几种方式进行申请

2019-09-10 13:58 UTC, yJunS commented on articles/2019/09/2019-09-10-online-activity.md
> +description: "各种技术群里交流不过瘾？来 zoom 呀！"
线上技术交流会期待你的参与
这样会不会好一些？

2019-09-11 06:57 UTC, donhui approved these changes
lgtm

2019-09-12 18:40 UTC, yJunS approved these changes
LGTM

2019-09-27 01:11 UTC, LinuxSuRen commented
活动没有搞起来。。。。

2019-10-20 03:36 UTC, LinuxSuRen commented on management/auto-reply/keywords-welcome.yml
> +        支持的关键字回复：技术群、活动、视频、教程、转载、投诉、帮助
如果是`微信群`的话，不明确这个群的作用，`技术群`会更加明确。

2019-10-20 03:37 UTC, LinuxSuRen commented on management/auto-reply/keywords-welcome.yml
> +        支持的关键字回复：技术群、活动、视频、教程、转载、投诉、帮助
很多人对活动也比较关注，可以加这个关键字

2019-10-20 04:52 UTC, hummerstudio commented
好像没写关于提问的内容？我看技术群内很多人的问题都比较具体，是不是让他们准备一下好远程演示。没有准备临时发问可能说不清具体问题。

2019-10-20 04:58 UTC, LinuxSuRen commented
> 好像没写关于提问的内容？我看技术群内很多人的问题都比较具体，是不是让他们准备一下好远程演示。没有准备临时发问可能说不清具体问题。

是的，确实会有这样的问题。我们的活动不是收费的，也无法保证一定能解答，更多的像是交流。可以给一些建议，例如：

- 提前准备好想要交流的问题
- 涉及到涉及操作的，自行准备好相应的环境

加这样的描述，你觉得如何？

2019-10-20 05:08 UTC, hummerstudio commented
> * 涉及操作的，自行准备好相应的环境

 再加一个怎么样：环境在内网的，提前将脱敏后的关键配置/代码以及报错信息截图

2019-10-20 05:15 UTC, yJunS requested changes
建议将[参会方式](https://jenkins-zh.github.io/meeting/)链接进来

2019-10-20 12:24 UTC, LinuxSuRen commented
> 建议将[参会方式](https://jenkins-zh.github.io/meeting/)链接进来

是遗漏了这部分，不过，我觉得可以把 https://jenkins-zh.github.io/event/ 这个地址贴出来。这个是在线活动，不是会议。

2019-10-20 12:41 UTC, merged