[blog translation-09-15]: Jenkins World Contributor Summit and Ask the Experts booth
jenkins-infra/wechat pull request #224
Opened 2019-09-08 13:46 UTC by Shunw19

- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2019/08/25/jenkinsworld-contrib-summit-ask-the-expert-booth/)
- [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-09-08 13:52 UTC, LinuxSuRen requested changes
非常给力，作为一个非 IT 从业人员能搞定 GitHub，点若干个赞👍。
有一些格式上的问题需要做调整，请参考下面的格式约定：

https://github.com/jenkins-infra/wechat/tree/master/articles  
https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md

2019-09-08 13:52 UTC, LinuxSuRen commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +date: 2019-08-25
这里是期望发布的日期，考虑到 review 的周期，一般是在你提交 PR 后的一周左右比较合适。

2019-09-08 13:52 UTC, LinuxSuRen commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +
多余的空格

2019-09-08 13:52 UTC, LinuxSuRen commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +# 第一天
题目为一级标题（也就是个 `#`），因此，其他的应该是从二级标题开始

2019-09-08 13:58 UTC, Shunw19 commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +date: 2019-08-25
搜噶！我以为是原文发布的日期 囧

2019-09-08 14:02 UTC, Shunw19 commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +
你说的是空格多余？我是要在visual studio code上做修改，还是在这个就能直接修改？

2019-09-08 14:02 UTC, LinuxSuRen commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +
哪里都可以

2019-09-08 14:05 UTC, Shunw19 commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +date: 2019-08-25
此处感谢@yJunS远程指导！

2019-09-08 14:05 UTC, LinuxSuRen commented
great teacher and great student +1

> On Sep 8, 2019, at 22:05, shunw <notifications@github.com> wrote:
> 
> 此处感谢@yJunS <https://github.com/yJunS>远程指导！

2019-09-09 14:00 UTC, yJunS requested changes

2019-09-09 14:00 UTC, yJunS commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +Jenkins 15周岁啦！Jenkins World 将 DevOps 思想领袖、IT 主管、持续交付实践者以及 Jenkins 社区和生态系统齐聚这场全球活动，让与会者有机会学习、探索以及面对面交流，帮助塑造 Jenkins 的下一次发展以及针对DevOps的解决方案.
> 针对DevOps的解决方案
->
针对 DevOps 的解决方案

2019-09-09 14:00 UTC, yJunS commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +讨论会结尾是博思艾伦咨询公司（Booz Allen Hamilton）的 Steven Terrana 的展示和精彩的 Jenkins 模板引擎。如果你还没有试过这个，请一定不要错过 (https://github.com/boozallen/jenkins-templating-engine)。
> (https://github.com/boozallen/jenkins-templating-engine)
这块应该是
[https://github.com/boozallen/jenkins-templating-engine](https://github.com/boozallen/jenkins-templating-engine)
![image](https://user-images.githubusercontent.com/20575981/64536871-6b23e300-d34c-11e9-861e-44b0a35c390c.png)

2019-09-09 14:00 UTC, yJunS commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +这真的是一场非常有意思的体验，让我有机会了解社区正在做什么，帮助他们解决面对的问题。问题涉及的范围很广，从 Jenkins X 到我负责维护的种种插件，如 Jenkins Prometheus 和  Sysdig Secure 扫描插件。也有很多关于 Kubernetes 的问题。有很多关于 Kubernetes 使用情况提高的市场营销方面的数据，但对 Kubernetes 上 Jenkins
> Sysdig Secure 扫描插件
是不是把插件全名写出来会好一些？
Sysdig Secure Scanning 插件

2019-09-09 14:00 UTC, yJunS commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +最后压轴的就是我了。我展示了正在维护的Sysdig Secure 扫描 Jenkins 插件。感谢每一位当场的朋友。
Sysdig Secure 扫描 Jenkins
同上

2019-09-09 14:00 UTC, yJunS commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +就在午餐demo之后，我顺道去看了下 Jenkins 开放区。这对社区而言，是讨论议题、自主活动的机会。我真的非常享受这次讨论会，觉得该形式在与会人员中的接受程度很好。
> 午餐demo之后

->
午餐 demo 之后

2019-09-09 14:00 UTC, yJunS commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +这是一场无与伦比的非凡体验。非常感谢 CloudBees、Jenkins 社区、GSoC、Tracy Miranda、Alyssa Tong和我的公司 Sysdig。
> Alyssa Tong和我的公司

->
Alyssa Tong 和我的公司

2019-09-11 03:04 UTC, donhui commented on articles/2019/09/2019-09-15-Jenkins World Contributor Summit and Ask the Expert booth.md
> +Jenkins 15周岁啦！Jenkins World 将 DevOps 思想领袖、IT 主管、持续交付实践者以及 Jenkins 社区和生态系统齐聚这场全球活动，让与会者有机会学习、探索以及面对面交流，帮助塑造 Jenkins 的下一次发展以及针对 DevOps 的解决方案.
针对 DevOps 的解决方案.
-->
针对 DevOps 的解决方案。

句号改成中文的

2019-09-11 06:53 UTC, LinuxSuRen requested changes
建议把日期修改为16号，避开中秋节日。

2019-09-11 11:23 UTC, LinuxSuRen commented
图片所在的目录好像么有修改过来

2019-09-14 15:37 UTC, yJunS approved these changes
LGTM

2019-09-16 00:42 UTC, merged