add file 2019-09-09-devops-world-jenkins-world.md
jenkins-infra/wechat pull request #227
Opened 2019-09-10 02:56 UTC by H5ang

[类型-文章排期] 标题

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [*] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[https://devops.com/2019-devops-world-jenkins-world-award-winners-announced/](https://jenkins-zh.cn/)
    - [*] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-09-10 02:59 UTC, LinuxSuRen commented
尽量避免关闭了 PR 重新提交，在原有的基础上修改就好了

2019-09-10 14:07 UTC, yJunS reviewed
日期已经过了的话。建议把日期以及文件名等都做相应更改。有问题可以及时在群里问就好

2019-09-10 14:15 UTC, yJunS commented
GitHub 的 PR 的内容也上 Markdown 的，这块你可以看一下,你应该编辑过，应该是在提交后，再打勾的
![image](https://user-images.githubusercontent.com/20575981/64621188-d25a9980-d417-11e9-95f3-c8420eb64ec8.png)

2019-09-11 06:51 UTC, LinuxSuRen requested changes
建议把日期修改为9月23号

2019-09-15 01:18 UTC, yJunS requested changes
在pr模板中，原文的地址只是显示成原文地址，实际链接并不正确

2019-09-15 01:18 UTC, yJunS commented on articles/2019/09/2019-09-09-devops-world-jenkins-world.md
> +author: huang
翻译的话，author应该不是你自己。translator才是

2019-09-15 01:18 UTC, yJunS commented on articles/2019/09/2019-09-09-devops-world-jenkins-world.md
> +> 15个组织和个人荣获DevOps杰出成就，开源贡献和渠道合作伙伴绩效
> 个人荣获DevOps杰出成就，开源贡献和渠道合作伙伴绩效

->
个人荣获 DevOps 杰出成就、开源贡献和渠道合作伙伴绩效

2019-09-15 01:18 UTC, yJunS commented on articles/2019/09/2019-09-09-devops-world-jenkins-world.md
> +**DEVOPS WORLD | JENKINS WORLD，2019年8月15日在旧金山，由CloudBees**，企业DevOps领导者推动经济持续发展，今天宣布了2019 DevOps world 和 Jenkins world 获奖者。该奖项表彰3个类别的成就：Jenkins社区奖，表彰对Jenkins项目做出重大贡献的人；CloudBees创新将，表彰在DevOps转型中取得优秀成果的
中英文之间空格

2019-09-15 01:18 UTC, yJunS commented on articles/2019/09/2019-09-09-devops-world-jenkins-world.md
> +CloudBees创新将的获得者包括各种规模的组织，从风险投资的小型创业公司到全球技术巨头。Jenkins社区将授予了4个人，他们为Jenkins社区做出了贡献。最后5个渠道合作伙伴因在勤奋卓越获得认可。
中英文间空格

2019-09-15 01:18 UTC, yJunS commented on articles/2019/09/2019-09-09-devops-world-jenkins-world.md
> +###**JENKINS社区奖**
中英文间空格

2019-09-15 01:18 UTC, yJunS commented on articles/2019/09/2019-09-09-devops-world-jenkins-world.md
> +Jenkins社区奖由Jenkins创始人兼CloudBees首席科学家Kohsuke Kawaguchi和Jenkins大使组成的小组选出。Jenkins大使每年都会被提名，他们都是有影响力的Jenkins爱好者，热衷于与他人分享Jenkins的技术专长。
中英文间空格

2019-09-15 01:18 UTC, yJunS commented on articles/2019/09/2019-09-09-devops-world-jenkins-world.md
> +“2019 Jenkins社区奖表彰了社区成员的努力，他们在几个关键领域为推进Jenkins做出了重大贡献“，Kawaguchi表示，”今年的提交的质量比以往任何时候都要好。”
中英文间空格

2019-09-15 01:18 UTC, yJunS commented on articles/2019/09/2019-09-09-devops-world-jenkins-world.md
> +* 2019最有价值的Jenkins贡献者 - Oliver Gondža
文章中有多处中英文规范的问题，请仔细检查

2019-09-23 06:00 UTC, LinuxSuRen approved these changes
当前 PR 的作者长期没有响应，已经到了要发文的时间了，我只能修改后发布了。

2019-09-23 06:00 UTC, merged