pull
jenkins-infra/wechat pull request #229
Opened 2019-09-16 16:11 UTC by eryajf

[类型-文章排期] 标题

<-- Comment:
请仔细阅读这里的描述，我们只会 Review 符合描述的 PR

1. Comment 区域属于注释部分，阅读完后请删除
2. 带星号（*）的区域是必选项
3. 如果您提交的 PR 超过三天没有收到 Review，可以 ping 最近合并了 PR 的人
4. 翻译需要增加对应的原文地址
5. 只有维护类的 PR 不需要标题中增加排期，排期的日期格式为：01-10。如果有特殊情况，排期可能需要进行调整
-->

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-09-17 00:02 UTC, LinuxSuRen requested changes
非常欢迎您的贡献，请按照我们的规范进行调整。

2019-09-18 02:00 UTC, yJunS reviewed
PR标题和文章内的都需要按照规范来提交的

2019-09-18 03:24 UTC, eryajf commented
可能是我理解错了，我的本意是想从官方库，往自己fork的地址pull同步一下，看来对这个流程还是不够熟悉

2019-09-18 03:24 UTC, closed without merging

2019-09-18 03:27 UTC, LinuxSuRen commented
建议先自己创建一些仓库测试、熟悉下流程，谢谢配合。