翻译-Alpha 版本的插件管理库和 CLI 工具
jenkins-infra/wechat pull request #236
Opened 2019-10-15 17:49 UTC by zhaoying818

[类型-文章排期] 标题

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2019/07/02/plugin-management-tool-alpha-release/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [x] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [x] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-10-16 12:29 UTC, LinuxSuRen requested changes

2019-10-16 12:29 UTC, LinuxSuRen commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +- pluginstxt.png
`poster` 是海报封面的意思，只能有一个，不是数组。

2019-10-16 12:29 UTC, LinuxSuRen commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +## GSoC 1 期更新
`phase` 翻译为阶段更合适点

2019-10-16 12:29 UTC, LinuxSuRen commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +当我考虑将[插件管理器](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/PluginManager.java)从 Jenkins 核心中撤出时，由于依赖项的复杂性和数量，这最终成为了最具挑战性的第一步。相反，我们决定首先将 Jenkins Docker 中的 [install-plugins.
`撤出`  移出？

2019-10-16 12:29 UTC, LinuxSuRen commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +欢迎通过[插件安装管理器 CLI 工具 Gitter 聊天](https://gitter.im/jenkinsci/plugin-installation-manager-cli-tool)或 [Jenkins 开发者邮件列表](mailto:jenkinsci-dev@googlegroups.com)与我们联系。我希望收到您的问题，评论和反馈！我们在世界标准时间下午6点（星期二和星期四）开
`Gitter 聊天` 
`Gitter 聊天室`?

2019-10-16 15:32 UTC, zhaoying818 commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +当我考虑将[插件管理器](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/PluginManager.java)从 Jenkins 核心中撤出时，由于依赖项的复杂性和数量，这最终成为了最具挑战性的第一步。相反，我们决定首先将 Jenkins Docker 中的 [install-plugins.
```suggestion
当我考虑将[插件管理器](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/PluginManager.java)从 Jenkins 核心中移出时，由于依赖项的复杂性和数量，这最终成为了最具挑战性的第一步。相反，我们决定首先将 Jenkins Docker 中的 [install-plugins.sh bash 脚本](https://github.com/jenkinsci/docker/blob/master/install-plugins.sh)转换为 Java。 install-plugins.sh 脚本存在多个问题，即它是 bash 脚本并且扩展性有限，此外，它不会检索所有最新的更新中心的元数据。
```

2019-10-16 15:39 UTC, zhaoying818 commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +欢迎通过[插件安装管理器 CLI 工具 Gitter 聊天](https://gitter.im/jenkinsci/plugin-installation-manager-cli-tool)或 [Jenkins 开发者邮件列表](mailto:jenkinsci-dev@googlegroups.com)与我们联系。我希望收到您的问题，评论和反馈！我们在世界标准时间下午6点（星期二和星期四）开
```suggestion
欢迎通过[插件安装管理器 CLI 工具 Gitter 聊天室](https://gitter.im/jenkinsci/plugin-installation-manager-cli-tool)或 [Jenkins 开发者邮件列表](mailto:jenkinsci-dev@googlegroups.com)与我们联系。我希望收到您的问题，评论和反馈！我们在世界标准时间下午6点（星期二和星期四）开会。
```

2019-10-16 15:41 UTC, zhaoying818 commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +## GSoC 1 期更新
```suggestion
## GSoC 阶段 1 更新
```

2019-10-16 16:02 UTC, zhaoying818 commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +- pluginstxt.png
封面图片已经修改 为devopsworld.jpg

2019-10-16 16:07 UTC, zhaoying818 commented
所提建议已经修改完毕！
thx！

2019-10-17 00:18 UTC, LinuxSuRen approved these changes

2019-10-17 00:18 UTC, LinuxSuRen commented
这篇博客来自于 `jenkins.io`，因此，还需要向 https://github.com/jenkins-infra/cn.jenkins.io 提交一份。

2019-10-17 00:18 UTC, LinuxSuRen commented
如果你想要有自己的署名的话，需要在这里提交对应的信息。
https://github.com/jenkins-infra/wechat/tree/master/management/contributors

2019-10-17 01:56 UTC, zhaoying818 commented
1）cn.jenkins.io 已经发起 PR https://github.com/jenkins-infra/cn.jenkins.io/pull/245
2）已经添加署名文件

2019-10-17 01:58 UTC, LinuxSuRen commented on management/contributors/zhaoying818.yml
> +nickname: zhaoying818
`nickname` 会直接显示在微信公众号上，你确定是用这个吗？

2019-10-17 02:29 UTC, zhaoying818 commented on management/contributors/zhaoying818.yml
> +nickname: zhaoying818
我还是改成自己真名吧

2019-10-17 02:30 UTC, zhaoying818 commented on management/contributors/zhaoying818.yml
> +nickname: zhaoying818
```suggestion
nickname: 赵营
```

2019-10-17 02:30 UTC, LinuxSuRen commented on management/contributors/zhaoying818.yml
> +nickname: zhaoying818
怎么都行，看你自己的期望了

2019-10-17 02:34 UTC, zhaoying818 commented on management/contributors/zhaoying818.yml
> +nickname: 赵营
```suggestion
nickname: 赵小小影
```

2019-10-17 02:37 UTC, zhaoying818 commented on management/contributors/zhaoying818.yml
> +nickname: 赵营
好难抉择啊，就用自己的 微信昵称了。
就这么定了！

2019-10-17 02:38 UTC, zhaoying818 commented on management/contributors/zhaoying818.yml
> +nickname: zhaoying818
O(∩_∩)O~
改成微信昵称了！

2019-10-17 03:30 UTC, donhui commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +date: 2019-07-02
这里日期也改下，改成计划发布日期

2019-10-17 04:07 UTC, zhaoying818 commented on articles/2019/07/2019-07-02-plugin-management-tool-alpha-release.md
> +date: 2019-07-02
```suggestion
date: 2019-10-25
```

2019-10-17 04:14 UTC, yJunS requested changes
建议将文件名和文件夹路径都按照实际日期来修改

2019-10-17 05:18 UTC, LinuxSuRen submitted a review, later dismissed
漏了时间了，日期都应该是发布的日期。

2019-10-17 09:18 UTC, zhaoying818 commented
也就是说 2019-07-02-plugin-management-tool-alpha-release 都需要修改为
2019-10-25-plugin-management-tool-alpha-release.md

@LinuxSuRen @yJunS

2019-10-17 11:11 UTC, yJunS commented
是的，图片的相关文件夹也要变更

On Thu, Oct 17, 2019 at 5:18 PM zhaoying <notifications@github.com> wrote:

> 也就是说 2019-07-02-plugin-management-tool-alpha-release 都需要修改为
> 2019-10-25-plugin-management-tool-alpha-release.md
>
> @LinuxSuRen <https://github.com/LinuxSuRen> @yJunS
> <https://github.com/yJunS>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkins-infra/wechat/pull/236?email_source=notifications&email_token=AE47N3JXQJBXWDHSDNTRFNDQPAUX5A5CNFSM4JA75YD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBPNLZI#issuecomment-543086053>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE47N3JMOAIUDEM5CHD2ZILQPAUX5ANCNFSM4JA75YDQ>
> .
>

2019-10-17 11:40 UTC, LinuxSuRen commented
@zhaoying818 这里的日期是文章要发布的日期，而不是原文编写的日期。例如：你翻译的18年的，这里写成18年就不合适。

2019-10-17 17:04 UTC, zhaoying818 commented
已经将原目录移动到 articles/2019/10下面
目录名2019-10-25-plugin-management-tool-alpha-release
文件名2019-10-25-plugin-management-tool-alpha-release.md

2019-10-18 01:42 UTC, yJunS requested changes
建议把封面图片在正文中也放出来，参考[文章](https://github.com/jenkins-infra/wechat/pull/237/files#diff-faca71c28ab8e4fb847972bf62a89b1aR11)

2019-10-18 02:16 UTC, zhaoying818 commented on articles/2019/10/2019-10-25-plugin-management-tool-alpha-release.md
> +
```suggestion

![devopsworld File](devopsworld.jpg)

```

2019-10-18 02:18 UTC, zhaoying818 commented
封面图片 在正文中呈现  已完成！

2019-10-18 02:29 UTC, yJunS commented
> 封面图片 在正文中呈现 已完成！

Cool

2019-10-18 02:29 UTC, yJunS approved these changes
LGTM

2019-10-18 07:22 UTC, zhaoying818 commented
> 漏了时间了，日期都应该是发布的日期。

已经修复OK！

2019-10-18 07:27 UTC, donhui approved these changes
lgtm

2019-10-25 09:57 UTC, zhaoying818 commented
这个今天是不是可以发布了

2019-10-25 15:09 UTC, donhui approved these changes

2019-10-25 15:19 UTC, merged