[翻译-2019-10-28] 引入新的文件夹授权插件
jenkins-infra/wechat pull request #238
Opened 2019-10-18 08:39 UTC by wenjunzhangp

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-10-18 09:15 UTC, donhui reviewed
@wenjunzhangp 
感谢您的贡献，有几处需要规范或调整下～

2019-10-18 09:15 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +title: "引入新的文件夹授权插件"
引入新的文件夹授权插件
-->
介绍新的文件夹授权插件

2019-10-18 09:15 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +在我的 Google Summer of Code Projec t期间，我创建了全新的 Folder Auth 插件，可轻松管理 Folders 插件对文件夹中组织的项目的权限。这个新插件旨在通过易于管理的角色进行快速权限检查。该插件的1.0版本刚刚发布，可以从您的 Jenkins 更新中心下载。
Google Summer of Code Projec t
-->
Google Summer of Code Project

2019-10-18 09:15 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件的灵感来自角色策略插件 ，可改善性能并简化角色管理。开发该插件是为了克服角色策略插件在许多角色上的性能限制。同时，该插件通过文件夹解决了 Jenkins 中组织项目最受欢迎的方式之一。该插件还具有一个新的UI，将来会有更多改进。
新的UI
中英文之间加空格

2019-10-18 09:15 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +* 全球角色：适用于詹金斯的所有地方
全球角色：适用于詹金斯的所有地方
-->
全局角色：适用于 Jenkins 的所有地方

2019-10-18 09:15 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +## 带有Swagger支持的REST API
带有Swagger支持的REST API
中英文之间加空格

2019-10-18 09:15 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件提供 REST API ，用于通过 Swagger.json 管理具有 OpenAPI 规范的角色。您可以在 SwaggerHub 上签出 Swagger API  。SwaggerHub 提供了多种语言的存根，可以下载并用于与插件进行交互。您还可以使用 curl   从命令行查看一些示例请求。
您还可以使用 curl   从命令行查看一些示例请求
中英文之间保持一个空格

2019-10-18 09:15 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用 我在GSoC项目第一阶段中创建的微基准框架对改进进行 了评估。两个插件的相同配置的基准测试表明，与角色策略2.13中的全局角色相比，对 500 个全局角色而言，权限检查的速度最高快 934x ，后者本身包含了一些性能改进。将文件夹角色与“角色策略”的项目角色进行比较，可以对在 150 个用户的实例上组织在两层深度文件夹中的 250 个项目进行的权
这行有几个多余的空格

2019-10-18 09:32 UTC, wenjunzhangp commented
所提建议已经修改完毕！
thx！

2019-10-18 10:11 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用 我在 GSoC 项目第一阶段中创建的微基准框架对改进进行了评估。两个插件的相同配置的基准测试表明，与角色策略2.13中的全局角色相比，对500个全局角色而言，权限检查的速度最高快934x，后者本身包含了一些性能改进。将文件夹角色与“角色策略”的项目角色进行比较，可以对在150个用户的实例上组织在两层深度文件夹中的250个项目进行的权限检查，将访问
934x
-->
934倍

2019-10-18 10:11 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用 我在 GSoC 项目第一阶段中创建的微基准框架对改进进行了评估。两个插件的相同配置的基准测试表明，与角色策略2.13中的全局角色相比，对500个全局角色而言，权限检查的速度最高快934x，后者本身包含了一些性能改进。将文件夹角色与“角色策略”的项目角色进行比较，可以对在150个用户的实例上组织在两层深度文件夹中的250个项目进行的权限检查，将访问
您可以在此处查看基准和结果比较 。
`此处`应该有个超链接的

2019-10-18 10:11 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件的灵感来自角色策略插件 ，可改善性能并简化角色管理。开发该插件是为了克服角色策略插件在许多角色上的性能限制。同时，该插件通过文件夹解决了 Jenkins 中组织项目最受欢迎的方式之一。该插件还具有一个新的 UI ，将来会有更多改进。
该插件的灵感来自角色策略插件 ，
逗号前面的空格去掉

2019-10-18 10:11 UTC, donhui commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件的灵感来自角色策略插件 ，可改善性能并简化角色管理。开发该插件是为了克服角色策略插件在许多角色上的性能限制。同时，该插件通过文件夹解决了 Jenkins 中组织项目最受欢迎的方式之一。该插件还具有一个新的 UI ，将来会有更多改进。
该插件还具有一个新的 UI ，
UI 后面的空格也去掉

2019-10-18 10:22 UTC, wenjunzhangp commented
感谢您的review，建议已经修改完毕。
thx！

2019-10-18 10:22 UTC, donhui approved these changes
lgtm

2019-10-18 10:55 UTC, yJunS requested changes
建议添加一张封面图片，每一篇文章都要求有一张封面图片

2019-10-18 11:08 UTC, yJunS requested changes

2019-10-18 11:08 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +在我的 Google Summer of Code Project 期间，我创建了全新的 Folder Auth 插件，可轻松管理 Folders 插件对文件夹中组织的项目的权限。这个新插件旨在通过易于管理的角色进行快速权限检查。该插件的1.0版本刚刚发布，可以从您的 Jenkins 更新中心下载。
在原文中，` Google Summer of Code Project`、` Folder Auth Plugin`和`Folders plugin`等都有链接地址，请补充一下，保证文章的完整性

2019-10-18 11:08 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件的灵感来自角色策略插件，可改善性能并简化角色管理。开发该插件是为了克服角色策略插件在许多角色上的性能限制。同时，该插件通过文件夹解决了 Jenkins 中组织项目最受欢迎的方式之一。该插件还具有一个新的 UI，将来会有更多改进。
原文中`Role Strategy Plugin`有链接地址，同上

2019-10-18 11:08 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用 我在 GSoC 项目第一阶段中创建的微基准框架对改进进行了评估。两个插件的相同配置的基准测试表明，与角色策略2.13中的全局角色相比，对500个全局角色而言，权限检查的速度最高快934倍，后者本身包含了一些性能改进。将文件夹角色与“角色策略”的项目角色进行比较，可以对在150个用户的实例上组织在两层深度文件夹中的250个项目进行的权限检查，将访问
同上，原文中`micro-benchmark framework`有链接地址

2019-10-18 11:08 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件提供 REST API ，用于通过 Swagger.json 管理具有 OpenAPI 规范的角色。您可以在 SwaggerHub 上签出 Swagger API 。SwaggerHub 提供了多种语言的存根，可以下载并用于与插件进行交互。您还可以使用 curl 从命令行查看一些示例请求。
同上，原文中`SwaggerHub`、` curl`都有链接地址

2019-10-18 11:08 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +
文章似乎翻译不完整。以下内容都未翻译
![image](https://user-images.githubusercontent.com/20575981/67089588-96ff7780-f1da-11e9-8646-95b83470ff47.png)

2019-10-19 04:52 UTC, yJunS requested changes

2019-10-19 04:52 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件提供 REST API ，用于通过 Swagger.json 管理具有 OpenAPI 规范的角色。您可以在 [SwaggerHub](https://app.swaggerhub.com/apis/abhyudaya/folder-auth/1.0.0s) 上签出 Swagger API 。SwaggerHub 提供了多种语言的存根，可以下载并用于与插件进行交互。您还可以使用 [curl
原文 `check out` 翻译为 `签出`不太准确，`查看`是否更合适一些？

2019-10-19 04:52 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +在不久的将来，我想改进用户界面，使插件更容易使用。我还想改进 api 、文档和更多优化，以提高插件的性能。
> 我还想改进 api 、文档和更多优化

这句话似乎不太通顺。`优化`在这里是一个动词，不是一个名词

2019-10-19 04:52 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> + [GitHub](https://github.com/AbhyudayaSharma)
关于作者不是文章内实际都内容，是 [jenkins.io](https://jenkins.io) 模板引入的，参考[文章](https://github.com/jenkins-infra/jenkins.io/blob/master/content/blog/2019/08/2019-08-16-folder-auth-plugin.adoc)

2019-10-19 05:16 UTC, yJunS approved these changes
LGTM

2019-10-19 07:08 UTC, LinuxSuRen requested changes
非常感谢您的贡献，不过有一些地方还是需要调整下。

2019-10-19 07:08 UTC, LinuxSuRen commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> + [GitHub](https://github.com/AbhyudayaSharma)
`谷歌2019代码之夏` 这块不建议翻译，因为，翻译后会让人感觉到困惑。

2019-10-19 07:08 UTC, LinuxSuRen commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> + [GitHub](https://github.com/AbhyudayaSharma)
同意关于作者的部分，不用加进来。如果要体现作者的信息的话，我们可以从整体考虑，只要保持有引用即可。例如：从页面布局上可以显示出来作者。

2019-10-19 07:08 UTC, LinuxSuRen commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +description: "介绍新的文件夹授权插件"
这里的描述，您可以根据你自己对本文的理解加个描述。不过也不是强制性的。

2019-10-19 07:09 UTC, LinuxSuRen commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +
多余的空行，可以删除了。

2019-10-21 03:43 UTC, wenjunzhangp commented
建议已经修改完毕。thx！

2019-10-21 07:21 UTC, yJunS requested changes

2019-10-21 07:21 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用 我在 GSoC 项目第一阶段中创建的 [micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/) 对改进进行了评估。两个插件的相同配置的基准测试表明，与角色策略2.13中的全局角色相比，对500个全局角色而言，权限检查的速
> 使用 我在 GSoC 项目第一阶段中创建的 [micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/) 对改进进行了评估

这句话似乎还有些不太通顺，`使用`还多一个空格，整句话的意思有些不太明确

2019-10-21 13:13 UTC, zhaoying818 commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +在我的 [Google Summer of Code Project](https://jenkins.io/projects/gsoc/2019/role-strategy-performance) 期间，我创建了全新的 [Folder Auth](https://plugins.jenkins.io/folder-auth) 插件，可轻松管理 [Folders plugin](https:/
中文与数字之间需要加空格

2019-10-21 13:13 UTC, zhaoying818 commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用我在 GSoC 项目第一阶段中创建的 [micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/) 微基准框架进行了评估。两个插件的相同配置的基准测试表明，与角色策略2.13中的全局角色相比，对500个全局角色而言，权限检查的
中文与数字之间需要加空格

2019-10-22 02:47 UTC, wenjunzhangp commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用我在 GSoC 项目第一阶段中创建的 [micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/) 微基准框架进行了评估。两个插件的相同配置的基准测试表明，与角色策略2.13中的全局角色相比，对500个全局角色而言，权限检查的
感谢百忙抽空review，建议已经修改 thx

2019-10-22 03:19 UTC, yJunS requested changes

2019-10-22 03:19 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件的灵感来自角色策略插件，可改善性能并简化角色管理。开发该插件是为了克服 [Role Strategy Plugin](https://plugins.jenkins.io/role-strategy) 在许多角色上的性能限制。同时，该插件通过文件夹解决了 Jenkins 中组织项目最受欢迎的方式之一。该插件还具有一个新的 UI，将来会有更多改进。
`克服` 这个词是不是有些不太恰当？ `解决`是不是好一些？

2019-10-22 03:19 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用我在 GSoC 项目第一阶段中创建的 [micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/) 微基准框架进行了评估。两个插件的相同配置的基准测试表明，与角色策略 2.13 中的全局角色相比，对 500 个全局角色而言，权
> 对 500 个全局角色而言，权限检查的速度最高快   934 倍

`对 500 个全局角色而言`前半句话不太容易理解意思，后半句话的数字前多空格

2019-10-22 03:19 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +该插件支持 Jenkins 的“代码配置”功能，因此您无需通过 Web UI 即可配置权限。YAML 配置如下所示：
代码配置 -> 代码即配置

2019-10-22 07:02 UTC, yJunS requested changes

2019-10-22 07:02 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件旨在在权限检查中胜过“角色策略插件”。使用我在 GSoC 项目第一阶段中创建的 [micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/) 微基准框架进行了评估。两个插件的相同配置的基准测试表明，与角色策略 2.13 中的全局角色相比，权限检查的速度最高快 934
> Benchmarks for identical configurations for both plugin show that the permissions check are up to 934x faster for 500 global roles when compared to the global roles from the Role Strategy 2.13,

原文中的话被直接截了？不太好吧

2019-10-22 11:03 UTC, yJunS requested changes

2019-10-22 11:03 UTC, yJunS commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件的设计目的是在权限检查方面优于角色策略插件。这些改进是使用我在 GSOC 项目的第一阶段创建的[micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/)来衡量的。两个插件相同配置的基准测试表明，与角色策略 2.13 中的全局角色相比， 500 个全局角色的权限检查速
> 500 个全局角色的权限检查速度高达 934 倍

`高达`不是一个比较都词汇吧，用`提高了`似乎更好

`[micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/)` 建议前后加上空格

2019-10-23 02:01 UTC, wenjunzhangp commented on articles/2019/10/2019-10-28-introducing-new-folder-authorization-plugin.md
> +此插件的设计目的是在权限检查方面优于角色策略插件。这些改进是使用我在 GSOC 项目的第一阶段创建的[micro-benchmark framework](https://jenkins.io/blog/2019/06/21/performance-testing-jenkins/)来衡量的。两个插件相同配置的基准测试表明，与角色策略 2.13 中的全局角色相比， 500 个全局角色的权限检查速
已调整

2019-10-23 16:01 UTC, yJunS reviewed
感觉应该问题不大了

2019-10-28 08:19 UTC, LinuxSuRen approved these changes

2019-10-28 08:20 UTC, merged