[翻译-2019-10-30] Building a new operating model for DevOps
jenkins-infra/wechat pull request #245
Opened 2019-10-27 17:14 UTC by zhaoying818

[翻译-2019-10-30] Building a new operating model for DevOps

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://www.linkedin.com/pulse/building-new-operating-model-devops-jon-hammant/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-10-29 00:23 UTC, LinuxSuRen commented
建议把日期推后到11月6日，因为，大家可能没有足够的时间来review。而且，这样也不至于有的周有文章发，有的周没有。

2019-10-29 02:44 UTC, zhaoying818 commented
> 建议把日期推后到11月6日，因为，大家可能没有足够的时间来review。而且，这样也不至于有的周有文章发，有的周没有。按照，我们目前出文章的速度，能保证一周有一篇就很不错了。

好的，那我找时间修改一下！

2019-10-29 15:38 UTC, zhaoying818 commented
预计发布时间修改到了2019-11-06
请审核！

2019-10-30 01:40 UTC, donhui commented on articles/2019/11/2019-11-06-building-new-operating-model-devops.md
> +在我的下一个博客中，我将探讨帮助DevOps扩展的另一个关键因素：度量。
我将探讨帮助DevOps扩展的另一个关键因素：度量。
DevOps 中英文空格

2019-10-30 01:40 UTC, donhui commented on articles/2019/11/2019-11-06-building-new-operating-model-devops.md
> +我一直在 [撰写](https://www.linkedin.com/pulse/main-challenge-devops-doing-scale-jon-hammant/) 有关企业面临的 DevOps 挑战的文章。从根本上讲，它是关于规模的：当企业尝试将其扩展到大型企业通常拥有的 800 多个应用程序中时，它们正努力实现在小型 DevOps 概念验证中看到的相同收益。 如果 DevOps
[撰写]
前后不需要空格

2019-10-30 02:00 UTC, yJunS requested changes

2019-10-30 02:00 UTC, yJunS commented on articles/2019/11/2019-11-06-building-new-operating-model-devops.md
> +DevOps 的理想运营模式是一种权力民主化的模式，并且公司中的每个人都有权发挥自己的领导作用。在这里，高级主管确定了出行的方向，但是然后相信他们熟练的开发人员会做些必要的事情。在这种模式下，管理者促进和授权，而不是直接；确保开发人员拥有实现目标所需的一切，同时在这里和那里轻轻地推动，以确保他们的工作与整体公司议程和战略路线图保持一致。这涉及到我们在流动的劳动力中看到的宏观变化，并逐渐过渡到非中
> 而不是直接

这句话翻译过来会有点看不懂，感觉改为`而不是直接参与`是不是好一些？

2019-10-30 02:00 UTC, yJunS commented on articles/2019/11/2019-11-06-building-new-operating-model-devops.md
> +在我的下一个博客中，我将探讨帮助DevOps扩展的另一个关键因素：度量。
> 我将探讨帮助DevOps扩展的另一个关键因素

中英文空格

2019-10-30 02:00 UTC, yJunS commented
。。。   有重复了

2019-10-30 03:09 UTC, LinuxSuRen commented
> 。。。 有重复了

这是啥意思，尽量把事情描述清楚了，没有上下文，几乎很难看懂。

2019-10-30 04:51 UTC, yJunS commented
> > 。。。 有重复了
> 
> 这是啥意思，尽量把事情描述清楚了，没有上下文，几乎很难看懂。

我的问题，我是想说review和 @donhui 的重复了，与其他无关，抱歉

2019-10-30 14:21 UTC, zhaoying818 commented on articles/2019/11/2019-11-06-building-new-operating-model-devops.md
> +在我的下一个博客中，我将探讨帮助DevOps扩展的另一个关键因素：度量。
已经修改

2019-10-30 14:21 UTC, zhaoying818 commented on articles/2019/11/2019-11-06-building-new-operating-model-devops.md
> +我一直在 [撰写](https://www.linkedin.com/pulse/main-challenge-devops-doing-scale-jon-hammant/) 有关企业面临的 DevOps 挑战的文章。从根本上讲，它是关于规模的：当企业尝试将其扩展到大型企业通常拥有的 800 多个应用程序中时，它们正努力实现在小型 DevOps 概念验证中看到的相同收益。 如果 DevOps
空格已经取消
多谢

2019-10-30 14:22 UTC, zhaoying818 commented on articles/2019/11/2019-11-06-building-new-operating-model-devops.md
> +DevOps 的理想运营模式是一种权力民主化的模式，并且公司中的每个人都有权发挥自己的领导作用。在这里，高级主管确定了出行的方向，但是然后相信他们熟练的开发人员会做些必要的事情。在这种模式下，管理者促进和授权，而不是直接；确保开发人员拥有实现目标所需的一切，同时在这里和那里轻轻地推动，以确保他们的工作与整体公司议程和战略路线图保持一致。这涉及到我们在流动的劳动力中看到的宏观变化，并逐渐过渡到非中
已修改

2019-10-31 07:41 UTC, yJunS approved these changes
LGTM

2019-11-05 11:02 UTC, LinuxSuRen approved these changes

2019-11-06 06:43 UTC, merged