[翻译-2019-11-01]在 Kubernetes 中通过 Apache Kafka 插件远程处理 Kafka 启动程序
jenkins-infra/wechat pull request #249
Opened 2019-10-28 08:53 UTC by wenjunzhangp

[翻译-2019-11-01]在 Kubernetes 中通过 Apache Kafka 插件远程处理 Kafka 启动程序

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-10-28 08:56 UTC, LinuxSuRen submitted a review, later dismissed
包含了 #248 的内容

2019-10-28 09:38 UTC, wenjunzhangp commented
去掉 #248 的内容

2019-10-28 11:57 UTC, yJunS requested changes
不应该直接删除，应该和主分支同步，不显示出删除的文件，否则会把主分支的文件删除掉

2019-10-28 12:25 UTC, LinuxSuRen commented
[这里](https://jenkins-zh.cn/about/branching-strategy/)有我们推荐使用的分支策略

2019-10-29 15:46 UTC, zhaoying818 commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> + Apache-Kafka 插件上远程处理的 Helm 图表基于 [stable/jenkins](https://github.com/helm/charts/tree/master/stable/jenkins) 图表和 [incubator/kafka](https://github.com/helm/charts/tree/master/incubator/kafka) 图表。截至目前，
进行中  修改为 开发中，是否更好？

2019-10-29 15:52 UTC, zhaoying818 commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +* 启动单个 Remoting Kafka Agent 窗格。
pod 是否 需要翻译？

2019-10-30 00:57 UTC, LinuxSuRen commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +* 启动单个 Remoting Kafka Agent 窗格。
不建议翻译 pod

2019-10-30 01:42 UTC, donhui commented
这个 PR 我建议重新从 master 拉新分支提交下，因为提交记录有点乱，并且删除了一些东西，这样最终会在 master 分支上也把它删掉。
建议一个任务一个分支，可以参考：https://jenkins-zh.cn/about/branching-strategy/

2019-10-30 01:44 UTC, LinuxSuRen commented
不要再重新增加 PR 了，就在这个 PR 里做修改吧。如果有疑问的话，今天晚上的例会上可以讨论下。

> On Oct 30, 2019, at 09:42, Donghui Wang <notifications@github.com> wrote:
> 
> R 我建议重新从 master 拉新分支提交下，因为提交记录有点乱，并且删除了一些东西，这样最终会在 master 分支上也把它删掉。
> 建议一个任务一个分支，可

2019-10-30 07:53 UTC, wenjunzhangp commented
建议已经修改，另外在 @yJunS 的帮助下，这个分支已经正常了，麻烦大家在帮忙review下，辛苦了~

2019-10-31 07:40 UTC, yJunS requested changes

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +- remoting kafka kubernetes helm developer gsoc gsoc2019
标签和关键字建议分开去写

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +我是越南 FPT 大学的龙阮。 [Remoting over Apache Kafka with Kubernetes features](https://jenkins.io/projects/gsoc/2019/remoting-over-apache-kafka-docker-k8s-features/) 是我在谷歌 2019 代码之夏的项目。这是我第一次为 Jenkins 做贡献，我非常
`龙阮`是根据什么翻译的呢？

`谷歌 2019 代码之夏`也不应该翻译的

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +当前版本的 [Remoting over Apache Kafka plugin](https://github.com/jenkinsci/remoting-kafka-plugin) 远程处理需要用户手动配置整个系统，包括 zookeeper 、 kafka 和远程处理代理。它也不支持动态代理配置，因此很难实现可伸缩性。我的项目旨在解决两个问题：
`zookeeper 、 kafka`和顿号之间不需要空格

> 它也不支持动态代理配置，因此很难实现可伸缩性

`可伸缩性`应该算是形容词吧，根据上下文的语义，修改为`因此很难实现具有伸缩性的扩展`会不会好一些？

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +*  Kubernetes 集群中的动态代理配置。
这两处原文中都有序号排列

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +* 在 Kubernetes 特性中完全实现了 Apache-Kafka 配置。
这句话好像与原文翻译不太符合，并不是在 Kubernetes 中实现的

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +此功能是 2.0 版本的一部分，因此尚未正式发布。您可以通过使用 [Experimental Update Center](https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/) 更新到 2.0.0-alpha 版本或直接从 master branch 构建来尝试该功能：
`branch`可以翻译为`分支`的

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +当用户单击“在 Kubernetes 上启动 Kafka ”按钮时， Jenkins 将根据信息创建一个 Kubernetes 客户机，然后从资源中应用 zookeeper 和 kafka yaml 规范文件。
`Start Kafka on Kubernetes`为按钮内容，建议不翻译，并且原文中有单独以 code 形式标记的。
`resources`在原文中也以 code 形式标记的

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> + Apache-Kafka 插件上远程处理的 Helm 图表基于 [stable/jenkins](https://github.com/helm/charts/tree/master/stable/jenkins) 图表和 [incubator/kafka](https://github.com/helm/charts/tree/master/incubator/kafka) 图表。截至目前，
`CloudAPI`在原文中应该是分开的

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +statefulset.apps/demo-zookeeper   1/1     6m30s
这些红底是什么情况？

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +命令 do.sh start 将执行以下步骤：
`do.sh start`原文中是 code 形式标记的

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +* 安装图标( Jenkins Kafka )。
括号和英文之间不用空格

2019-10-31 07:40 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +您可以通过运行 kubectl 来检查图表状态，例如:
`kubectl`原文中 code 标记的

2019-10-31 09:36 UTC, wenjunzhangp commented
建议已经修改完毕，十分抱歉由于我的操作失误和对git分支的不熟悉，导致了很多不好的影响，实在抱歉。这篇文章翻译过后，我停一段时间，好好学习一个git分支的操作和各种push pull merge。由于之前很少使用git，git也从来没有参与过多人协作开发的模式，我很抱歉。

2019-10-31 21:43 UTC, LinuxSuRen commented
@wenjunzhangp 没关系的，这正好说明，通过你参与社区的贡献，有助于提升 git 的使用技能。加油⛽️！

2019-11-01 00:40 UTC, yJunS commented
@wenjunzhangp 我现在看到的昨天提的 review 内容被删除了？不是删除内容，应该是修改才对。

2019-11-01 00:43 UTC, yJunS commented
还有一个情况可能需要注意一下，这里的地址应该是原文地址，而不是社区网站地址
![image](https://user-images.githubusercontent.com/20575981/67995081-94455d80-fc83-11e9-92e0-baeb2508640e.png)

2019-11-01 01:24 UTC, yJunS reviewed
建议文章发布日期往后推一下

2019-11-01 02:05 UTC, yJunS commented on articles/2019/11/2019-11-01-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +我是越南 FPT 大学的龙阮。 [Remoting over Apache Kafka with Kubernetes features](https://jenkins.io/projects/gsoc/2019/remoting-over-apache-kafka-docker-k8s-features/) 是我在谷歌 2019 代码之夏的项目。这是我第一次为 Jenkins 做贡献，我非常
这段的自我介绍没有了。`Google Summer of Code 2019`应该直接写出来就可以

2019-11-01 04:53 UTC, wenjunzhangp commented
谢谢大家的review，建议已经修改完毕。文章发布日期推后到11-08。

2019-11-01 05:08 UTC, yJunS requested changes

2019-11-01 05:08 UTC, yJunS commented on articles/2019/11/2019-11-08-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +在全局配置页面上，用户可以输入 Kubernetes 服务器信息和凭据。然后他们只需单击一个按钮就可以启动 ApacheKafka 。
`单击`换成`点击`或许更好

2019-11-01 05:08 UTC, yJunS commented on articles/2019/11/2019-11-08-remoting-over-apache-kafka-plugin-with-kafka-launcher-in-kubernetes.md
> +* 安装图标(Jenkins Kafka)。
`图标` ？

2019-11-04 12:05 UTC, yJunS approved these changes
LGTM

2019-11-08 07:14 UTC, merged