[翻译-2019-11-11] GSOC 第一阶段工作时间插件更新
jenkins-infra/wechat pull request #251
Opened 2019-11-05 04:49 UTC by wenjunzhangp

[翻译-2019-11-11] GSOC 第一阶段工作时间插件更新

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-11-06 15:54 UTC, yJunS reviewed
英文和标点符号间不需要空格的

2019-11-07 01:34 UTC, donhui commented
工作时间 简写成 工时 会不会好点？

2019-11-07 01:36 UTC, LinuxSuRen commented
建议不要翻译 working hours，不管翻译成工作时间还是工时都是有歧义的。

2019-11-07 03:42 UTC, wenjunzhangp commented
建议修改完成，感谢大家的review：）

2019-11-08 08:00 UTC, yJunS requested changes

2019-11-08 08:00 UTC, yJunS commented on articles/2019/11/2019-11-11-gsoc-phase-1-updates-on-working-hours-plugin.md
> +poster: “./2019-11-11-gsoc-phase-1-updates-on-working-hours-plugin/cover.jpg”
可以换成半角的引号或者不加

2019-11-08 08:00 UTC, yJunS commented on articles/2019/11/2019-11-11-gsoc-phase-1-updates-on-working-hours-plugin.md
> +在 Google Summer of Code 的第一个代码阶段，我一直在从事“[Working Hours Project](https://jenkins.io/projects/gsoc/2019/working-hours-improvements/)”项目，该项目还有待于改善可用性。
> “[Working Hours Project](https://jenkins.io/projects/gsoc/2019/working-hours-improvements/)”

原文中没有引号

2019-11-12 02:33 UTC, closed without merging

2019-11-12 02:35 UTC, LinuxSuRen commented
再次提醒下，任何时候，都不需要使用强制推送