[翻译-2019-11-13]了解如何使用 Jenkins-X UpdateBot
jenkins-infra/wechat pull request #252
Opened 2019-11-05 08:31 UTC by wenjunzhangp

[翻译-2019-11-13]了解如何使用 Jenkins-X UpdateBot

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://dzone.com/articles/using-jenkins-x-updatebot/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-11-07 02:10 UTC, donhui commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +在 [Jenkins-X platform](https://jenkins-x.io/about/) 中，`UpdateBot` 由 Jenkinsfiles 中的 updatebot 命令自动显示和调用。但是 UpdateBot 也可以在 Jenkins-X 之外使用，并且单独运行它可以帮助了解它可以做什么并测试版本替换。因此，让我们用一个简单的测试项目来尝试一下。
Jenkinsfiles 在英文中是复数
中文翻译时，建议去掉最后面的 s

2019-11-07 02:10 UTC, donhui commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +在 [Jenkins-X platform](https://jenkins-x.io/about/) 中，`UpdateBot` 由 Jenkinsfiles 中的 updatebot 命令自动显示和调用。但是 UpdateBot 也可以在 Jenkins-X 之外使用，并且单独运行它可以帮助了解它可以做什么并测试版本替换。因此，让我们用一个简单的测试项目来尝试一下。
updatebot 命令 --> `updatebot` 命令
updatebot 前后加"`"

2019-11-07 02:10 UTC, donhui commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +UpdateBot 可以为各种不同的[文件类型设置版本](https://github.com/jenkins-x/updatebot/blob/a08fdec38654a96f8bc5785b59b086193e861911/updatebot-core/src/main/java/io/jenkins/updatebot/kind/Kind.java#L30)-我们不会在这里对它们进行全部测
我们将对其运行 UpdateBot ，以查看这些资源文件中可以替换哪些 UpdateBot。
-->
我们将对其运行 UpdateBot ，以查看 UpdateBot 可以替换这些资源文件中哪些内容。

2019-11-07 02:10 UTC, donhui commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +如果我们在没有空运行标志的情况下运行，则将创建一个真实的拉取请求，前提是我们有权创建该请求。
如果我们在没有空运行标志的情况下运行，则将创建一个真实的拉取请求，前提是我们有权创建该请求。
-->
如果我们在没有 dry-run 标记的情况下运行，则将创建一个真实的 pull request，前提是我们有权创建它。
dry-run 和 pull request 建议不翻译

2019-11-07 02:10 UTC, donhui commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +UpdateBot 具有自动合并拉动请求的功能，例如通过轮询 GitHub 来检查 PR 状态并合并是否一切正常（命令为`updatebot update-loop`）。但是，GitHub 确实对这些请求进行了速率限制，因此 UpdateBot 也可以将其[批准添加到 PR ](https://github.com/jenkins-x/updatebot/blob/a08fdec38654a96
UpdateBot 具有自动合并拉动请求的功能，
-->
UpdateBot 具有自动合并 pull request 的功能，

2019-11-07 02:10 UTC, donhui commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +例如，在[构建没有快照的 Maven 项目](https://redstack.wordpress.com/2014/07/14/continuous-integration-without-snapshots/)时，[UpdateBot 可用于在 CI / CD 设置中传播版本](https://community.alfresco.com/community/bpm/blog/2018/11
可以对产生各种不同类型工件的项目进行一系列更改。
-->
可以对产生各种不同类型制品的项目进行一系列更改。
artifacts 统一翻译为制品，可以参考下[翻译规范](https://github.com/jenkins-zh/translation-spec/blob/master/specification.md)

2019-11-07 04:02 UTC, wenjunzhangp commented
建议修改完成，感谢大家的review：）

2019-11-07 05:54 UTC, donhui approved these changes
LGTM

2019-11-08 09:02 UTC, yJunS requested changes

2019-11-08 09:02 UTC, yJunS commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +poster: “./2019-11-15-using-jenkins-x-updatebot/cover.jpg”
引号建议换位半角的引号

2019-11-11 01:33 UTC, zhaoying818 commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +然后，我们仍然需要使用 `UPDATEBOT_GITHUB_USER` 和 `UPDATEBOT_GITHUB_PASSWORD`（[或令牌](https://github.com/jenkins-x/updatebot/blob/a08fdec38654a96f8bc5785b59b086193e861911/updatebot-core/src/main/java/io/jenkins/up
token 这个可以保留，不用翻译为 令牌

2019-11-11 01:35 UTC, zhaoying818 commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +例如，在[构建没有快照的 Maven 项目](https://redstack.wordpress.com/2014/07/14/continuous-integration-without-snapshots/)时，[UpdateBot 可用于在 CI / CD 设置中传播版本](https://community.alfresco.com/community/bpm/blog/2018/11
CI/CD 这个/ 左右不需要加空格

2019-11-11 12:12 UTC, yJunS requested changes

2019-11-11 12:12 UTC, yJunS commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +这表明我们可以抓取出来。Dockerfile 实际上使用两个不同的 openjdk 映像，每个映像都有一个不同的标签，并且此命令将替换这两个映像：
映像 -> 镜像

2019-11-11 12:12 UTC, yJunS commented on articles/2019/11/2019-11-15-using-jenkins-x-updatebot.md
> +本示例使用单个 UpdateBot YAML 文件将一组依赖项/版本推送到单个下游项目。YAML 文件还支持将一组更改推送到多个[下游存储库](https://github.com/jenkins-x/jenkins-x-platform/commit/196ef005ff026cbd9be8fd505945bbbc5b71da67)。UpdateBot 推送其能够进行的所有替换，以便每个下游存
> 推送到单个下游项目

这里从语义上来看，`推送到一个下游项目`应该就可以了，用`单个`到话感觉会有些不太通顺了

2019-11-12 08:34 UTC, yJunS commented
建议在解决了之前的 `request changes` 之后，把已解决的对话结束掉，也算是一个任务的终止

2019-11-15 10:38 UTC, LinuxSuRen approved these changes

2019-11-15 10:39 UTC, merged