[翻译-2019-11-09]Jenkins 2019 年董事会和官员选举更新
jenkins-infra/wechat pull request #256
Opened 2019-11-09 06:39 UTC by wenjunzhangp

[翻译-2019-11-09]Jenkins 2019 年董事会和官员选举更新

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2019/11/08/board-elections/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-11-10 03:02 UTC, donhui commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +竞选活动主任的候选人是：
活动主任
-->
活动官员
这个建议和上面保持一致

2019-11-10 03:02 UTC, donhui commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +每位候选人都提供了一份声明，以帮助指导选民为什么要为候选人投票。有关更多详细信息，请参阅[候选语句](https://docs.google.com/document/d/15rJYkBjWLGZTL87xeJ4P2Y1LNn7C0EBb0wkDVUSfLmQ/edit#)。竞选董事会职位的候选人为：
候选语句
-->
候选人的声明

2019-11-10 03:02 UTC, donhui commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +这是近一段时间以来我们第一次进行 Jenkins 选举。我们正在学习。Jenkins 选举旨在实现包容性。我们不仅将选举限于代码提交者。在 2019 年 9 月 1 日之前注册了 Jenkins 帐户的任何人都有资格投票。Jenkins 是一个成功的项目，大约有 10 万个符合该标准的帐户。因此，我们正在与符合条件的选民联系，并要求他们明确 `opt-in` 以参加投票。
`opt-in`
-->
`选择性加入`

2019-11-10 03:02 UTC, donhui commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +如果符合条件，您将在注册的 jenkins.io 电子邮件地址中收到一封电子邮件。该邮件来自 elections@jenkins.io，标题为 `2019 Jenkins Election-邀请参加`。该电子邮件将提供选举详细信息，并包含一个 `I want to participate` 按钮。
`2019 Jenkins Election-邀请参加`
这里是邮件标题，建议保持原文
`2019 Jenkins Election - Invitation to Participate`

2019-11-10 03:06 UTC, donhui commented
文中的格式（比如：表格），建议和原文保持一致
原文：https://github.com/jenkins-infra/jenkins.io/pull/2632/files

2019-11-10 04:13 UTC, yJunS requested changes

2019-11-10 04:13 UTC, yJunS commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +description: "Jenkins 社区正在进行 2019 年董事会和官员职位的选举，提名征集已经结束。有关更多详细信息请阅读下文。"
描述建议仅写描述即可，阅读下文等文字没必要写在描述中

2019-11-10 04:13 UTC, yJunS commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +投票将于 2019 年 11 月 11 日正式开始。候选人将收到 Kohsuke Kawaguchi 发送的 Condorcet 互联网投票电子邮件。每次投票将发送一封电子邮件（因此，总共 3 票：董事会 1 票，活动官员 1 票，安全官员 1 票）。投票将要求使用以下截图对候选人进行排名：
> 因此，

在这里建议去掉，加上之后感觉语句不太通顺

2019-11-10 12:03 UTC, LinuxSuRen commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +竞选活动主任的候选人是：
我建议 event officer 等不要翻译，保持原文，至少没有见到国内有类似的名称。

2019-11-10 12:03 UTC, LinuxSuRen commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +每位候选人都提供了一份声明，以帮助指导选民为什么要为候选人投票。有关更多详细信息，请参阅[候选语句](https://docs.google.com/document/d/15rJYkBjWLGZTL87xeJ4P2Y1LNn7C0EBb0wkDVUSfLmQ/edit#)。竞选董事会职位的候选人为：
候选人宣言？

2019-11-10 12:06 UTC, LinuxSuRen commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +description: "Jenkins 社区正在进行 2019 年董事会和官员职位的选举，提名征集已经结束。有关更多详细信息请阅读下文。"
描述，是为了吸引读者继续阅读的简短文字。尽量从读者的角度来想这个问题，例如：”Jenkins 社区选举活动期待您的参与“等等

2019-11-10 12:10 UTC, LinuxSuRen requested changes
建议把“董事会”、“官员”保持原文，不要翻译。因为，中文的表述和英文的含义不完全一样，甚至，容易产生歧义。

2019-11-10 12:10 UTC, LinuxSuRen commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +* Zhao Xiaojie (a.k.a. Rick to many of you)
建议把我的名字该成中文的”赵晓杰“，谢谢。或者是：
赵晓杰（Rick）

2019-11-10 12:10 UTC, LinuxSuRen commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +[cols="s,n",options="header"]
这个表格要用markdown的格式

2019-11-10 12:10 UTC, LinuxSuRen commented on articles/2019/11/2019-11-09-2019-jenkins-board-and-officer-elections-update.md
> +|==================================================
表格格式

2019-11-10 13:33 UTC, LinuxSuRen commented
#257 优先发布
建议这篇放到 12号发
#251 放到13号发

2019-11-10 17:23 UTC, yJunS reviewed
建议之后的封面图片尽量与文章相关度高一些，这样也有利于有一个好的导读

2019-11-11 02:43 UTC, wenjunzhangp commented
> 建议之后的封面图片尽量与文章相关度高一些，这样也有利于有一个好的导读

好的，下次翻译注意收集和文章有关的

2019-11-11 03:01 UTC, LinuxSuRen commented
这次就换一个封面图吧

2019-11-11 04:38 UTC, wenjunzhangp commented
> 这次就换一个封面图吧

好的，等下我找一个合适的

2019-11-11 04:58 UTC, wenjunzhangp commented
封面图已更换。

2019-11-11 13:54 UTC, LinuxSuRen requested changes
不仅仅是标题上要修改日期，文件和目录中的日期也要修改。

2019-11-12 04:53 UTC, LinuxSuRen approved these changes

2019-11-12 14:13 UTC, merged