[翻译-2019-11-13]Working Hours 插件的第一阶段更新
jenkins-infra/wechat pull request #258
Opened 2019-11-12 02:48 UTC by wenjunzhangp

[翻译-2019-11-13]Working Hours 插件的第一阶段更新

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2019/07/09/Phase1-Updates-On-Working-Hours-Plugin/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-11-12 08:27 UTC, yJunS requested changes
#251 
尽量建议在原有的PR基础上操作，无论什么时候坚持不做 `push -force` 的操作，可能会因为某一次强制提交导致其他文件的改变

2019-11-12 08:27 UTC, yJunS commented on articles/2019/11/2019-11-13-gsoc-phase-1-updates-on-working-hours-plugin.md
> +description: "Working Hours 插件的第一阶段更新"
描述的问题建议还是更改一下

2019-11-12 14:21 UTC, LinuxSuRen commented
我们把这个调整到14号？13号得发布一份感谢信 #259

2019-11-13 03:00 UTC, wenjunzhangp commented
好的，我这边来修改一下发布日期。
昨天#251这个PR我本地分支不小心merge了master和别的分支的内容，然后我捣鼓了半天也没弄好，最后不得已新弄了一个PR和本地的分支，实在抱歉，昨天又操作失误了  :(

2019-11-13 03:18 UTC, yJunS reviewed
建议把 PR 的日期也修改一下

2019-11-13 04:14 UTC, LinuxSuRen commented
描述并不是一个完整的句子，只是个片段，因此不需要句号，我已经调整了。

2019-11-14 09:51 UTC, LinuxSuRen approved these changes

2019-11-14 09:51 UTC, merged