[原创-2019-11-13] 致霍格沃兹测试学院的一份感谢信
jenkins-infra/wechat pull request #259
Opened 2019-11-12 04:45 UTC by LinuxSuRen

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-11-12 14:57 UTC, donhui commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +* 代码开源
列出几个重要的代码仓库？

2019-11-12 14:57 UTC, donhui commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +但是，我们今天尤其想要表示感谢的是——下面给予 Jenkins 中文社区现金10000元捐赠的企业。
但是，
这个但是可否去掉？

2019-11-12 17:29 UTC, yJunS commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +但是，我们今天尤其想要表示感谢的是——下面给予 Jenkins 中文社区现金10000元捐赠的企业。
赞同，`但是`这个词汇有点驳回前面话的意思

2019-11-13 00:29 UTC, LinuxSuRen commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +* 代码开源
是否把这个地址 https://github.com/jenkins-zh 给出来就好来，对我们来说，都是重要的，没有不重要的。

2019-11-13 01:19 UTC, donhui commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +* 代码开源
也可以～

2019-11-13 01:21 UTC, donhui commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +title: "致霍格沃兹测试学院的一份感谢信"
一份感谢信
-->
一封感谢信
？

2019-11-13 02:06 UTC, yJunS requested changes

2019-11-13 02:06 UTC, yJunS commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +Jenkins 虽然有着无数潜在的用户群体，但是，在国内直接参与社区的人却了了无几，甚至，
`了了无几` -> `寥寥无几`?

2019-11-13 02:06 UTC, yJunS commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +在一年前成立了。我们从双周例会（公开讨论社区发展相关的话题），扩展到单周技术交流会
`扩展到` 感觉有些不切当，这不是一个从 A 到 B 的过程，感觉用`拓展了`会更适合一些

2019-11-13 02:06 UTC, yJunS commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +包括：图书、大会免费门票等等。这要感谢人民邮电出版社等对我们长期的大力支持。
> 这要感谢人民邮电出版社等对我们长期的大力支持

感觉前面既然提到大会免费门票的话，把合作社区也提一下会好一点

2019-11-13 02:06 UTC, yJunS commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +* 代码开源
是不是可以按 GitHub 和 Gitee 同时展示出来？

2019-11-13 02:59 UTC, LinuxSuRen commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +* 代码开源
Gitee 我们几乎都没有怎么用，而且，基本是作为备份的。不建议放。

2019-11-13 03:01 UTC, LinuxSuRen commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +包括：图书、大会免费门票等等。这要感谢人民邮电出版社等对我们长期的大力支持。
大会免费门票，指的是激励。合作社区是什么概念？

2019-11-13 03:01 UTC, LinuxSuRen commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +在一年前成立了。我们从双周例会（公开讨论社区发展相关的话题），扩展到单周技术交流会
用“增加了”？

2019-11-13 03:06 UTC, yJunS approved these changes
LGTM

2019-11-13 03:06 UTC, yJunS commented on articles/2019/11/2019-11-13-a-thanks-letter.md
> +* 代码开源
好的，目前看应该没什么问题了

2019-11-13 03:19 UTC, donhui approved these changes
lgtm

2019-11-13 04:12 UTC, merged