[原创-2019-11-20] jenkins-cli-help-you-manage-jenkins
jenkins-infra/wechat pull request #263
Opened 2019-11-15 15:48 UTC by donhui

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-11-15 23:56 UTC, LinuxSuRen requested changes
非常好👍，有处错别字的。另外，可以提一下目前的代码质量的部分，以及单元测试覆盖率，这都是项目重要的部分。

2019-11-15 23:56 UTC, LinuxSuRen commented on articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins.md
> +作为中国开眼界的一份子，此时此刻，Jenkins CLI 正在参加由 OSCHINA（开源中国）主办的`2019年度最受欢迎中国开源软件评选`活动。
`中国开眼界`?

2019-11-15 23:56 UTC, LinuxSuRen commented on articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins.md
> +Jenkins CLI，简称 jcli，一个由国人开发的开源的 Jenkins 命令行工具。
`国人开发的` 我觉得是不是不用强调这个呢？

2019-11-16 00:50 UTC, donhui commented on articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins.md
> +Jenkins CLI，简称 jcli，一个由国人开发的开源的 Jenkins 命令行工具。
那去掉，改成 `使用 Golang 开发的`

2019-11-16 01:26 UTC, donhui commented
已修正，并对代码质量增加了说明。

2019-11-16 01:46 UTC, LinuxSuRen approved these changes

2019-11-17 07:49 UTC, yJunS commented on articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins.md
> +
建议可以把 `gofish` 和 `Scoop` 包管理器的方式也添加进去，`gofish` 同时支持 linux 和 windows，`Scoop` 支持 windows，这样会有多种选择

2019-11-17 07:49 UTC, yJunS commented on articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins.md
> +如果你在使用过程中遇到问题，欢迎在 GitHub 仓库提交 issue 来反馈；
`issue` 是不是可以添加一个链接？

2019-11-18 01:35 UTC, donhui commented on articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins.md
> +如果你在使用过程中遇到问题，欢迎在 GitHub 仓库提交 issue 来反馈；
加上了

2019-11-18 01:36 UTC, donhui commented on articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins.md
> +
加上了，我想问下，这两个包管理器用的人多么，我是没用过

2019-11-18 02:13 UTC, yJunS commented on articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins.md
> +
`gofish` 和 `Scoop` 我之前没听过。   是 @LinuxSuRen 找的。在 windows 下我个人感觉 `chocolatey` 很方便，只是打包方式有点困难。

2019-11-19 23:47 UTC, merged