[翻译-2019-11-29] Jenkins CI/CD 集成 Git Secrets
jenkins-infra/wechat pull request #266
Opened 2019-11-20 16:47 UTC by zhaoying818

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://dzone.com/articles/jenkins-cicd-with-git-secrets/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [x] 维护

2019-11-21 02:01 UTC, yJunS reviewed
建议提交的PR里不要有过多的 commit 记录

2019-11-21 10:24 UTC, zhaoying818 commented
好的

2019-11-22 06:46 UTC, donhui reviewed
git-sercret  学习了

2019-11-22 06:46 UTC, donhui commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +git-secret 的工作方式如下。进入仓库中要加密文件的文件夹，然后，运行 `git init && git secret init`。这将初始化 `.gitsecret` 文件夹，然后运行 `git secret tell $email`，如果您希望其他用户解密密钥文件，则必须导入其 gpg 公钥，然后再次运行 `git secret tell $otheruseremailid`。现在您
`$yoursecretfile.secret`
建议改成，与上面的 `git secret add $secretfilename` 保持一致
`$secretfilename.secret`

2019-11-22 06:46 UTC, donhui commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +git-secret 的工作方式如下。进入仓库中要加密文件的文件夹，然后，运行 `git init && git secret init`。这将初始化 `.gitsecret` 文件夹，然后运行 `git secret tell $email`，如果您希望其他用户解密密钥文件，则必须导入其 gpg 公钥，然后再次运行 `git secret tell $otheruseremailid`。现在您
原文这里没有描述清楚

2019-11-22 09:59 UTC, zhaoying818 commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +git-secret 的工作方式如下。进入仓库中要加密文件的文件夹，然后，运行 `git init && git secret init`。这将初始化 `.gitsecret` 文件夹，然后运行 `git secret tell $email`，如果您希望其他用户解密密钥文件，则必须导入其 gpg 公钥，然后再次运行 `git secret tell $otheruseremailid`。现在您
```suggestion
git-secret 的工作方式如下。进入仓库中要加密文件的文件夹，然后，运行 `git init && git secret init`。这将初始化 `.gitsecret` 文件夹，然后运行 `git secret tell $email`，如果您希望其他用户解密密钥文件，则必须导入其 gpg 公钥，然后再次运行 `git secret tell $otheruseremailid`。现在您可以运行 `git secret add $secretfilename` 和 `git secret hide`，这将创建名为 `$secretfilename.secret` 的加密的密钥文件。
```

2019-11-23 02:16 UTC, donhui approved these changes
lgtm

2019-11-23 11:46 UTC, yJunS requested changes

2019-11-23 11:46 UTC, yJunS commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +现在，您可以提交主仓库了。git-secret 自动将 `$secretfile` 添加到 `.gitignore`，因此您只需提交 `$secretfile.secret` 文件。
`master` 感觉应该不用翻译吧？

2019-11-23 11:46 UTC, yJunS commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +1.导出gpg私钥。
中英文空格问题

2019-11-23 11:46 UTC, yJunS commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +4.在 Jenkins 流水线中使用添加的 gpg 私钥、所有者信任文件和密码短语。这里的"gpg-secret"、"gpg-trust" 和 "gpg-passphrase" 是添加 Jenkins 凭据时给出的 ID。
> 这里的"gpg-secret"

中英文空格问题

2019-11-24 15:45 UTC, zhaoying818 commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +现在，您可以提交主仓库了。git-secret 自动将 `$secretfile` 添加到 `.gitignore`，因此您只需提交 `$secretfile.secret` 文件。
master repo 不知道怎么翻译比较合适 :smile

2019-11-24 15:47 UTC, zhaoying818 commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +1.导出gpg私钥。
已经修正。thx

2019-11-24 15:48 UTC, zhaoying818 commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +4.在 Jenkins 流水线中使用添加的 gpg 私钥、所有者信任文件和密码短语。这里的"gpg-secret"、"gpg-trust" 和 "gpg-passphrase" 是添加 Jenkins 凭据时给出的 ID。
已经修正

2019-11-25 02:02 UTC, yJunS commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +现在，您可以提交主仓库了。git-secret 自动将 `$secretfile` 添加到 `.gitignore`，因此您只需提交 `$secretfile.secret` 文件。
翻译为 `master 分支库`是否可行？相对好理解一些

2019-11-25 11:29 UTC, zhaoying818 commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +现在，您可以提交主仓库了。git-secret 自动将 `$secretfile` 添加到 `.gitignore`，因此您只需提交 `$secretfile.secret` 文件。
我觉得可行

2019-11-25 11:29 UTC, zhaoying818 commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +现在，您可以提交主仓库了。git-secret 自动将 `$secretfile` 添加到 `.gitignore`，因此您只需提交 `$secretfile.secret` 文件。
或者仓库的master分支？

2019-11-25 11:30 UTC, zhaoying818 commented on articles/2019/11/2019-11-29-jenkins-cicd-with-git-secrets.md
> +现在，您可以提交主仓库了。git-secret 自动将 `$secretfile` 添加到 `.gitignore`，因此您只需提交 `$secretfile.secret` 文件。
```suggestion
现在，您可以提交 master 分支库了。git-secret 自动将 `$secretfile` 添加到 `.gitignore`，因此您只需提交 `$secretfile.secret` 文件。
```

2019-11-29 02:05 UTC, yJunS approved these changes
LGTM

2019-11-29 02:05 UTC, merged