[原创-2019-11-28] Release jcli v0.0.23
jenkins-infra/wechat pull request #268
Opened 2019-11-27 12:07 UTC by LinuxSuRen

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-11-27 14:01 UTC, donhui commented
封面图片，可不可以换成我之前用的 Jenkins CLI 图片：http://jenkins-zh.cn/wechat/articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins/jenkins-cli.png

2019-11-27 14:02 UTC, LinuxSuRen commented
> 封面图片，可不可以换成我之前用的 Jenkins CLI 图片：http://jenkins-zh.cn/wechat/articles/2019/11/2019-11-20-jenkins-cli-help-you-manage-jenkins/jenkins-cli.png

好主意!!!

2019-11-27 14:28 UTC, yJunS requested changes

2019-11-27 14:28 UTC, yJunS commented on articles/2019/11/2019-11-28-jcli-v0.0.23.md
> +如果，您好没有听说或者使用过 Jenkins CLI，欢迎阅读我们的官方文档，以及下面的 v0.0.23 版本更新内容。
您好没有听说 -> 您还没有听说

2019-11-27 15:05 UTC, donhui approved these changes

2019-11-28 02:22 UTC, yJunS approved these changes

2019-11-28 04:53 UTC, merged