[翻译-2019-12-11] Jenkins 健康检查顾问
jenkins-infra/wechat pull request #270
Opened 2019-12-06 09:30 UTC by wenjunzhangp

[翻译-2019-12-11] Jenkins 健康检查顾问

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2019/11/22/jenkins-health-advisor-by-cloudbees/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-12-08 15:08 UTC, zhaoying818 commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +* 您如何避免 “angry Jenkins” logo？
```suggestion
* 您如何避免臭名昭著的 “angry Jenkins” logo？
```

2019-12-08 16:06 UTC, zhaoying818 commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +在 [CloudBees](https://www.cloudbees.com/?utm_medium=blog&utm_source=jenkins.io&utm_campaign=cloudbees-jenkins-advisor-plugin)，我们拥有多年支持 [supporting our customers who are using Jenkins](https://www.clo
```suggestion
在 [CloudBees](https://www.cloudbees.com/?utm_medium=blog&utm_source=jenkins.io&utm_campaign=cloudbees-jenkins-advisor-plugin)，我们拥有多年[支持使用 Jenkins 的客户](https://www.cloudbees.com/products/cloudbees-jenkins-support/overview)的经验，其中包括基于 Jenkins 构建的专有产品，例如 [CloudBees Core](https://www.cloudbees.com/products/core/overview)。因此，我们的支持团队由拥有 Jenkins 知识的自动化专家组成，您在其他任何地方都无法获得。
```

2019-12-09 10:19 UTC, yJunS requested changes

2019-12-09 10:19 UTC, yJunS commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +* 您如何确保您的 master 或 agents 不会默默失败？您是否正在监视其日志？其所有内部组件？如果出现问题，您该如何解决？
> 您如何确保您的 master 或 agents 不会默默失败

应该是失效会更准确一些吧。指的应该是节点的能动性，而不是一个动作吧？

`您是否正在监视其日志？其所有内部组件？`  这里监控是不是好一些？  还有断句用顿号感觉更适当一些。在中文里，后半句并没有任何含义，应该跟前半句是连接的

2019-12-09 10:19 UTC, yJunS commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +* 您如何避免臭名昭著的 “angry Jenkins” logo？
避免出现，`logo` 感觉可以翻译的吧

2019-12-09 10:19 UTC, yJunS commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +在 [CloudBees](https://www.cloudbees.com/?utm_medium=blog&utm_source=jenkins.io&utm_campaign=cloudbees-jenkins-advisor-plugin)，我们拥有多年[支持使用 Jenkins 的客户](https://www.cloudbees.com/products/cloudbees-jen
`我们拥有多年[支持使用 Jenkins 的客户](https://www.cloudbees.com/products/cloudbees-jenkins-support/overview)的经验`
->
`我们拥有多年为[使用 Jenkins 的客户提供支持](https://www.cloudbees.com/products/cloudbees-jenkins-support/overview)的经验`

是不是好一些？

2019-12-09 10:19 UTC, yJunS commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +花几分钟时间阅读我们的[文档](https://docs.cloudbees.com/docs/admin-resources/latest/plugins/cloudbees-jenkins-advisor?utm_medium=blog&utm_source=jenkins.io&utm_campaign=cloudbees-jenkins-advisor-plugin)，发现服务，并随时通
> [Gitter](https://gitter.im/jenkinsci/jenkins)，[jenkinsci-users@googlegroups.com](https://groups.google.com/forum/#!forum/jenkinsci-users)

之间应该用顿号

2019-12-09 10:19 UTC, yJunS commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +* [CloudBees Jenkins Support](https://www.cloudbees.com/products/cloudbees-jenkins-support/overview)
显示名称是可以翻译的

2019-12-10 02:14 UTC, wenjunzhangp commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +* 您如何确保您的 master 或 agents 不会默默失败？您是否正在监视其日志？其所有内部组件？如果出现问题，您该如何解决？
我的想法是建议用问号，和原文保持一致

2019-12-10 04:20 UTC, yJunS commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +* 您如何确保您的 master 或 agents 不会默默失效？您是否正在监控其日志？其所有内部组件？如果出现问题，您该如何解决？
> 您是否正在监控其日志？其所有内部组件？

如果是使用问号的话，建议后面半句  加上`监控`

2019-12-10 04:20 UTC, yJunS commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +* 您如何避免出现 “Angry Jenkins” 商标？
logo 翻译为 `图标` 是不是好一些？

2019-12-11 01:49 UTC, LinuxSuRen requested changes
感谢提供译文，有些地方需要做下调整。

2019-12-11 01:49 UTC, LinuxSuRen commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +description: "Jenkins 开放了一项新的免费服务: Jenkins Health Advisor by CloudBees，我们将教您如何使用它并保持您的 masters 健康。"
描述不是一个完整的句子，不需要句号。另外，这个描述有歧义，建议调整为：
`CloudBees  推出了一项新的免费服务: Jenkins Health Advisor，帮助您保持 master 节点的健康`

CloudBees != Jenkins，所以不是 Jenkins 提供的服务

2019-12-11 01:49 UTC, LinuxSuRen commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +有帮助的链接：
翻译为`参考链接`会不会更好点？

2019-12-11 01:49 UTC, LinuxSuRen commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +经过多年的内部使用，我们决定与社区共享此服务，我们很高兴为 **每个 Jenkins 用户推出一项新的免费（如啤酒）服务**：[Jenkins Health Advisor by CloudBees](https://www.cloudbees.com/jenkins/health-advisor-plugin)。
建议去掉`（如啤酒）`，在我们的文化里，啤酒并不是免费的，也没有上下文。

2019-12-11 01:59 UTC, yJunS commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +经过多年的内部使用，我们决定与社区共享此服务，我们很高兴为 **每个 Jenkins 用户推出一项新的免费（如啤酒）服务**：[Jenkins Health Advisor by CloudBees](https://www.cloudbees.com/jenkins/health-advisor-plugin)。
我在 review 的时候，也感觉这块不太合适，可能对于很多人来说，不理解这块的意思。

2019-12-11 02:08 UTC, wenjunzhangp commented on articles/2019/12/2019-12-11-jenkins-health-advisor-by-cloudBees-is-here.md
> +经过多年的内部使用，我们决定与社区共享此服务，我们很高兴为 **每个 Jenkins 用户推出一项新的免费（如啤酒）服务**：[Jenkins Health Advisor by CloudBees](https://www.cloudbees.com/jenkins/health-advisor-plugin)。
我在翻译的时候，也不太懂这块的意思，是不是在外国人的文化里，啤酒是免费的...

2019-12-11 02:13 UTC, LinuxSuRen approved these changes

2019-12-11 02:57 UTC, yJunS approved these changes
LGTM

2019-12-11 02:57 UTC, merged

2019-12-11 06:16 UTC, yJunS commented
@wenjunzhangp 注意图片文件后缀，还有文件夹尽量都用小写

2019-12-11 07:17 UTC, yJunS commented
@wenjunzhangp 文章顺便可以在 cn.jenkins.io 上也发一下

2019-12-11 07:38 UTC, wenjunzhangp commented
@yJunS 收到下次注意，一会我在 `cn.jenkins.io` 也提个PR。