[翻译-2019-12-19] 使用 Docker 全自动构建 Java 应用
jenkins-infra/wechat pull request #272
Opened 2019-12-11 18:28 UTC by tomatofrommars

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://dzone.com/articles/full-build-automation-for-java-application-using-d)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-12-12 04:10 UTC, yJunS reviewed
建议将 commit 提交记录清理一下

2019-12-12 04:47 UTC, LinuxSuRen commented
> 建议将 commit 提交记录清理一下

这次肯定是清理不了了，下次再说吧。另外，主要的问题是，不应该使用你的 master 分支来提交 PR，每次都需要重新创建分支。

2019-12-12 08:08 UTC, tomatofrommars commented
> > 建议将 commit 提交记录清理一下
> 
> 这次肯定是清理不了了，下次再说吧。另外，主要的问题是，不应该使用你的 master 分支来提交 PR，每次都需要重新创建分支。

哦，那我关了重新提一个？

2019-12-12 08:09 UTC, LinuxSuRen commented
不用关闭，没关系的，合并的时候会压缩。

2019-12-12 08:10 UTC, tomatofrommars commented
> 不用关闭，没关系的，合并的时候会压缩。

好的

2019-12-12 15:09 UTC, donhui commented
图片路径需要去掉`2019-12-19-full-build-automation-for-java-application-using-docker/`
构建的时候会自动加上这个的

2019-12-12 16:12 UTC, tomatofrommars commented
> 图片路径需要去掉`2019-12-19-full-build-automation-for-java-application-using-docker/`
> 构建的时候会自动加上这个的

Done

2019-12-13 04:12 UTC, yJunS requested changes
非常感谢贡献文章，这里有一些需要讨论修改的地方

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +## 理解 Jenkins-complete
理解 -> 了解 
`理解`的意思感觉有些偏差

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +这是我们构建 Jenkins 镜像的核心仓库，它包含了所需的配置文件。我们通过 Jenkins 官方提供的 Docker 镜像启动 Jenkins 容器，然后完成一些动作，例如安装插件，创建用户等。
`例如安装插件，创建用户等` -> `例如安装插件、创建用户等`

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +安装好之后，我们会创建用来获取 Java 应用的 Github 凭据，还有推送镜像到 Dockerhub 的 Docker 凭据。最后，开始创建我们应用的流水线 job.
> 开始创建我们应用的流水线 job.

结尾的句号应该是全角的

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +这个过程很长，我们的目标是让所有这些事都自动执行。主仓库包含的文件和详细配置会用来创建镜像。当创建好的镜像启动运行以后，我们同时完成了以下这些动作：
个人感觉`自动执行`替换为`自动化`要好一些

`我们同时完成了以下这些动作` 这句话感觉有一点歧义，感觉像是我们手动去完成的，而不是自动完成的。并且可能跟原文中不完全一致，下面的分列项在原文中都是过去完成时的状态。

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +仔细观察上面的代码，我们可以看到一个 id 为“Github”的用户名以及加密后的密码。这个 id 很重要，我们会在后面的流水线中用到。
“Github” 在原文中是小写的，尽量还是以原文为主。前引号前和后引号后也建议加上空格

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +里创建一个名为“sample-maven-job”的 job, 这个文件包含了它的详细配置。
“sample-maven-job” 前后建议加空格

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +我们把这个 token 命名为 “MY-TOKEN”.
这里换行也没什么影响，不过没太明白意义是？

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +虽然，我们在容器里创建了 Jenkins 服务器和一个 job, 我们还需要一个触发器来触发整个自动构建。我喜欢下面的方法:
> 创建了 Jenkins 服务器

不是服务器吧？应该是服务才对

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +这个使得 Jenkins 以安静模式安装
这个使得 Jenkins 以安静模式安装 -> 这个使得 Jenkins 可以静默安装

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +同样，复制到`/usr/share/jenkins/ref/init.groovy.d/`的脚本会在服务器启动后被执行。
> `/usr/share/jenkins/ref/init.groovy.d/`

前后空格问题

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +这些说明很重要，它们在 Jenkins 家目录创建了一些用来存放配置文件的文件夹。`latest/`和`builds/1`存放的目录也需要与其 job 相对应。
此处以及下方还有一些空格问题，请一起修改一下

2019-12-13 04:12 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +另一件重要的事是定义环境。我定义了名为 `docker.io/jagadesh1982/sample` 的仓库，新制成的成品（jar 包）的名字也将遵循这个格式 `docker.io/jagadesh1982/sample:<version>`。如果你的镜像需要推送到 Dockerhub 的话，记住这一点是非常重要的。Dockerhub 希望你的镜像名按照 `docker.io/<user Na
> 新制成的成品（jar 包）的名字也将遵循这个格式

`artifact` 一般翻译为 `制品`
并且这句话好像与原文不完全相符，原文中是把镜像名称按后续规则定命名，这里体现的是将制品名。

2019-12-15 07:25 UTC, tomatofrommars commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +虽然，我们在容器里创建了 Jenkins 服务器和一个 job, 我们还需要一个触发器来触发整个自动构建。我喜欢下面的方法:
是的，其他地方我也一并改了

2019-12-15 08:06 UTC, tomatofrommars commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +另一件重要的事是定义环境。我定义了名为 `docker.io/jagadesh1982/sample` 的仓库，新制成的成品（jar 包）的名字也将遵循这个格式 `docker.io/jagadesh1982/sample:<version>`。如果你的镜像需要推送到 Dockerhub 的话，记住这一点是非常重要的。Dockerhub 希望你的镜像名按照 `docker.io/<user Na
All done.

2019-12-15 09:19 UTC, chowsGh commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +date: 2019-12-19
【疑问】这个时间是翻译的时间还是原文"by Jagadish Manchala · Jun. 21, 19 · DevOps Zone · Tutorial"的时间？
如果是原文的时间，应该是2019-06-21

2019-12-19 02:33 UTC, yJunS requested changes

2019-12-19 02:33 UTC, yJunS commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +
这块应该有丢失图片 `pipeline-view.png`

2019-12-19 03:33 UTC, tomatofrommars commented on articles/2019/12/2019-12-19-full-build-automation-for-java-application-using-docker.md
> +
加好了

2019-12-19 03:46 UTC, yJunS approved these changes
LGTM

2019-12-19 03:46 UTC, merged