[翻译-2019-12-23] Webhook 通用触发插件
jenkins-infra/wechat pull request #277
Opened 2019-12-16 04:22 UTC by wenjunzhangp

[翻译-2019-12-23] Webhook 通用触发插件

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-12-16 16:11 UTC, zhaoying818 commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +* 构建快照（如果需要的话，也可以发布）
pre release翻译为 预发布 更好一些吧

2019-12-16 16:14 UTC, zhaoying818 commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +如果开发人员习惯于在 Bitbucket 中像这样组织存储库，我们是否应该在 Jenkins 中以同样的方式组织它们？而且，如果他们浏览 Jenkins，是否应该不为每种功能（例如 `pull-request`，`snapshot` 和 `release`）找到一份构建任务？每个具有仅与该功能相关的参数的作业。我认同！像这样：
应该不为  --> 不应该为
是不是更好一些？

2019-12-16 16:16 UTC, zhaoying818 commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +Webhooks 通常在提供它们的服务中有据可查。观察看到：
观察看到   -->如
是否会更贴切一些？

2019-12-16 16:26 UTC, zhaoying818 commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +回购中提供了最新文档，我也有一个完整的示例，其中使用 `configuration-as-code` 实现了 GitLab。在这里查看存储库。
```suggestion
[仓库](https://github.com/jenkinsci/generic-webhook-trigger-plugin/)中提供了最新文档，并且有一个完整的示例，其中使用  `configuration-as-code`  实现了 GitLab。在[这里](https://github.com/tomasbjerre/jenkins-configuration-as-code-sandbox)查看仓库。
```

2019-12-16 16:29 UTC, zhaoying818 commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +有了这些规则，管道就可以完全通用，并且在存储库中不需要 Jenkinsfiles。由于某些原因，某些 git 存储库可能需要禁用测试用例。这可以通过允许存储库添加一个特殊文件，也就是 `jenkins-settings.json` 来解决，让基础架构发现其[内容并对其采取行动](https://github.com/tomasbjerre/jenkins-configuration-as-cod
pipeline 翻译为流水线

2019-12-16 16:33 UTC, zhaoying818 commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +* Jenkins 作业配置-使用[作业 DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki)。
Job 翻译为任务

2019-12-16 16:36 UTC, zhaoying818 commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +该插件不是很大，只是 webhook，`JSONPath/XPath` 和正则表达式之间的粘合剂。所有这些部分都已被很好地记录下来，我会尽力支持该插件。这是一个非常有据可查的解决方案！
```suggestion
该插件不是很大，只是 webhook、`JSONPath/XPath` 和正则表达式之间的粘合剂。所有这些部分都已被很好地记录下来，我会尽力维护该插件。这是一个非常有据可查的解决方案！
```

2019-12-17 03:37 UTC, yJunS requested changes

2019-12-17 03:37 UTC, yJunS commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +与 Jenkins 一起工作时，我经常遇到同样的问题：
> 与 Jenkins 一起工作时

这句话感觉不是很合适，感觉 `Jenkins` 像是一个人

2019-12-17 03:37 UTC, yJunS commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +## 代码复制和安全性
应该是 `代码重复` 吧？

2019-12-17 03:37 UTC, yJunS commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +* **代码复制和安全性**-每个存储库中的 `Jenkinsfiles`。
代码复制 -> 代码重复

2019-12-17 03:37 UTC, yJunS commented on articles/2019/12/2019-12-23-generic-webhook-trigger-plugin.md
> +我的解决方案几乎可以追溯到基本知识：我们有一个自动化服务器（Jenkins），我们想在外部 Webhooks 上触发它。我们想从该 Webhook 收集信息并将其提供给我们的构建。为了支持它，我创建了[通用 Webhook 触发器插件](https://plugins.jenkins.io/generic-webhook-trigger)。
我们有一个自动化服务器 -> 我们有一个自动化服务

2019-12-23 09:16 UTC, yJunS approved these changes

2019-12-23 09:16 UTC, merged