[翻译-2019-12-31] 使用 Jenkins 实现 CI/CD 多分支流水线
jenkins-infra/wechat pull request #280
Opened 2019-12-22 10:26 UTC by anxk

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://dzone.com/articles/implement-ci-for-multibranch-pipeline-in-jenkins)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-12-22 12:29 UTC, LinuxSuRen requested changes
感谢您贡献文章，因为多分支流水线已经有了本地化，建议对应的按钮、菜单使用对应的翻译。

2019-12-22 12:29 UTC, LinuxSuRen commented on articles/2019/12/2019-12-31-implement-cicd-for-multibranch-pipeline-in-jenkins.md
> +toc: false
why false?

2019-12-22 12:29 UTC, LinuxSuRen commented on articles/2019/12/2019-12-31-implement-cicd-for-multibranch-pipeline-in-jenkins.md
> +Jenkins 是一个持续集成服务器，用于从版本控制系统（VCS）中获取最新代码，然后对其进行构建、测试并将结果通知给开发人员。除了作为一个持续集成（CI）服务器之外，Jenkins 还可以做很多其它的事情。最初它被称为 Hudson，是川口浩辅（Kohsuke Kawaguchi）基于 Java 编写的一个开源项目，因此，在安装和运行 Jenkins 之前，首先需要安装 [Java 8](ht
从[linkedin](https://www.linkedin.com/in/kohsukekawaguchi/?locale=ja_JP)上看到，他的日文名字是`川口耕介`

2019-12-22 12:53 UTC, anxk commented on articles/2019/12/2019-12-31-implement-cicd-for-multibranch-pipeline-in-jenkins.md
> +Jenkins 是一个持续集成服务器，用于从版本控制系统（VCS）中获取最新代码，然后对其进行构建、测试并将结果通知给开发人员。除了作为一个持续集成（CI）服务器之外，Jenkins 还可以做很多其它的事情。最初它被称为 Hudson，是川口浩辅（Kohsuke Kawaguchi）基于 Java 编写的一个开源项目，因此，在安装和运行 Jenkins 之前，首先需要安装 [Java 8](ht
我改一下这里。

2019-12-22 12:55 UTC, anxk commented on articles/2019/12/2019-12-31-implement-cicd-for-multibranch-pipeline-in-jenkins.md
> +toc: false
我不确定这里要不要，参考了仓库中一些文章，并没有包含 toc，所以就设置 false 了，这里要改成 true 吗？

2019-12-22 12:59 UTC, anxk commented on articles/2019/12/2019-12-31-implement-cicd-for-multibranch-pipeline-in-jenkins.md
> +toc: false
另外，尽管多分支流水线已经有了本地化，但是考虑到文章叙述和图的内容一致，是否保持菜单和按钮等翻译保持原文更好一些。否则，是否需要重新对照原文进行截图？

2019-12-22 13:10 UTC, anxk commented on articles/2019/12/2019-12-31-implement-cicd-for-multibranch-pipeline-in-jenkins.md
> +Jenkins 是一个持续集成服务器，用于从版本控制系统（VCS）中获取最新代码，然后对其进行构建、测试并将结果通知给开发人员。除了作为一个持续集成（CI）服务器之外，Jenkins 还可以做很多其它的事情。最初它被称为 Hudson，是川口浩辅（Kohsuke Kawaguchi）基于 Java 编写的一个开源项目，因此，在安装和运行 Jenkins 之前，首先需要安装 [Java 8](ht
已修改。

2019-12-22 14:04 UTC, LinuxSuRen commented on articles/2019/12/2019-12-31-implement-cicd-for-multibranch-pipeline-in-jenkins.md
> +toc: false
toc 为 true 的话，构建完成后能看到对应的目录，因此，是需要设置为true的。
考虑到图的话，确实保留也是一个不错的选择。

2019-12-22 14:40 UTC, anxk commented on articles/2019/12/2019-12-31-implement-cicd-for-multibranch-pipeline-in-jenkins.md
> +toc: false
已修改 toc 值为 true；考虑到文章叙述和图的内容一致性，保持菜单和按钮等翻译与原文一致。

2019-12-22 15:25 UTC, yJunS reviewed
请确保 `management/contributors/` 下有对应的翻译者信息

2019-12-22 16:22 UTC, anxk commented
> 请确保 `management/contributors/` 下有对应的翻译者信息

好的，已添加对应文件。

2019-12-22 23:48 UTC, LinuxSuRen approved these changes

2019-12-31 01:03 UTC, merged

2020-01-09 01:10 UTC, LinuxSuRen commented
抱歉，之前忘记在公众号上发布，今天会发出来。