add new translation named welcome to matrix
jenkins-infra/wechat pull request #282
Opened 2019-12-24 12:59 UTC by 0N0thing

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [* ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2019/11/22/welcome-to-the-matrix/))
    - [* ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [* ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [* ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2019-12-24 15:57 UTC, yJunS requested changes
感谢贡献文章

PR 标题请按照[发布规则](https://github.com/jenkins-infra/wechat/blob/master/management/operators/README.md)来修改，日期建议至少延后一周。

文章也请按照翻译规范和文章编写格式进行修改

2019-12-25 00:09 UTC, LinuxSuRen commented
`欢迎来到矩阵` ，从这个标题看不出来说的是什么。如果没有合适的词，建议保持原文。

2019-12-25 01:04 UTC, 0N0thing commented
> `欢迎来到矩阵` ，从这个标题看不出来说的是什么。如果没有合适的词，建议保持原文。

那就是按照原标题命名是吗？blog的主要内容也是跟矩阵有关的，更准确来说像是“坐标系”。但是本身 `matrix` 的字面意思更准确来说是矩阵，所以从标题来说确实看起来不像是一篇介绍 `Jenkins` 的文章。那我就把标题修改成原文标题啦。

2019-12-25 01:11 UTC, LinuxSuRen commented
文中介绍的是流水线的矩阵特性，我们可以翻译成更加容易理解的，例如：欢迎使用流水线的矩阵特性。
欢迎来到的话，一般是描述一个地方，无法来到一个东西或者特性。

2019-12-25 01:14 UTC, 0N0thing commented
> 文中介绍的是流水线的矩阵特性，我们可以翻译成更加容易理解的，例如：欢迎使用流水线的矩阵特性。
> 欢迎来到的话，一般是描述一个地方，无法来到一个东西或者特性。

好的，了解。那么“欢迎使用流水线指令-矩阵”这样是否好点？因为 `matrix` 是 `Declaractive Pipeline` 指令的一部分。这样能突出是 `Pipeline` 的内容还能说明这个是一个其中的指令。不吝赐教 :D

2019-12-25 01:21 UTC, 0N0thing commented
> 感谢贡献文章
> 
> PR 标题请按照[发布规则](https://github.com/jenkins-infra/wechat/blob/master/management/operators/README.md)来修改，日期建议至少延后一周。
> 
> 文章也请按照翻译规范和文章编写格式进行修改

PR标题已将时间延后一周，文件内容我会再根据翻译规范和文章编写格式再次审阅并修改，感谢提醒。

2019-12-25 02:10 UTC, LinuxSuRen commented
12月31日已经有一篇文章了，我们每天只发一篇。另外，要避开周末、节假日等日期。

2019-12-25 02:39 UTC, 0N0thing commented
> 12月31日已经有一篇文章了，我们每天只发一篇。另外，要避开周末、节假日等日期。

好的，那就要明年了 :p 我再改下日期。

2019-12-31 03:17 UTC, yJunS requested changes

2019-12-31 03:17 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +## [单配置流水线](https://jenkins.io/blog/2019/11/22/welcome-to-the-matrix/#single-configuration-pipeline)
一般顶级标题我们会默认为2级标题，因为title会默认为1级标题，这个标题原文中也没有加链接，建议最好跟原文的格式保持一致，下方标题亦有相同情况

2019-12-31 03:17 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +# [欢迎使用流水线指令-矩阵](https://jenkins.io/blog/2019/11/22/welcome-to-the-matrix/)
这个标题在原文中好像不属于文章的正文，有标题就可以了

2019-12-31 03:17 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +声明式流水线1.5.0-beta1（可以从[ Jenkins 实验更新站点 ](https://updates.jenkins.io/experimental/)获取）添加了一个新的  `matrix` 部分，该部分能让我一次指定一个阶段列表，然后在多个配置上并行运行同一列表。让我们来看一看！
`验更新站点` 后面应该没有空格

2019-12-31 05:49 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +# [欢迎使用流水线指令-矩阵](https://jenkins.io/blog/2019/11/22/welcome-to-the-matrix/)
已删除该标题

2019-12-31 05:50 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +声明式流水线1.5.0-beta1（可以从[ Jenkins 实验更新站点 ](https://updates.jenkins.io/experimental/)获取）添加了一个新的  `matrix` 部分，该部分能让我一次指定一个阶段列表，然后在多个配置上并行运行同一列表。让我们来看一看！
已删除该文字后面的空格

2019-12-31 05:50 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +## [单配置流水线](https://jenkins.io/blog/2019/11/22/welcome-to-the-matrix/#single-configuration-pipeline)
已将标题修改为二级标题，并将文章中带有链接的url去除，只显示标题名称

2019-12-31 06:50 UTC, yJunS requested changes

2019-12-31 06:50 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +---
每个结束符后尽量空一行，否则会出现格式错乱的问题，如下图：
![image](https://user-images.githubusercontent.com/20575981/71612646-b5232400-2bdc-11ea-9db4-3867219b83d2.png)

2019-12-31 06:50 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +单配置流水线
这样是多余的？

2019-12-31 06:50 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +```
建议空行

2019-12-31 06:50 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +```
建议空行

2019-12-31 06:50 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +```
如上

2019-12-31 06:50 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +```
如上

2019-12-31 07:06 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +```
已在下一次pr中修正

2019-12-31 07:06 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +```
已在下一次pr中修正

2019-12-31 07:06 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +```
已在下一次pr中修正

2019-12-31 07:06 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +```
已在下一次pr中修正

2019-12-31 07:07 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +单配置流水线
已删除该行，在格式修正的时候忘记删除了，抱歉

2019-12-31 07:07 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +---
已在每个结束附后添加换行，格式已在我自己的fork上进行了查看确认是换行的了，已提pr

2020-01-08 13:52 UTC, LinuxSuRen commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +- [ Jenkins 实验更新中心](https://updates.jenkins.io/experimental/)
Jenkins 前不需要再有空格了，前面什么内容都没有。
`实验更新中心`建议修改为`实验性更新中心`，不然可能会有歧义。

2020-01-08 13:52 UTC, LinuxSuRen commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +- [使用 Jenkins 实验更新中心](https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/#using-the-experimental-update-center)
同上

2020-01-08 14:48 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +- [使用 Jenkins 实验更新中心](https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/#using-the-experimental-update-center)
内容已做修改并提交pr，还有文章开头有一处也需要修改，都修改完毕

2020-01-08 14:48 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +- [ Jenkins 实验更新中心](https://updates.jenkins.io/experimental/)
内容已做修改并提交pr，还有文章开头有一处也需要修改，都修改完毕

2020-01-08 15:29 UTC, LinuxSuRen approved these changes
LGTM

2020-01-09 03:33 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +## 重要
这块在原文中应该是声明。不是标题

2020-01-09 03:33 UTC, yJunS commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +在[ DevOps World | Jenkins World 2019](https://www.cloudbees.com/devops-world/lisbon) “[声明式流水线2019：知识点，技巧，以及接下来的事情](https://sched.co/UeQe)”中加入我。我会回顾过去的一年有哪些加入到了流水线（包括“矩阵”）以及探讨一些关于流水线下一步走向的想法。
> 在[ DevOps World | Jenkins World 2019](https://www.cloudbees.com/devops-world/lisbon) “[声明式流水线2019：知识点，技巧，以及接下来的事情](https://sched.co/UeQe)”中加入我

这句话看起来不太通顺的样子，`快来加入我的...的...` 应该更具有可读性一些

2020-01-10 13:26 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +## 重要
麻烦问下，这个地方简单加粗可以吗？

2020-01-10 13:26 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +## 重要
> 这块在原文中应该是声明。不是标题

麻烦问下，这个地方简单加粗可以吗？

2020-01-10 13:27 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +在[ DevOps World | Jenkins World 2019](https://www.cloudbees.com/devops-world/lisbon) “[声明式流水线2019：知识点，技巧，以及接下来的事情](https://sched.co/UeQe)”中加入我。我会回顾过去的一年有哪些加入到了流水线（包括“矩阵”）以及探讨一些关于流水线下一步走向的想法。
> > 在[ DevOps World | Jenkins World 2019](https://www.cloudbees.com/devops-world/lisbon) “[声明式流水线2019：知识点，技巧，以及接下来的事情](https://sched.co/UeQe)”中加入我
> 
> 这句话看起来不太通顺的样子，`快来加入我的...的...` 应该更具有可读性一些
收到，这个地方我再组织下语言，上个问题确认完毕后下个pr做修改。

2020-01-11 00:55 UTC, LinuxSuRen commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +## 重要
和原文类似的就可以了，你可以找找markdown也有类似与提醒的用法。

2020-01-11 13:18 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +## 重要
> 和原文类似的就可以了，你可以找找markdown也有类似与提醒的用法。

因为原文还有另一处这样的文本，我都一致按照文字加粗处理了，望采纳

2020-01-11 13:19 UTC, 0N0thing commented on articles/2019/12/2019-12-24-Welcome-to-the-Matrix.md
> +在[ DevOps World | Jenkins World 2019](https://www.cloudbees.com/devops-world/lisbon) “[声明式流水线2019：知识点，技巧，以及接下来的事情](https://sched.co/UeQe)”中加入我。我会回顾过去的一年有哪些加入到了流水线（包括“矩阵”）以及探讨一些关于流水线下一步走向的想法。
> > 在[ DevOps World | Jenkins World 2019](https://www.cloudbees.com/devops-world/lisbon) “[声明式流水线2019：知识点，技巧，以及接下来的事情](https://sched.co/UeQe)”中加入我
> 
> 这句话看起来不太通顺的样子，`快来加入我的...的...` 应该更具有可读性一些

请查看新提pr对该处的翻译是否准确，谢谢

2020-01-12 09:54 UTC, yJunS reviewed
文章中最好添加一张封面图片。在规范中有规定

2020-01-12 11:03 UTC, LinuxSuRen commented
是的，微信公众号里必须要有一个封面

2020-01-12 11:47 UTC, 0N0thing commented
> 文章中最好添加一张封面图片。在规范中有规定

收到，我待会按照要求我添加一张图片上去

2020-01-12 11:47 UTC, 0N0thing commented
> 是的，微信公众号里必须要有一个封面

好的，抽时间我添加一张封面图片上去

2020-01-13 00:47 UTC, LinuxSuRen commented
@0N0thing 封面图片太大了，这样会导致该仓库快速变大。这里有文章中对图片的规定https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md#%E5%9B%BE%E7%89%87
PR 模板也有对应[文章格式要求的链接](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)

2020-01-13 01:05 UTC, 0N0thing commented
> @0N0thing 封面图片太大了，这样会导致该仓库快速变大。这里有文章中对图片的规定https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md#%E5%9B%BE%E7%89%87
> PR 模板也有对应[文章格式要求的链接](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)

收到，我看到图片分辨率是200*200以上，没有注意文件大小，我再修改下

2020-01-13 01:34 UTC, LinuxSuRen approved these changes

2020-01-13 01:38 UTC, 0N0thing commented
> @0N0thing 封面图片太大了，这样会导致该仓库快速变大。这里有文章中对图片的规定https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md#%E5%9B%BE%E7%89%87
> PR 模板也有对应[文章格式要求的链接](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)

对了，我看了一下，如果我的pr格式是20-01-07的话我的文章应该放在20/01的目录下才对，麻烦看下放在这个地方是否合适，如果不合适我再把目录重新改下，谢谢

2020-01-13 01:40 UTC, LinuxSuRen commented
这块确实遗留了，后续的用流水线来校验。可以都写成今天 2020-01-13

2020-01-13 01:43 UTC, 0N0thing commented
> 这块确实遗留了，后续的用流水线来校验。可以都写成今天 2020-01-13

那我提交的目录还需要换吗？还是说保留当前的目录不变只是修改下文件名？

2020-01-13 01:50 UTC, LinuxSuRen commented
把目录、文件名称都修改了吧

2020-01-13 01:51 UTC, 0N0thing commented
> 把目录、文件名称都修改了吧

好的，我这边重新换一下

2020-01-13 09:23 UTC, yJunS approved these changes
lgtm

2020-01-13 09:26 UTC, merged