[翻译-2020-02-10] WebSocket
jenkins-infra/wechat pull request #290
Opened 2020-02-05 09:13 UTC by wenjunzhangp

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2020/02/02/web-socket/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2020-02-06 01:11 UTC, LinuxSuRen requested changes
感谢提供译稿，有一些小问题，得调整下。

2020-02-06 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-10-webSocket.md
> +我很高兴地提出报告，[JEP-222](https://github.com/jenkinsci/jep/blob/master/jep/222/README.adoc) 从 [2.217](https://jenkins.io/changelog/#v2.217) 开始每周登陆 Jenkins。此改进为 Jenkins 带来了实验性的 WebSocket 支持，可在连接入站代理程序或运行 CL
`JEP-222 has landed in Jenkins weeklies, starting in 2.217.`

我的理解是 JEP-222 从 Jenkins 每周更新版开始落地

2020-02-06 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-10-webSocket.md
> +我很高兴地提出报告，[JEP-222](https://github.com/jenkinsci/jep/blob/master/jep/222/README.adoc) 从 [2.217](https://jenkins.io/changelog/#v2.217) 开始每周登陆 Jenkins。此改进为 Jenkins 带来了实验性的 WebSocket 支持，可在连接入站代理程序或运行 CL
`HTTP（S）`

这里应该使用英文标点符号。

2020-02-06 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-10-webSocket.md
> +尽管 Jenkins 的许多用户都可以受益，但实施该系统对 CloudBees 尤为重要，因为 [现代云平台上的 CloudBees Core](https://docs.cloudbees.com/docs/cloudbees-core/latest/)（即在 Kubernetes 上运行）如何配置网络。当管理员希望将入站（以前称为“JNLP”）外部代理连接到 Jenkins 主服务器（例如在
`implementing` 在这里是否为实现的意思呢？

2020-02-06 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-10-webSocket.md
> +尽管 Jenkins 的许多用户都可以受益，但实施该系统对 CloudBees 尤为重要，因为 [现代云平台上的 CloudBees Core](https://docs.cloudbees.com/docs/cloudbees-core/latest/)（即在 Kubernetes 上运行）如何配置网络。当管理员希望将入站（以前称为“JNLP”）外部代理连接到 Jenkins 主服务器（例如在
`troubleshoot` 是调试的意思

2020-02-06 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-10-webSocket.md
> +使用 WebSocket，现在可以在存在反向代理的情况下更简单地连接入站代理：如果 HTTP（S）端口已在提供流量，则大多数代理将允许 WebSocket 连接而无需其他配置。可以在代理配置中启用 WebSocket 模式，并且即将推出 [Kubernetes 插件](https://plugins.jenkins.io/kubernetes/)中对基于 Pod 的代理的支持。您将需要一个[代理
`HTTP（S）` 同样的问题

2020-02-06 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-10-webSocket.md
> +使用 WebSocket，现在可以在存在反向代理的情况下更简单地连接入站代理：如果 HTTP（S）端口已在提供流量，则大多数代理将允许 WebSocket 连接而无需其他配置。可以在代理配置中启用 WebSocket 模式，并且即将推出 [Kubernetes 插件](https://plugins.jenkins.io/kubernetes/)中对基于 Pod 的代理的支持。您将需要一个[代理
`代理版本 4.0 ` 翻译为 4.0或更高版本的代理是否会好一点

2020-02-06 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-10-webSocket.md
> +已经针对 Kubernetes 实现示例（包括 OpenShift）对 WebSocket 代码进行了测试，但是很可能仍然存在一些错误和局限性，并且尚未测试重构建负载下代理的可伸缩性。暂时将此功能视为 Beta 版，并让我们了解其工作原理！
`bugs` 建议不要翻译，或者是`缺陷`

2020-02-06 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-10-webSocket.md
> +我很高兴地提出报告，[JEP-222](https://github.com/jenkinsci/jep/blob/master/jep/222/README.adoc) 从 [2.217](https://jenkins.io/changelog/#v2.217) 开始每周登陆 Jenkins。此改进为 Jenkins 带来了实验性的 WebSocket 支持，可在连接入站代理程序或运行 CL
封面图片应该在文章的最前面

2020-02-08 09:54 UTC, LinuxSuRen approved these changes
LGTM

2020-02-08 12:00 UTC, yJunS requested changes

2020-02-08 12:00 UTC, yJunS commented on articles/2020/02/2020-02-10-webSocket.md
> +我很高兴地提出报告，[JEP-222](https://github.com/jenkinsci/jep/blob/master/jep/222/README.adoc) 从 Jenkins 每周更新版开始落地。此改进为 Jenkins 带来了实验性的 WebSocket 支持，可在连接入站代理程序或运行 CLI 时使用。WebSocket 协议允许通过 HTTP（S）端口进行双向流式通信.
感觉`双向流式通信`有点看不太明白，建议直接翻译为`双向通信`或者`双向交互式通信`

2020-02-08 12:00 UTC, yJunS commented on articles/2020/02/2020-02-10-webSocket.md
> +尽管 Jenkins 的许多用户都可以受益，但实现该系统对 CloudBees 尤为重要，因为 [现代云平台上的 CloudBees Core](https://docs.cloudbees.com/docs/cloudbees-core/latest/)（即在 Kubernetes 上运行）如何配置网络。当管理员希望将入站（以前称为“JNLP”）外部代理连接到 Jenkins 主服务器（例如在
`群集` -> `集群`

2020-02-08 12:00 UTC, yJunS commented on articles/2020/02/2020-02-10-webSocket.md
> +使用 WebSocket，现在可以在存在反向代理的情况下更简单地连接入站代理：如果 HTTP（S）端口已在提供流量，则大多数代理将允许 WebSocket 连接而无需其他配置。可以在代理配置中启用 WebSocket 模式，并且即将推出 [Kubernetes 插件](https://plugins.jenkins.io/kubernetes/)中对基于 Pod 的代理的支持。您将需要一个[ 4
`映像` -> `镜像`

2020-02-09 09:20 UTC, LinuxSuRen approved these changes

2020-02-09 22:27 UTC, merged