[翻译-2020-02-09] Jenkins 创始人 Kohsuke 的新篇章
jenkins-infra/wechat pull request #291
Opened 2020-02-05 10:05 UTC by zhaoying818

<!-- 
Comment:
[类型-文章排期] 标题
请仔细阅读这里的描述，我们只会 Review 符合描述的 PR

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2020/01/23/a-new-chapter-for-kohsuke/#a-new-chapter-for-kohsuke)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [x] 维护

2020-02-06 03:09 UTC, donhui commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +description: "Jenkins 创始人 Kohsuke 的新篇章"
建议 description 和 title 不一样

2020-02-06 03:16 UTC, yJunS requested changes

2020-02-06 03:16 UTC, yJunS commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +2020 年对我来说将是变化的一年。在 1 月底，我将正式退出 Jenkins，将我在 [CloudBees](https://www.cloudbees.com/) 的角色转换为顾问，并将注意力转向我的[新创业公司](https://launchableinc.com/)。这篇文章的其余部分将结合这种过渡的背景，如果您没有与我紧密合作，这可能会令您惊讶。
变化 -> 转变
可能更好一些

2020-02-06 03:16 UTC, yJunS commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +Jenkins 之旅充满神奇，而且从未间断。我非常喜欢这一切，尤其是与造就 Jenkins 如今成就的世界各地的用户会面与交流。作为项目的创建者，在某个时候，我开始想如何将火炬传递给下一任领导者，如何使人们继续推动它前进。如今，由于有了 CloudBees 和社区，新一代的才华横溢、有才干的领导者正在热情地推动事情向前发展，这真令人高兴。例如，[新选举的董事会成员](https://jenkin
`folks` 翻译为 `乡亲们` 感觉有点不太合适

2020-02-06 03:20 UTC, donhui commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +最后，即使离开 CloudBees 不再作为其一名全职员工，也并没有完全离开，我将继续作为 CloudBees 的顾问，我仍然在情感和财务上都对 CloudBees 进行了大量投资。我仍然是狂热的粉丝，我会继续为他们加油，只不过是在默默观望。Jenkins 也一样，我仍然在董事会中，以确保连续性。我的主席任期将于 3 月届满，但我仍在[持续交付基金会](https://cd.foundation
我的主席任期将于 3 月届满，但我仍在[持续交付基金会](https://cd.foundation/)的[技术监督委员会](https://github.com/cdfoundation/toc)任职。
这里我感觉应该翻译成：
我仍在[持续交付基金会](https://cd.foundation/)的[技术监督委员会](https://github.com/cdfoundation/toc)任职，虽然我的主席任期将于 3 月届满。

2020-02-06 03:20 UTC, zhaoying818 commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +description: "Jenkins 创始人 Kohsuke 的新篇章"
```suggestion
description: "Jenkins 创始人 Kohsuke 即将退出 Jenkins，并投身于一个新的创业公司 Launchable "
```

2020-02-06 03:22 UTC, zhaoying818 commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +2020 年对我来说将是变化的一年。在 1 月底，我将正式退出 Jenkins，将我在 [CloudBees](https://www.cloudbees.com/) 的角色转换为顾问，并将注意力转向我的[新创业公司](https://launchableinc.com/)。这篇文章的其余部分将结合这种过渡的背景，如果您没有与我紧密合作，这可能会令您惊讶。
ok。

2020-02-06 03:23 UTC, zhaoying818 commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +Jenkins 之旅充满神奇，而且从未间断。我非常喜欢这一切，尤其是与造就 Jenkins 如今成就的世界各地的用户会面与交流。作为项目的创建者，在某个时候，我开始想如何将火炬传递给下一任领导者，如何使人们继续推动它前进。如今，由于有了 CloudBees 和社区，新一代的才华横溢、有才干的领导者正在热情地推动事情向前发展，这真令人高兴。例如，[新选举的董事会成员](https://jenkin
追随者？这个如何？

2020-02-06 03:24 UTC, zhaoying818 commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +最后，即使离开 CloudBees 不再作为其一名全职员工，也并没有完全离开，我将继续作为 CloudBees 的顾问，我仍然在情感和财务上都对 CloudBees 进行了大量投资。我仍然是狂热的粉丝，我会继续为他们加油，只不过是在默默观望。Jenkins 也一样，我仍然在董事会中，以确保连续性。我的主席任期将于 3 月届满，但我仍在[持续交付基金会](https://cd.foundation
ok

2020-02-06 03:26 UTC, donhui commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +Jenkins 之旅充满神奇，而且从未间断。我非常喜欢这一切，尤其是与造就 Jenkins 如今成就的世界各地的用户会面与交流。作为项目的创建者，在某个时候，我开始想如何将火炬传递给下一任领导者，如何使人们继续推动它前进。如今，由于有了 CloudBees 和社区，新一代的才华横溢、有才干的领导者正在热情地推动事情向前发展，这真令人高兴。例如，[新选举的董事会成员](https://jenkin
伙伴？

2020-02-06 03:27 UTC, zhaoying818 commented on articles/2020/02/2020-02-09-a-new-chapter-for-kohsuke.md
> +Jenkins 之旅充满神奇，而且从未间断。我非常喜欢这一切，尤其是与造就 Jenkins 如今成就的世界各地的用户会面与交流。作为项目的创建者，在某个时候，我开始想如何将火炬传递给下一任领导者，如何使人们继续推动它前进。如今，由于有了 CloudBees 和社区，新一代的才华横溢、有才干的领导者正在热情地推动事情向前发展，这真令人高兴。例如，[新选举的董事会成员](https://jenkin
伙伴 这个我觉得不错

2020-02-06 03:29 UTC, donhui approved these changes
lgtm

2020-02-08 09:56 UTC, LinuxSuRen commented
把该文章调整到12日发布吧，上面的[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)也有描述。

2020-02-10 01:54 UTC, zhaoying818 commented
> 
> 
> 把该文章调整到12日发布吧，上面的[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)也有描述。

已经重新提交，调整到12日

2020-02-10 01:58 UTC, LinuxSuRen commented
换行是不是出了问题
![image](https://user-images.githubusercontent.com/1450685/74115766-a1130f00-4beb-11ea-9de9-aff3161f27d1.png)

2020-02-10 02:16 UTC, LinuxSuRen approved these changes

2020-02-10 02:17 UTC, zhaoying818 commented
> 换行是不是出了问题
> ![image](https://user-images.githubusercontent.com/1450685/74115766-a1130f00-4beb-11ea-9de9-aff3161f27d1.png)

果然是出了问题，本地的编辑器有点问题，已经修复。谢谢

2020-02-12 01:35 UTC, merged