Translate article "happy second birthday jenkins x"
jenkins-infra/wechat pull request #292
Opened 2020-02-06 09:30 UTC by XiongKezhi

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2020-02-07 02:21 UTC, zhaoying818 commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +description: Jenkins 2019 年终回顾
应该是 Jenkins X 2019 年终回顾

2020-02-07 04:49 UTC, XiongKezhi commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +description: Jenkins 2019 年终回顾
谢谢，已更正

2020-02-07 10:48 UTC, zhaoying818 commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +keywords:
这里的tag1 tag2 和 tag3可以不要吧

2020-02-07 10:50 UTC, LinuxSuRen commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +keywords:
是的

2020-02-07 13:30 UTC, XiongKezhi commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +keywords:
那完全不使用tag吗？

2020-02-07 13:43 UTC, LinuxSuRen commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +keywords:
意思这样的：
```
tags:
- jenkins-x
- ci
- cd
```

2020-02-07 13:49 UTC, LinuxSuRen commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +-  jenkins-x
有个多余的空格？

2020-02-07 13:54 UTC, XiongKezhi commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +-  jenkins-x
抱歉，直接在网页上修改的没有注意到。已经修改了，在这之后的一个[commit-557f6e](https://github.com/jenkins-infra/wechat/pull/292/commits/557f6e2a04d04ff3a71c0baf602793c244a6eda8)

2020-02-07 13:55 UTC, LinuxSuRen commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +-  jenkins-x
it's ok

2020-02-07 13:55 UTC, LinuxSuRen commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +-  jenkins-x
it's ok

2020-02-08 10:06 UTC, LinuxSuRen approved these changes
LGTM

2020-02-08 10:06 UTC, LinuxSuRen commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +translator: 熊科智
这里我们使用 GitHub ID 作为标示，[在这里](https://github.com/jenkins-infra/wechat/tree/master/management/contributors)记录译者的信息。

2020-02-08 13:30 UTC, yJunS requested changes
图片路径请参照其他文章格式填写，以下的路径可能会导致无法正常读取。图片的命名：字母建议也使用小写字母

2020-02-09 14:46 UTC, donhui reviewed
有两处小错误，麻烦修正下～

2020-02-09 14:46 UTC, donhui commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +当 Jenkins X 开始它的 serverless jenkins 旅程时，它选择了使用 [Prow](https://github.com/kubernetes/test-infra/tree/master/prow)，一个用于 Github 事件和 ChatOps 的事件处理器。Prow 被 Kubernetes 项目用于构建所有的仓库，初次以外，它还包含了一个强大的 webhook 事
初次以外-->除此以外

2020-02-09 14:46 UTC, donhui commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +在 2018 年的后半年，Jenkins X 开始了一趟提供 Serverless Jenkins 与仅在需要时运行流水线引擎的旅程。这种流水线引擎基于 knative build-pipeline 项目，该项目进化成为了受到 Jenkins 和 Jenkins X 社区众多帮助与热爱的 Tekton 。[Jenkins X 项目在 2019 的 2 月完成了与 Tekton 的初次集成](ht
KuBurnes 本地-->kubernetes 原生

2020-02-12 12:19 UTC, XiongKezhi commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +当 Jenkins X 开始它的 serverless jenkins 旅程时，它选择了使用 [Prow](https://github.com/kubernetes/test-infra/tree/master/prow)，一个用于 Github 事件和 ChatOps 的事件处理器。Prow 被 Kubernetes 项目用于构建所有的仓库，初次以外，它还包含了一个强大的 webhook 事
已修改~ 感谢审阅！

2020-02-12 12:20 UTC, XiongKezhi commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +在 2018 年的后半年，Jenkins X 开始了一趟提供 Serverless Jenkins 与仅在需要时运行流水线引擎的旅程。这种流水线引擎基于 knative build-pipeline 项目，该项目进化成为了受到 Jenkins 和 Jenkins X 社区众多帮助与热爱的 Tekton 。[Jenkins X 项目在 2019 的 2 月完成了与 Tekton 的初次集成](ht
已修改！

2020-02-12 12:22 UTC, XiongKezhi commented on articles/2020/02/2020-02-17-happy-second-birthday-jenkins-x.md
> +translator: 熊科智
已修改

2020-02-12 12:37 UTC, donhui approved these changes

2020-02-16 01:25 UTC, LinuxSuRen approved these changes

2020-02-16 01:25 UTC, merged