[翻译-2020-02-18] 2019年 Google 编程之夏活动报告
jenkins-infra/wechat pull request #293
Opened 2020-02-11 12:36 UTC by 0N0thing

- [] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2020/01/29/gsoc-report/#google-summer-of-code-2019-report)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [] 维护

2020-02-11 13:17 UTC, 0N0thing commented
操作问题导致我第一篇翻译的文章的格式我改了一下我一并提交了，就只是第一行的那个空行的格式问题我做了修改，如果需要加的话我另外加上。我忘记了这个地方要不要加空行了。

2020-02-14 16:43 UTC, yJunS requested changes
标点符号很多都有问题，要使用半角的标点符号，用全角会有问题的

2020-02-15 00:42 UTC, LinuxSuRen requested changes
先调整下吧，这次 PR 里包含了无关的内容，每次 PR 都只能包含一个相关内容。你可以参考这里的指导 https://jenkins-zh.cn/about/branching-strategy/

2020-02-15 00:43 UTC, LinuxSuRen commented
> 题导致我第一篇翻译的文章的格式我改了一下我一并提交了，就只是第一行的那个空行的格式问题我做了修改，如果需要加的话我另外加上。我忘记了这个地方要不要加

不要使用master分支来提交，每次都新建一个分支来修改。

2020-02-15 04:11 UTC, 0N0thing commented
> 标点符号很多都有问题，要使用半角的标点符号，用全角会有问题的

收到，我处理下标点问题。

2020-02-15 04:12 UTC, 0N0thing commented
> > 题导致我第一篇翻译的文章的格式我改了一下我一并提交了，就只是第一行的那个空行的格式问题我做了修改，如果需要加的话我另外加上。我忘记了这个地方要不要加
> 
> 不要使用master分支来提交，每次都新建一个分支来修改。

我重新fork了一次，然后我再提pr吧

2020-02-15 05:01 UTC, closed without merging