[翻译-2020.02.21]使用容器化和 Docker 实现 DevOps 的基础知识
jenkins-infra/wechat pull request #295
Opened 2020-02-14 13:16 UTC by zhaoying818

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://dzone.com/articles/the-abc-of-devops-implementation-with-containeriza)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2020-02-15 01:11 UTC, LinuxSuRen requested changes
有点小问题需要调整

2020-02-15 01:11 UTC, LinuxSuRen commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +# 什么是容器化？
一级标题应该是 `##` ，这里有描述 https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md

2020-02-15 12:24 UTC, zhaoying818 commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +# 什么是容器化？
ok，已经修复

2020-02-17 02:48 UTC, yJunS requested changes

2020-02-17 02:48 UTC, yJunS commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +DevOps 在IT行业中风靡一时。[维基百科](https://en.wikipedia.org/wiki/DevOps)中阐述 DevOps 是将软件开发（Dev）和信息技术维护（Ops）结合在一起的一组实践，旨在缩短系统开发生命周期并提供高质量的持续交付。 DevOps普及的主要原因是，它使企业可以比传统软件开发方法更快地开发和改进产品。
`IT` 前后以及 `DevOps` 后面都空格问题

2020-02-17 02:48 UTC, yJunS commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +*你可能感兴趣：[Docker 和 DevOps：开发有状态的应用程序并在Docker中进行部署](https://dzone.com/articles/docker-and-devops-developing-state-full-applicatio)*
`Docker ` 前后空格问题

2020-02-17 02:48 UTC, yJunS commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +像 [AWS ECS](https://dzone.com/articles/deploying-an-aws-ecs-task-using-containers-from-ec) 一样，DevOps 和 Docker 镜像管理技术使软件开发人员可以轻松地进行 IT 运营，共享软件以及彼此协作，并提高生产力。除了鼓励开发人员一起工作之外，他们还成功地消除了以前影响应用程序的不同工作环境之间的冲突
中英文空格问题

2020-02-17 02:48 UTC, yJunS commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +让我们更深入地研究容器化，它的好处，它的工作原理，选择容器化工具的方式以及它如何胜过虚拟机（VM）的使用。
`它的好处，它的工作原理，选择容器化工具的方式` 之间用顿号应该更合适一些

2020-02-17 02:48 UTC, yJunS commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +[Docker](https://www.docker.com) 已经成为 IT 行业中的一个流行术语。 Docker 可以定义为一个开源软件平台，它提供了一种在容器内构建、测试、保护和部署应用程序的简化方法。 Docker 鼓励软件开发人员与云、Linux 和 Windows 操作系统进行协作，以轻松，快速地交付服务。
`以轻松，快速地交付服务` 感觉逗号改为顿号好一些

2020-02-17 02:48 UTC, yJunS commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +像 [AWS ECS](https://dzone.com/articles/deploying-an-aws-ecs-task-using-containers-from-ec) 一样，DevOps 和 Docker 镜像管理技术使软件开发人员可以轻松地进行 IT 运营，共享软件以及彼此协作，并提高生产力。除了鼓励开发人员一起工作之外，他们还成功地消除了以前影响应用程序的不同工作环境之间的冲突
`可以轻松地进行 IT 运营，共享软件以及彼此协作` 中间用顿号感觉好一些

2020-02-17 02:48 UTC, yJunS commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +- **[Dockerfile](https://dzone.com/articles/a-beginners-guide-to-the-dockerfile)** – A text file containing instructions on how to build a Docker image.
这段没有进行翻译？

2020-02-17 02:48 UTC, yJunS commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +- **Docker企业版（EE）** – 用于Linux和Windows开发的另一套工具。
中英文空格问题

2020-02-17 04:37 UTC, zhaoying818 commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +- **[Dockerfile](https://dzone.com/articles/a-beginners-guide-to-the-dockerfile)** – A text file containing instructions on how to build a Docker image.
> 
> 
> 这段没有进行翻译？

漏了，已经补充

2020-02-17 07:09 UTC, donhui commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +#### 4. 更快的可扩展性
更快的可扩展性-->更快的可伸缩性
正文同样

2020-02-17 15:36 UTC, zhaoying818 commented on articles/2020/02/2020-02-21-the-abc-of-devops-implementation-with-containerization-and-docker.md
> +#### 4. 更快的可扩展性
ok

2020-02-21 01:12 UTC, LinuxSuRen approved these changes

2020-02-21 01:12 UTC, merged