[翻译-2020-02-18] 2019 年 Google 编程之夏活动报告
jenkins-infra/wechat pull request #296
Opened 2020-02-15 05:00 UTC by 0N0thing

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2020/01/29/gsoc-report/#google-summer-of-code-2019-report)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2020-02-15 05:02 UTC, 0N0thing commented
之前pr中的问题已做修改，请各位查看该pr中提交的内容

2020-02-15 12:29 UTC, zhaoying818 commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +date：2020-02-06
date应该使翻译稿要发布或者预发布的日期，即2020-02-18

2020-02-15 13:55 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +date：2020-02-06
已修改

2020-02-16 23:35 UTC, LinuxSuRen requested changes
感谢提供译稿，不过发现有几个小问题

2020-02-16 23:35 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年成功完成了 5 个 GSoC 课题：[角色策略插件性能优化](https://jenkins.io/projects/gsoc/2019/role-strategy-performance)，[插件安装管理 CLI 工具/库](https://jenkins.io/projects/gsoc/2019/plugin-installation-manager-tool-cli)，[运行时间插件
`working-hours`翻译成`运行时间`的话，不容易理解，建议保持原文。

2020-02-16 23:35 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +## 运行时间插件 - UI 优化
同上

2020-02-16 23:35 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线的制品提升插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
`promotion`虽然是提升的意思，但在这里还是会让人感觉困惑

2020-02-17 06:51 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线的制品提升插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
> `promotion`虽然是提升的意思，但在这里还是会让人感觉困惑

这个插件我看是要在流水线上进行更好的兼容，如果按照这个意思的话就命名为 “在 Jenkins 流水线上优化制品插件”是否可以？

2020-02-17 06:54 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线的制品提升插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
promotion 应该指的是制品在多个环境里的*升级*的意思，例如：从staging环境升级到int环境，保留英文的话，感觉会好一些。

2020-02-17 07:00 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年成功完成了 5 个 GSoC 课题：[角色策略插件性能优化](https://jenkins.io/projects/gsoc/2019/role-strategy-performance)，[插件安装管理 CLI 工具/库](https://jenkins.io/projects/gsoc/2019/plugin-installation-manager-tool-cli)，[运行时间插件
> `working-hours`翻译成`运行时间`的话，不容易理解，建议保持原文。

已修改为保持原文

2020-02-17 07:00 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +## 运行时间插件 - UI 优化
> 同上

已修改

2020-02-17 07:01 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线的制品提升插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
下一pr修改为该名称

2020-02-17 07:39 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
`流水线上优化制品插件` 这里漏了？

2020-02-17 07:44 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
> `流水线上优化制品插件` 这里漏了？

`Artifact Promotion plugin for Jenkins Pipeline` 我把它翻译成 `Jenkins 流水线上优化制品插件`了

2020-02-17 07:47 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
https://github.com/jenkinsci/artifact-promotion-plugin
从项目上的描述来看 promotion 在这里并不是优化的意思，指的是把制品从snapshot升级到release上这种动作。

2020-02-17 07:49 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
> `流水线上优化制品插件` 这里漏了？

https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline/ 可以参考这个blog的detail的第一句，这个课题的目的应该还是要优化在流水线上的兼容性

2020-02-17 08:13 UTC, yJunS commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +Google 编程之夏活动不仅仅是一个夏日的实习项目，对于组织和一些社区的成员来说，这个活动是他们一整年努力的成果。现在，在里斯本举行的 Devops World | Jenkins World 会议以及最后的回顾会议之后，我们宣布 GSoC 2019 正式画上结束的句号。首先我们感谢所有的参与者：学生们，导师们，主题专家，以及其他一些提出课题构想，参与学生选择，社区联系以及一些后期的讨论与回顾
`学生们，导师们，主题专家`、`参与学生选择，社区联系以及一些后期的讨论与回顾的贡献者们` 之间用顿号应该好一些

2020-02-17 08:13 UTC, yJunS commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +title：2019 年 Google 编程之夏活动报告
感觉 `Google Summer of Code` 应该不需要翻译

2020-02-17 08:14 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +title：2019 年 Google 编程之夏活动报告
这个还好了，国内也有一些是这么翻译的。

2020-02-17 08:14 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
> https://github.com/jenkinsci/artifact-promotion-plugin
> 从项目上的描述来看 promotion 在这里并不是优化的意思，指的是把制品从snapshot升级到release上这种动作。

如果参考这个链接的话这个地方的 `promotion` 是保留原文还是用其他的翻译代替？

2020-02-17 08:14 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +Google 编程之夏活动不仅仅是一个夏日的实习项目，对于组织和一些社区的成员来说，这个活动是他们一整年努力的成果。现在，在里斯本举行的 Devops World | Jenkins World 会议以及最后的回顾会议之后，我们宣布 GSoC 2019 正式画上结束的句号。首先我们感谢所有的参与者：学生们，导师们，主题专家，以及其他一些提出课题构想，参与学生选择，社区联系以及一些后期的讨论与回顾
确实是，中午的习惯是顿号

2020-02-17 08:15 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
没有特别的词的话，就建议保留了

2020-02-17 08:31 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
> 没有特别的词的话，就建议保留了

确实想不到特别的词了，那我就保留原词了。`Jenkins 流水线 artifact-promotion 插件` 还是 `Jenkins 流水线制品 promotion 插件`这两个哪个好一些？或者说有其他的译法？

2020-02-17 08:36 UTC, donhui commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
`Jenkins 流水线 artifact-promotion 插件` 我个人觉得这个好

2020-02-17 08:37 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
`Jenkins 流水线制品 promotion 插件` +1

2020-02-17 08:39 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +Google 编程之夏活动不仅仅是一个夏日的实习项目，对于组织和一些社区的成员来说，这个活动是他们一整年努力的成果。现在，在里斯本举行的 Devops World | Jenkins World 会议以及最后的回顾会议之后，我们宣布 GSoC 2019 正式画上结束的句号。首先我们感谢所有的参与者：学生们，导师们，主题专家，以及其他一些提出课题构想，参与学生选择，社区联系以及一些后期的讨论与回顾
> `学生们，导师们，主题专家`、`参与学生选择，社区联系以及一些后期的讨论与回顾的贡献者们` 之间用顿号应该好一些

`学生们、导师们、主题专家、以及其他一些提出课题构想，参与学生选择，社区联系以及一些后期的讨论与回顾的贡献者们`  我觉得这个地方在人分类这里可以用顿号做分隔，然后`课题构想...` 这几个的话我觉得这些还是保留逗号，因为这个地方我觉得强调的是人，所以用逗号分隔这些要感谢的人我觉得就可以。

2020-02-17 08:46 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
两个都可以，不会有歧义就好

2020-02-17 09:11 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +今年并非所有的项目都完成了。我们也在 [Jenkins 流水线上优化制品插件](https://jenkins.io/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline)和[云特性的外部工作区管理插件](https://jenkins.io/projects/gsoc/2019/ext-workspace-manag
> `Jenkins 流水线制品 promotion 插件` +1

那我改成 `Jenkins 流水线 artifact-promotion 插件` 吧，这两个应该是一体的毕竟用连字符连着的。

2020-02-17 09:13 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +title：2019 年 Google 编程之夏活动报告
这个地方是否保留当前翻译格式，因为这个地方是这篇blog的主题也是出现比较多的几个词组之一，这个地方改动的话文章里面也有一些翻译的地方需要同样处理。

2020-02-17 09:51 UTC, LinuxSuRen commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +title：2019 年 Google 编程之夏活动报告
我觉得全文保持一致就可以了

2020-02-17 10:44 UTC, 0N0thing commented on articles/2020/02/2020-02-18-google-summer-of-code-2019-report.md
> +title：2019 年 Google 编程之夏活动报告
这个地方我就保持当前内容不动了

2020-02-17 23:08 UTC, LinuxSuRen approved these changes

2020-02-17 23:08 UTC, merged