个人原创博客：批量修改 Jenkins 任务的技巧
jenkins-infra/wechat pull request #30
Opened 2019-02-23 04:43 UTC by zacker330

2019-02-23 12:32 UTC, LinuxSuRen requested changes

2019-02-23 12:32 UTC, LinuxSuRen commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +当我们代码`job.addProperty(new BuildDiscarderProperty(new LogRotator (2, 10, 2, 10)))`执行后，这个修改到底有没有持久化到文件系统中呢（Jenkins 的所有配置都持久在文件系统中）？我们看下 hudson.model.Job 的源码就知道：
> Jenkins 的所有配置都持久在文件系统中

现在，这个只是默认行为，也可以存放在其他位置。

2019-02-23 12:32 UTC, LinuxSuRen commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +本文章只介绍了批量修改“丢弃旧的构建”的配置，如果还希望修改其它配置，可以参考 hudson.model.Job 的源码：https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Job.java
> hudson.model.Job

对源码的引用是否可以添加对应的链接。

2019-02-23 12:32 UTC, LinuxSuRen commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +description: "Jenkins 脚本命令行的一种实践"
> 脚本命令行

个人感觉，“命令行脚本”读起来更顺口。

2019-02-23 12:32 UTC, LinuxSuRen commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +最近，笔者所在团队的 Jenkins 所在的服务器经常报硬盘空间不足。经查发现很多任务设置“丢弃旧的构建”。通知所有的团队检查自己的 Jenkins 任务有没有设置丢弃旧的构建，有些不现实。
> 经查发现很多任务设置“丢弃旧的构建”

按照你的上下文，是否应该是“没有”设置？

2019-02-23 12:33 UTC, LinuxSuRen commented
请使用与你的 GitHub 账户关联的邮箱地址进行提交。

2019-02-23 13:19 UTC, zacker330 commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +description: "Jenkins 脚本命令行的一种实践"
Jenkins script console 翻译成 Jenkins 脚本命令行，这个翻译应该没有问题，它是我切换到中文版的 Jenkins 看到的翻译。

2019-02-23 13:20 UTC, zacker330 commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +本文章只介绍了批量修改“丢弃旧的构建”的配置，如果还希望修改其它配置，可以参考 hudson.model.Job 的源码：https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Job.java
如果发布到公众号上，改成链接，没有显示上和操作上的问题，我改一下。

2019-02-23 13:21 UTC, zacker330 commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +最近，笔者所在团队的 Jenkins 所在的服务器经常报硬盘空间不足。经查发现很多任务设置“丢弃旧的构建”。通知所有的团队检查自己的 Jenkins 任务有没有设置丢弃旧的构建，有些不现实。
get

2019-02-23 13:22 UTC, LinuxSuRen commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +description: "Jenkins 脚本命令行的一种实践"
如果有更好的翻译方法的话，也可以把 Jenkins 节目上的进行修改。

2019-02-23 13:23 UTC, LinuxSuRen commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +本文章只介绍了批量修改“丢弃旧的构建”的配置，如果还希望修改其它配置，可以参考 hudson.model.Job 的源码：https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Job.java
公众号上总是有链接的问题，我们可以统一让大家查看原文获取链接

2019-02-23 23:27 UTC, zacker330 commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +当我们代码`job.addProperty(new BuildDiscarderProperty(new LogRotator (2, 10, 2, 10)))`执行后，这个修改到底有没有持久化到文件系统中呢（Jenkins 的所有配置都持久在文件系统中）？我们看下 hudson.model.Job 的源码就知道：
将

> Jenkins 的所有配置都持久在文件系统中 

改成：

Jenkins 的所有配置默认都持久化在文件系统中

2019-02-23 23:43 UTC, zacker330 commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +description: "Jenkins 脚本命令行的一种实践"
“节目”？

我个人看好“脚本命令行”，这样，重点在于“命令行”。而“命令行脚本”的重点在于“脚本”。这样会给人误解。

因为 “Jenkins script console” 是 Jenkins 的命令行。

2019-02-23 23:44 UTC, zacker330 commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +本文章只介绍了批量修改“丢弃旧的构建”的配置，如果还希望修改其它配置，可以参考 hudson.model.Job 的源码：https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Job.java
已经改成 Markdown 的样式。

2019-02-24 00:42 UTC, LinuxSuRen commented
麻烦注意下你的 git 关联邮箱

2019-02-24 08:51 UTC, closed without merging