[翻译-2020-03-06]使用 Visual Studio Code 验证 JCasC 配置文件
jenkins-infra/wechat pull request #304
Opened 2020-02-28 07:02 UTC by wenjunzhangp

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2020/02/25/vscode-caseStudy/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2020-02-29 01:51 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +## 代码配置插件
Configuration-as-code
统一翻译成`配置即代码`吧
下面也有几处

2020-02-29 01:51 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +问题陈述：将现有的模式验证工作流程脚本语言 [Jenkins 配置代码插件](https://plugins.jenkins.io/configuration-as-code/)转换为基于Java的重写，从而增强其可读性和可测试性，并由该测试框架提供支持。通过开发 VSCode 插件来促进自动完成和验证，从而增强开发人员的经验，这将有助于开发人员在应用到 Jenkins 实例之前编写正确的 Ya
基于Java的重写
中英文之间加空格

2020-02-29 01:51 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +问题陈述：将现有的模式验证工作流程脚本语言 [Jenkins 配置代码插件](https://plugins.jenkins.io/configuration-as-code/)转换为基于Java的重写，从而增强其可读性和可测试性，并由该测试框架提供支持。通过开发 VSCode 插件来促进自动完成和验证，从而增强开发人员的经验，这将有助于开发人员在应用到 Jenkins 实例之前编写正确的 Ya
[Jenkins 配置代码插件]
同上

2020-02-29 01:51 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线[会议](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-project
[会议]
meetup 建议保持英文

2020-02-29 01:51 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +    - 自动完成（Ctrl + Space）：自动完成所有命令。
Auto completion
个人感觉翻译成`自动补全`比较好

2020-03-02 03:45 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +## 配置即代码
配置即代码 --> 配置即代码插件

2020-03-02 03:45 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +    - 自动完成（Ctrl + Space）：自动补全。
自动完成（Ctrl + Space）：自动补全。
-->
自动补全（Ctrl + Space）：自动补全所有命令。

2020-03-02 15:49 UTC, yJunS requested changes

2020-03-02 15:49 UTC, yJunS commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +问题陈述：将现有的模式验证工作流程脚本语言 [Jenkins 配置即代码插件](https://plugins.jenkins.io/configuration-as-code/)转换为基于 Java 的重写，从而增强其可读性和可测试性，并由该测试框架提供支持。通过开发 VSCode 插件来促进自动完成和验证，从而增强开发人员的经验，这将有助于开发人员在应用到 Jenkins 实例之前编写正确的
原文中是 `yaml`, `y`没有大写

2020-03-02 15:49 UTC, yJunS commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +启用了新的 JSON 模式后，开发人员现在可以针对其测试 yaml 文件。该模式检查`描述符`，即可以应用于插件或 Jenkins 核心的配置，使用正确的类型并在某些情况下提供帮助文本。 VSCode 允许我们通过一些修改立即测试架构。该项目是[社区桥](https://communitybridge.org/)计划的一部分，社区桥计划是 Linux 基金会创建的一个平台，旨在使开发人员以及支持
个人感觉 `descriptors ` 保持原文即可，可以不做翻译

`Community Bridge` 同上，建议保持原文

2020-03-02 15:49 UTC, yJunS commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +## 屏幕截图
感觉直接写 `截图` 即可

2020-03-03 02:56 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
等我们翻译过来的时候，这个已经过去了
`我们将于 2 月 26 日举行在线 `这个将来时改成过去时？
@LinuxSuRen 你怎么看？
另外，我感觉PPT或视频链接也可以放上（不过视频时在 YouTube）
* Video: https://www.youtube.com/watch?v=nlm-ZaW9FPo&feature=youtu.be
* Slides: https://www.slideshare.net/SladynNunes/jenkins-jcasc-online-meetup

2020-03-03 05:59 UTC, wenjunzhangp commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
嗯，当时我翻译的时候也有想到过这个时效性的问题。这两个参考的 PPT 和 video 加在末尾吗。

2020-03-03 07:57 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
我个人建议放最后面

2020-03-03 10:04 UTC, wenjunzhangp commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
好的，那个时间的话要改成过去时吗

2020-03-03 10:05 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
我觉得可以加个`译注`说明下

2020-03-04 01:24 UTC, wenjunzhangp commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
`译注`怎么加，之前没加过尴尬不会加

2020-03-04 02:03 UTC, donhui commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
简单点就是把`将`去掉 😢
我写了个例子，可以参考下：
我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)（译注：该 meetup 已举办，Video 及 Slides 链接见最下方）

2020-03-04 11:59 UTC, donhui approved these changes
lgtm

2020-03-05 15:34 UTC, yJunS commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
将看着没去掉啊，应该是：
`我们于 2 月 26 日举行在线 meetup（译注：该 meetup 已举办，Video 及 Slides 链接见最下方）`
这样感觉才对吧？

2020-03-06 07:48 UTC, wenjunzhangp commented on articles/2020/03/2020-03-06-validating-jcasc-configuration-files-using-visual-studio-code.md
> +我们将于 2 月 26 日举行在线 [meetup](https://www.meetup.com/Jenkins-online-meetup/events/268823268)，讨论该插件以及如何使用它来验证您的 YAML 配置文件。对于有关架构的任何建议或讨论，请随时加入我们的 [gitter 频道](https://gitter.im/jenkinsci/jcasc-devtools-pr
我把`将`去掉了。

2020-03-06 12:38 UTC, yJunS approved these changes

2020-03-06 12:39 UTC, merged