[翻译-2020-03-16]更新流水线授权 SIG
jenkins-infra/wechat pull request #309
Opened 2020-03-05 06:21 UTC by wenjunzhangp

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins.io/blog/2020/03/02/pipeline-authoring-sig-update/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2020-03-05 06:33 UTC, LinuxSuRen requested changes
`authoring`: `the creation of programs and databases for computer applications such as computer-assisted learning or multimedia products.`

This special interest group aims to improve and curate the experience of authoring Jenkins Pipelines.

authoring 不是授权的意思。

update 在这里翻译成公告是否好一些。文章不像是在“更新”什么，是在公告 SIG 的变化。例如：流水线编撰 SIG 公告

2020-03-05 10:53 UTC, wenjunzhangp commented
好的多谢明白了，一会我改一下。

2020-03-16 07:55 UTC, LinuxSuRen approved these changes
抱歉，拖了很长时间。

2020-03-16 07:55 UTC, merged

2020-03-16 09:33 UTC, wenjunzhangp commented
没事的，最近我们也挺忙，都没时间接翻译了。：）