新原创博客：批量修改 Jenkins 任务的技巧
jenkins-infra/wechat pull request #31
Opened 2019-02-24 09:10 UTC by zacker330

作者：翟志军
原文地址：https://showme.codes/2019-02-23/jenkins-script-console-in-practice/

2019-02-24 09:38 UTC, LinuxSuRen approved these changes
LGTM

2019-02-24 09:42 UTC, LinuxSuRen requested changes
我们可以在 27 号发这篇文章，因此把文件名修改一下。或者，不体现也行。

2019-02-24 09:42 UTC, LinuxSuRen commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +description: "Jenkins 脚本命令行的一种实践"
把日期加一下：

`date: 2019-02-27`

另外，可以把你的原文地址放在这里：

`original: http://sample.com/orignal_link`

2019-02-24 10:17 UTC, zacker330 commented on articles/2019/02/2019-2-23-jenkins-script-console-in-practice.md
> +description: "Jenkins 脚本命令行的一种实践"
好的。我改一下。

2019-02-25 01:30 UTC, LinuxSuRen approved these changes
LGTM

2019-02-25 11:12 UTC, merged