[翻译-2020-03-24] 7 款你或许不知道的 DevOps 工具链编排解决方案
jenkins-infra/wechat pull request #319
Opened 2020-03-17 02:42 UTC by 0N0thing

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://dzone.com/articles/7-devops-toolchain-orchestration-solution-you-may)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2020-03-17 05:04 UTC, yJunS requested changes
![image](https://user-images.githubusercontent.com/20575981/76823538-81f14800-684f-11ea-9ca1-4bf0be7ea6f8.png)
这部分内容的冒号需要用半角的":"，不可以用全角的"："，否则渲染页面的时候会出错的，如果后面有内容加空格即可，如果是换行的直接回车即可

2020-03-17 05:09 UTC, 0N0thing commented
> ![image](https://user-images.githubusercontent.com/20575981/76823538-81f14800-684f-11ea-9ca1-4bf0be7ea6f8.png)
> 这部分内容的冒号需要用半角的":"，不可以用全角的"："，否则渲染页面的时候会出错的，如果后面有内容加空格即可，如果是换行的直接回车即可

好的，我修改下。

2020-03-19 13:22 UTC, yJunS commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +团队之间的透明化沟通在应用程序开发过程中成为了一项巨大的挑战。一个组织中的大部分团队的独立性已经有相当长时间了。这也就意味着开发团队，业务分析团队，QA 以及业务运营团队之间的工作距离越来越疏远。
`开发团队，业务分析团队，QA 以及业务运营团队` 应该是连贯的吧，应该用顿号好一些吧

2020-03-19 13:22 UTC, yJunS commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +date: 2020-03-24
日期最好遵守协定，每周的周一、三、五来发布文章

2020-03-19 13:22 UTC, yJunS commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +这些实践尝试将团队凝聚在一起从而避免各自为战。它们以在应用交付时确保高效为目标。这种方法提升了公司软件交付的功能性并且确保产生更少的风险。它们同样负责消除在 IT 响应中出现的任何障碍。
任何 -> 各种

2020-03-19 13:22 UTC, yJunS commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +你为公司构建的所有公司想要表达的东西都是通过代码实现的。但是代码同样有窍门的，你必须确保它能尽可能容易地被理解。你必须对它们进行控制和操作分支。如果做不到这些，就有可能面临非常乱糟糟的情况。
感觉`非常乱糟糟`没有必要加`非常`吧

2020-03-19 13:22 UTC, yJunS commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +你需要一条标准化资源配置途径。之后，你需要在整个 IT 开发过程中强制使用这个状态。最好的办法是通过一条自动化途径以及敏捷的方式。这种方法叫做配置管理。例如 [Ansible](https://www.ansible.com/)、[Chef 以及 Puppet](https://dzone.com/articles/tools-you-must-know-if-you-are-a-devops-
`最推荐的工具` 改为 `最佳建议`似乎更好一些

2020-03-19 13:22 UTC, yJunS commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +## 写在最后
这个标题修改为`结束语`是否好一些？

2020-03-20 01:16 UTC, 0N0thing commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +你需要一条标准化资源配置途径。之后，你需要在整个 IT 开发过程中强制使用这个状态。最好的办法是通过一条自动化途径以及敏捷的方式。这种方法叫做配置管理。例如 [Ansible](https://www.ansible.com/)、[Chef 以及 Puppet](https://dzone.com/articles/tools-you-must-know-if-you-are-a-devops-
> `最推荐的工具` 改为 `最佳建议`似乎更好一些

我改成了 `都是此过程最推荐使用的工具`，你看这样是否合适一些？

2020-03-20 01:17 UTC, 0N0thing commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +date: 2020-03-24
> 日期最好遵守协定，每周的周一、三、五来发布文章

这一个pr还要改吗？要不下一篇译文我注意下，这次先用这个时间可以吗？

2020-03-20 01:27 UTC, LinuxSuRen commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +date: 2020-03-24
我感觉还好了，大家能有时间review就👌。目前文章的数量也还可以

2020-03-20 02:34 UTC, 0N0thing commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +date: 2020-03-24
> 我感觉还好了，大家能有时间review就👌。目前文章的数量也还可以

我之前都把发布日期设置的周二，我记得当时我第一次提pr的时候当时时间好像是周二审核完周三发布这样的节奏，然后我就一直认为这个时间是一个发布前节点的时间，如果这样的话那我就按照发布时间的节点来吧。

2020-03-20 02:36 UTC, LinuxSuRen commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +date: 2020-03-24
没关系的，确实是发布的日期。

2020-03-20 02:40 UTC, 0N0thing commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +date: 2020-03-24
> 没关系的，确实是发布的日期。

好的，了解，那我下一篇译文我注意下。因为我这边还有一篇正在翻译的，下次pr时间上我会修改成发布时间点。

2020-03-20 11:59 UTC, yJunS requested changes

2020-03-20 11:59 UTC, yJunS commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +![cover](cover.png)
图片格式的后缀名改一下，之前几次也有类似的情况，下次可以注意一下

2020-03-20 12:10 UTC, 0N0thing commented on articles/2020/03/2020-03-24-7-devops-toolchains-orchestration-solutions-you-may-not-know.md
> +![cover](cover.png)
> 图片格式的后缀名改一下，之前几次也有类似的情况，下次可以注意一下

好的，我的失误，之前忘记改了

2020-03-20 13:16 UTC, yJunS approved these changes

2020-03-23 10:01 UTC, closed without merging

2020-03-23 10:01 UTC, donhui commented
@0N0thing
[翻译-2020-04-08] 将 Jenkins 构建为代码 
这个单独建分支
不同文章用不同分支
分支策略可以参考：http://jenkins-zh.cn/about/branching-strategy/

2020-03-23 10:11 UTC, 0N0thing commented
> @0N0thing
> [翻译-2020-04-08] 将 Jenkins 构建为代码
> 这个单独建分支
> 不同文章用不同分支
> 分支策略可以参考：http://jenkins-zh.cn/about/branching-strategy/

不好意思，提错了，新译文我重新提pr，可能是分支名重复了都一块提上去了

2020-03-23 10:38 UTC, donhui commented
这个你不应该关了啊，可以把最后一个 commit 回退掉
这篇文章也要发布的

2020-03-23 10:55 UTC, 0N0thing commented
关闭的操作我这边没点，是不是GitHub检测到approve merge的动作之后就关闭了？需要我这边reopen然后回退吗？

2020-03-23 10:59 UTC, donhui commented
0N0thing deleted the 0N0thing:temp4commit branch 1 hour ago

应该是你把分支删掉了，需要重新打开回退下

2020-03-23 11:00 UTC, 0N0thing commented
> 0N0thing deleted the 0N0thing:temp4commit branch 1 hour ago
> 
> 应该是你把分支删掉了，需要重新打开回退下

好的，我处理下

2020-03-24 01:00 UTC, 0N0thing commented
> 0N0thing deleted the 0N0thing:temp4commit branch 1 hour ago
> 
> 应该是你把分支删掉了，需要重新打开回退下

https://github.com/jenkins-infra/wechat/pull/327 不好意思哈，昨天看了半天也没折腾出来，因为我把分支从github上删掉了，所以close之前的commitid找不到了，所以我新提交了一次pr，麻烦用这个pr处理吧。