[翻译-2020-04-08] 将 Jenkins 构建为代码
jenkins-infra/wechat pull request #326
Opened 2020-03-23 10:17 UTC by 0N0thing

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://medium.com/preply-engineering/jenkins-omg-275e2df5d647)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

2020-04-03 05:48 UTC, yJunS requested changes

2020-04-03 05:48 UTC, yJunS commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +translator: s1mple_zj
![image](https://user-images.githubusercontent.com/20575981/78323403-4d49f400-75a4-11ea-9196-070277604104.png)
这块要写自己的 GitHub ID，否则渲染的时候，也会报错的

2020-04-03 05:48 UTC, yJunS commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +来源: https://www.altexsoft.com/blog/engineering/comparison-of-most-popular-continuous-integration-tools-jenkins-teamcity-bamboo-travis-ci-and-more/
这块不需要吧？

2020-04-03 05:48 UTC, yJunS commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +packer的配置是这样的
这块应该是对上段配置的介绍吧，如果没有地方介绍的话，个人感觉就需要单独放出来了

2020-04-03 05:48 UTC, yJunS commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +Bootstrap 文件 `packer_bootstrap.sh` 包含了在 AMI 预安装软件的所有命令。举个例子，我们使用 Docker，docker-compose 以及 [vaultenv](https://github.com/channable/vaultenv) 或者安装 Datadog 节点用来监控。
` Docker，docker-compose` 之间用顿号好吧？

2020-04-03 05:48 UTC, yJunS commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +我们使用的 Jenkins 集成了 GitHub，所以我们应该通过外部网络为 Github 提供一些 Jenkins URL。有很多可操作的方案（[IP 白名单](https://api.github.com/meta)，URL 或者令牌白名单，等等）而我们则结合 Cloudfront 以允许路径以及令牌验证。
token 可以不用翻译成令牌吧？  直接写成 token 就可以吧？

2020-04-03 05:48 UTC, yJunS commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +*订阅 [Preply 工程师博客](https://medium.com/preply-engineering)获取更多有关 Preply 工程的一些有趣的文章。敬请关注！*
这段应该不属于文章内的内容吧，不需要加的吧

2020-04-05 12:14 UTC, LinuxSuRen commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +我们使用的 Jenkins 集成了 GitHub，所以我们应该通过外部网络为 Github 提供一些 Jenkins URL。有很多可操作的方案（[IP 白名单](https://api.github.com/meta)，URL 或者令牌白名单，等等）而我们则结合 Cloudfront 以允许路径以及令牌验证。
我感觉都可以，在很多地方，也是用领牌这个表述的

2020-04-05 12:14 UTC, LinuxSuRen commented
@0N0thing 为了提高文章发布效率，您可以自行将当前 PR 迁移到 https://github.com/jenkins-zh/jenkins-zh 或者在合并后，我们帮忙迁移。
更多信息，请参考 jenkins-zh/jenkins-zh#205

2020-04-07 01:14 UTC, 0N0thing commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +translator: s1mple_zj
不好意思，节假日期间没有处理，我今天处理下。

2020-04-07 01:22 UTC, 0N0thing commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +来源: https://www.altexsoft.com/blog/engineering/comparison-of-most-popular-continuous-integration-tools-jenkins-teamcity-bamboo-travis-ci-and-more/
> 这块不需要吧？

这个地方我又重新看了一遍原文，发现这个地方的图片换了，所以我重新把这个地方的图片取了一次，然后覆盖了原先的。这个图片跟原文是有关系的，然后后面的链接应该是之前访问session的时候加上的链接，这个地方我会去掉。

2020-04-07 01:25 UTC, 0N0thing commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +packer的配置是这样的
> 这块应该是对上段配置的介绍吧，如果没有地方介绍的话，个人感觉就需要单独放出来了

packer的配置对应的是上面的内容，这句在原文里面是上面这块代码的解释说明，如果可以在文章渲染时作为一个灰色的文字的话就可以放在这个代码块下面，如果不行的话就把这句话放在代码块上面。

2020-04-07 01:34 UTC, 0N0thing commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +Bootstrap 文件 `packer_bootstrap.sh` 包含了在 AMI 预安装软件的所有命令。举个例子，我们使用 Docker，docker-compose 以及 [vaultenv](https://github.com/channable/vaultenv) 或者安装 Datadog 节点用来监控。
> ` Docker，docker-compose` 之间用顿号好吧？

已修改

2020-04-07 01:35 UTC, 0N0thing commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +我们使用的 Jenkins 集成了 GitHub，所以我们应该通过外部网络为 Github 提供一些 Jenkins URL。有很多可操作的方案（[IP 白名单](https://api.github.com/meta)，URL 或者令牌白名单，等等）而我们则结合 Cloudfront 以允许路径以及令牌验证。
> token 可以不用翻译成令牌吧？ 直接写成 token 就可以吧？

其实token或者令牌我觉得都能理解这个单词的意思，可能看个人习惯吧，我觉得可以把它翻译出来

2020-04-07 01:37 UTC, 0N0thing commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +*订阅 [Preply 工程师博客](https://medium.com/preply-engineering)获取更多有关 Preply 工程的一些有趣的文章。敬请关注！*
> 这段应该不属于文章内的内容吧，不需要加的吧

我把最后一行的内容去掉了，上面那个还是跟文章有关的内容。

2020-04-07 01:38 UTC, 0N0thing commented
> @0N0thing 为了提高文章发布效率，您可以自行将当前 PR 迁移到 https://github.com/jenkins-zh/jenkins-zh 或者在合并后，我们帮忙迁移。
> 更多信息，请参考 [jenkins-zh/jenkins-zh#205](https://github.com/jenkins-zh/jenkins-zh/issues/205)

这一篇先放这里吧，我把另一篇现在还在这上面的pr迁移到那边去。

2020-04-07 01:45 UTC, LinuxSuRen commented
@0N0thing 好的，没问题。

2020-04-07 01:59 UTC, 0N0thing commented
> @0N0thing 好的，没问题。

但是我看到目录结构变了，新的项目下哪个目录存放翻译的文章？

2020-04-07 02:04 UTC, LinuxSuRen commented
父目录变了，里面的结构还是一样的。是下面的这个目录：
`https://github.com/jenkins-zh/jenkins-zh/tree/master/content/wechat/articles`

2020-04-07 02:14 UTC, 0N0thing commented
> 父目录变了，里面的结构还是一样的。是下面的这个目录：
> `https://github.com/jenkins-zh/jenkins-zh/tree/master/content/wechat/articles`

好的，了解

2020-04-08 01:02 UTC, LinuxSuRen requested changes
把 Jenkins 构建为代码，感觉逻辑上有点问题。一般都是把代码构建成其他的东西，而不能反过来。可以参考下面的翻译：
- 以代码的形式构建 Jenkins
- 构建 Jenkins 即代码
- 保持原文不翻译

2020-04-08 01:02 UTC, LinuxSuRen commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +description: 主要介绍了关于 Jenkins “配置即代码”模式的具体方法，结合工具以及脚本对该模式进行了说明。
描述不是一个完整的句子，不需要句号结尾

2020-04-08 01:14 UTC, 0N0thing commented
> 把 Jenkins 构建为代码，感觉逻辑上有点问题。一般都是把代码构建成其他的东西，而不能反过来。可以参考下面的翻译：
> 
> * 以代码的形式构建 Jenkins
> * 构建 Jenkins 即代码
> * 保持原文不翻译

修改成第一个`以代码的形式构建 Jenkins`了，不翻译的话标题表达的意思就传达不给读者了。

2020-04-08 01:14 UTC, 0N0thing commented on articles/2020/04/2019-04-08-build-jenkins-as-a-code.md
> +description: 主要介绍了关于 Jenkins “配置即代码”模式的具体方法，结合工具以及脚本对该模式进行了说明。
> 描述不是一个完整的句子，不需要句号结尾

already fixed

2020-04-08 01:19 UTC, LinuxSuRen approved these changes
LGTM
如果没有其他负面反馈的话，我今天中午会合并

2020-04-08 01:21 UTC, LinuxSuRen commented
对了，我们把当前仓库的内容迁移到 [jenkins-zh](https://github.com/jenkins-zh/jenkins-zh) 后，并不能保留原有的提交记录，如果你希望保留的话，可以把这个内容迁移过去。或者，我来迁移都可以。

2020-04-08 01:24 UTC, 0N0thing commented
> 对了，我们把当前仓库的内容迁移到 [jenkins-zh](https://github.com/jenkins-zh/jenkins-zh) 后，并不能保留原有的提交记录，如果你希望保留的话，可以把这个内容迁移过去。或者，我来迁移都可以。

记录保留与否的话都可以，这篇就麻烦你们帮忙迁移吧。

2020-04-08 01:27 UTC, LinuxSuRen commented
👌，没问题。

2020-04-08 05:53 UTC, merged