2019-03-13-electron-pipeline-demo
jenkins-infra/wechat pull request #46
Opened 2019-03-11 00:26 UTC by zacker330

原创博客：https://showme.codes/2019-03-10/electronjs-pipeline-demo/ 介绍 Electron 应用的流水线

2019-03-11 13:14 UTC, LinuxSuRen commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +完整源码地址：https://github.com/zacker330/electronjs-pipeline-demo
是否可以包含更多的总结，能有举一反三的效果最好。这样读者不仅仅从一个单一的例子中获得启发，类似的场景也能应用，也更容易引发讨论。

2019-03-11 13:15 UTC, LinuxSuRen commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +* 持续交付的八大原则：https://blog.csdn.net/tony1130/article/details/6673741
可以把参考的部分，在正文中加上链接。如果是 URL 的话，读者还需要手动拷贝才能打开。

2019-03-11 13:16 UTC, LinuxSuRen commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +  __appName = "electron-webpack-quick-start"
> __appName

个人建议，环境变量用全部大写比较好。

2019-03-11 13:17 UTC, LinuxSuRen commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +但是如何介绍呢？倒是个大问题。笔者尝试直接贴代码，在代码注释中讲解。这是一次尝试，希望你正负的反馈。
在代码中添加注释的方式来讲解思路很好，但是否也用自然语言来做一些背景、思路的介绍呢。

2019-03-11 22:55 UTC, zacker330 commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +完整源码地址：https://github.com/zacker330/electronjs-pipeline-demo
嗯。加上设计思路的说明了。

2019-03-11 22:56 UTC, zacker330 commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +  __appName = "electron-webpack-quick-start"
好建议，已经改成全大写。

2019-03-11 22:56 UTC, zacker330 commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +但是如何介绍呢？倒是个大问题。笔者尝试直接贴代码，在代码注释中讲解。这是一次尝试，希望你正负的反馈。
关于思路，我还是在小结部分讲吧。

2019-03-11 22:58 UTC, zacker330 commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +* 持续交付的八大原则：https://blog.csdn.net/tony1130/article/details/6673741
考虑到是发在 Wechat 上的，所以，才写成这样。因为公众号上是不是显示超链接的。

但是，就你所说，我在链接的基础上，再加上超链接。

2019-03-12 01:47 UTC, LinuxSuRen requested changes

2019-03-12 01:47 UTC, LinuxSuRen commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +但是如何介绍呢？倒是个大问题。笔者尝试直接贴代码，在代码注释中讲解。这是一次尝试，希望你正负的反馈。
> 希望你正负的反馈

这里是否表述错误？

2019-03-12 04:03 UTC, zacker330 commented on articles/2019/03/2019-03-13-electron-pipeline-demo.md
> +但是如何介绍呢？倒是个大问题。笔者尝试直接贴代码，在代码注释中讲解。这是一次尝试，希望你正负的反馈。
表述不是很好。我改成：“希望得到你的正负反馈”

2019-03-12 10:10 UTC, LinuxSuRen approved these changes

2019-03-12 10:10 UTC, merged