理解gerrit change-id
jenkins-infra/wechat pull request #53
Opened 2019-03-24 11:36 UTC by zacker330

新博客，虽然和 Jenkins 看起来关系不大。但是都属于 CD 的范畴。

2019-03-24 14:03 UTC, LinuxSuRen requested changes
内容很不错，但是有几个疑问。

* 对于之前没有了解过 Gerrit 的人来说，一上来看会感觉一头雾水。因此，建议增加一些相关的介绍、链接之类的，这样的话，读者更容易理解。
* 如果能把 Gerrit 与 Jenkins 联系起来的花，会不会更好

另外，注意避免一些多余的空行。`## title` 后面也通常会有一个空行。

2019-03-25 00:11 UTC, zacker330 commented
> * 如果能把 Gerrit 与 Jenkins 联系起来的花，会不会更好

1. 这不是一篇 Gerrit 的科普文，是假设用户已经知道 Gerrit 是做什么用了，因为不了解 Gerrit 的人，看到这标题，可能不会看这文章了。但是加入一些参考是有必要的。

2. Gerrit 与 Jenkins 联系的相关内容，我还在看，不方便写过多内容。目前本章的内容只是 Gerrit 基础知识，联系起来的话有些生硬。

2019-03-25 05:20 UTC, LinuxSuRen commented on articles/2019/03/2019-03-24-understand-gerrit-change-id.md
> +> 审校：LinuxSuRen（https://github.com/LinuxSuRen）
个人感觉不用加谁来校验的，通过 GitHub 的 review 过程也能看出来。

2019-03-25 05:28 UTC, LinuxSuRen commented
> 这不是一篇 Gerrit 的科普文，是假设用户已经知道 Gerrit 是做什么用了，因为不了解 Gerrit 的人，看到这标题，可能不会看这文章了。但是加入一些参考是有必要的。

如果能有些简单介绍，让不了解 Gerrit 的人看了的人，感兴趣想要了解的话岂不是更好。这样的话，文章会更有用户粘性。

> Gerrit 与 Jenkins 联系的相关内容，我还在看，不方便写过多内容。目前本章的内容只是 Gerrit 基础知识，联系起来的话有些生硬。

既然本文是与 CI/CD 相关的，我建议还是把如何相关的思路或者想法描述一下。这样你如果计划还有后续文章的话，也是一铺垫；另外，这个公众号毕竟是 Jenkins 的官方号，所有的文章还是需要有关系、关联的比较好。

2019-03-25 05:45 UTC, zacker330 commented on articles/2019/03/2019-03-24-understand-gerrit-change-id.md
> +> 审校：LinuxSuRen（https://github.com/LinuxSuRen）
大多数读者是从发布出去的文章看的，并不会跑来 GitHub 来看 review 记录。而且，我们这文章是发布到公众号上去的。

2019-03-25 10:37 UTC, LinuxSuRen commented on articles/2019/03/2019-03-24-understand-gerrit-change-id.md
> +> 审校：LinuxSuRen（https://github.com/LinuxSuRen）
> 并不会跑来 GitHub 来看 review 记录

有道理。

https://github.com/jenkins-infra/wechat/blob/master/articles/2019/03/2019-03-13-electron-pipeline-demo.md
另外一篇文章的`审校`是写在文末的，我们需要统一。

2019-03-25 11:02 UTC, zacker330 commented on articles/2019/03/2019-03-24-understand-gerrit-change-id.md
> +> 审校：LinuxSuRen（https://github.com/LinuxSuRen）
嗯。之前我是放在最后面的，但是，我见 InfoQ 的都是放在前面。我觉得也有道理，我们应该突出审校者的贡献。

2019-03-25 15:25 UTC, LinuxSuRen commented on articles/2019/03/2019-03-24-understand-gerrit-change-id.md
> +> 审校：LinuxSuRen（https://github.com/LinuxSuRen）
可以的，建议把这个写到 readme 中，方便后来加入的朋友

2019-03-26 22:19 UTC, zacker330 commented
> > 这不是一篇 Gerrit 的科普文，是假设用户已经知道 Gerrit 是做什么用了，因为不了解 Gerrit 的人，看到这标题，可能不会看这文章了。但是加入一些参考是有必要的。
> 
> 如果能有些简单介绍，让不了解 Gerrit 的人看了的人，感兴趣想要了解的话岂不是更好。这样的话，文章会更有用户粘性。
> 
> > Gerrit 与 Jenkins 联系的相关内容，我还在看，不方便写过多内容。目前本章的内容只是 Gerrit 基础知识，联系起来的话有些生硬。
> 
> 既然本文是与 CI/CD 相关的，我建议还是把如何相关的思路或者想法描述一下。这样你如果计划还有后续文章的话，也是一铺垫；另外，这个公众号毕竟是 Jenkins 的官方号，所有的文章还是需要有关系、关联的比较好。

在这文章里介绍不合适，我个人认为。还是在 Gerrit 与 Jenkins 集成的文章里再介绍吧。这文章，就不先不发了。后面再发也可以。

2019-03-26 22:19 UTC, closed without merging