add blog: 简析 Jenkins 专有用户数据库加密算法
jenkins-infra/wechat pull request #69
Opened 2019-04-08 10:45 UTC by donhui

2019-04-10 02:10 UTC, LinuxSuRen requested changes

2019-04-10 02:10 UTC, LinuxSuRen commented on articles/2019/04/2019-04-12-brief-analysis-the-encryption-algorithm-of-the-built-in-jenkins-user-database.md
> +date: 2019-04-10
这里还是和上面的日期保持一直吧4月12

2019-04-10 02:10 UTC, LinuxSuRen commented on articles/2019/04/2019-04-12-brief-analysis-the-encryption-algorithm-of-the-built-in-jenkins-user-database.md
> +在 [github](https://github.com/jenkinsci/jenkins) 上查看其源码，通过关键字 #jbcrypt 搜索定位到 HudsonPrivateSecurityRealm.java 这个文件。
> github

更正式的写法是 GitHub

2019-04-10 03:54 UTC, LinuxSuRen approved these changes

2019-04-10 11:34 UTC, merged

2019-04-12 01:52 UTC, LinuxSuRen commented
微信公众号已设定时发布

2019-04-12 01:59 UTC, donhui commented
> 微信公众号已设定时发布
@LinuxSuRen 
我说么 每次刚好六点 哈哈

2019-04-12 02:00 UTC, LinuxSuRen commented
这个是我们之前会议设定好的时间，如果有更好的想法的话，欢迎提出来。

> On Apr 12, 2019, at 09:59, donghui <notifications@github.com> wrote:
> 
> 微信公众号已设定时发布
> @LinuxSuRen <https://github.com/LinuxSuRen>
> 我说么 每次刚好六点 哈哈
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/jenkins-infra/wechat/pull/69#issuecomment-482406609>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ABYivfbLmcJZ4F56cyCl3TI2Ep1d53EEks5vf-iGgaJpZM4ch3Yo>.
>