Translation task: AIOps: The Future of DevOps Is Here
jenkins-infra/wechat pull request #74
Opened 2019-04-12 04:55 UTC by P01son6415

2019-04-12 12:28 UTC, donhui approved these changes

2019-04-14 06:36 UTC, donhui commented on articles/2019/04/2019-04-15-aiops.md
> +tags:
建议增加 description
如果没有 description，会影响在网站的排版
同时也建议 2019-04-12-what-is-cicd 这篇文章加下 description

2019-04-14 06:49 UTC, LinuxSuRen commented on articles/2019/04/2019-04-15-aiops.md
> +tags:
+1

2019-04-16 00:57 UTC, LinuxSuRen requested changes
文件名要与日期保持一致

2019-04-17 01:27 UTC, merged

2019-04-17 04:17 UTC, zacker330 commented
简书：https://www.jianshu.com/p/aaa214c957ed

2019-04-17 04:20 UTC, zacker330 commented
掘金：https://juejin.im/post/5cb6a9156fb9a0686a22482d