[Translation 4.22] the-business-value-of-cd
jenkins-infra/wechat pull request #79
Opened 2019-04-14 12:19 UTC by donhui

2019-04-18 08:34 UTC, LinuxSuRen requested changes

2019-04-18 08:34 UTC, LinuxSuRen commented on articles/2019/04/2019-04-22-the-business-value-of-cd.md
> +持续交付使你能够以更低地风险更快低交付新软件或是更新已有软件。
> 持续交付使你能够以更低地风险更快低交付新软件或是更新已有软件。

持续交付使你能够以更低的风险、更快地交付新软件或是更新已有软件。

2019-04-18 08:34 UTC, LinuxSuRen commented
如果来得及的话，可以在周五（4月19日）发布

2019-04-18 09:48 UTC, donhui commented
> 如果来得及的话，可以在周五（4月19日）发布

已调整发布日期到 4.19
这样渐进式交付系列的三篇文章也可以下周一、三、五各发布一篇了

2019-04-18 09:51 UTC, LinuxSuRen approved these changes
LGTM

2019-04-18 11:15 UTC, merged

2019-04-19 01:30 UTC, donhui commented
开源中国：
https://my.oschina.net/jenkinszh/blog/3039004