[原创-2019-04-23] 关于 Jenkins master 共享 JENKINS_HOME 目录的实验
jenkins-infra/wechat pull request #85
Opened 2019-04-19 00:09 UTC by zacker330

### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-04-19 12:29 UTC, donhui commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +description: "尝试让Jenkins master高可用"
英文前后加空格

2019-04-19 12:31 UTC, donhui commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +2019-04-15-zabbix-monitor-jenkins
这行是不是 多了？

2019-04-19 12:38 UTC, donhui commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +可以确认的是，当两个 Jenkins 进程共用同一个 JENKINS_HOME 目录时，其中一个 Jenkins 进程更新了 Jenkins Home 的内容，另一个是不会实时更新的。所以，同时启动两个 Jenkins master 共用同一个 JENKINS_HOME 的方案是不可行的。我们不能在 jenkins-a 挂了后，直接将流量切到 jenkins-b。jenkins-b 必须重启。
Jenkins Home  是不是改成 JENKINS_HOME 比较好 ？
可以保持统一术语

2019-04-19 13:53 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +可以确认的是，当两个 Jenkins 进程共用同一个 JENKINS_HOME 目录时，其中一个 Jenkins 进程更新了 Jenkins Home 的内容，另一个是不会实时更新的。所以，同时启动两个 Jenkins master 共用同一个 JENKINS_HOME 的方案是不可行的。我们不能在 jenkins-a 挂了后，直接将流量切到 jenkins-b。jenkins-b 必须重启。
的确要统一。

2019-04-19 13:53 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +2019-04-15-zabbix-monitor-jenkins
故意的。

2019-04-19 14:11 UTC, donhui approved these changes

2019-04-20 02:39 UTC, LinuxSuRen requested changes
既然要在社区公众号上发的话，我们还是能尽量完善一些比较好，而且，要从社区表述一致性上考虑下。

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +date: 2019-04-23
加上`toc` 字段的话，可以生成目录，详情请参考 https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +description: "尝试让 Jenkins master 高可用"
通常情况下，描述会比标题要长一些

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +Jenkins master 的高可用是个老大难的问题。和很多人一样，笔者也想过两个 Jenkins master 共享同一个 JENKINS_HOME 的方案。了解 Jenkins 原理的人，都会觉得这个方案不可行。但是真的不可行吗？
> JENKINS_HOME

JENKINS_HOME 通常会用于标示一个环境变量，例如：`$JENKINS_HOME `。或者，使用另外的一个表述来描述 Jenkins 的存储根目录。

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +工作原因，笔者就亲自做了一次这样的实验。
> 工作原因，笔者就亲自做了一次这样的实验。

建议加一些行文中的语句转换

出于工作原因，笔者就亲自做了一次这样的实验，用来验证上面的猜想。

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +Jenkins 所有数据都存放目录中，这个目录被称为 JENKINS_HOME 目录。我们可以将 JENKINS_HOME 目录理解为 Jenkins 的数据库。但两个 Jenkins master 共享同一个 JENKINS_HOME 目录，并不像两个应用共享同一个数据库。
> Jenkins 所有数据都存放目录中

Jenkins 所有数据都存放某个目录中

> JENKINS_HOME

同上，这是一个环境变量名称，而不是一个名称、或者形容词。

> 但两个 Jenkins master 共享同一个 JENKINS_HOME 目录，并不像两个应用共享同一个数据库。

基于你的上下文，应该还没有得出这个结论，建议采用反问句或者疑问句。

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +执行`docker-compose up -d`启动实验环境后，发现，a 的界面与 b 的界面是不一样的。
> `docker-compose up -d`

建议前后增加空格，方便读者拷贝

> 发现，a 的界面与 b 的界面是不一样的

建议采用一致的表述，a 或者 jenkins-a

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +jenkins-b 的界面为：
> jenkins-b 的界面为

`为` ～ `是`。jenkins-b 的界面如下所示：

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +这时，将 jenkins-a 日志中的 Unlock 密码输入到 jenkins-b 的页面中，会得到报错信息：
> Unlock

我们的中文插件已经翻译过了，建议采用一致的表述。或者，全文采用英文的也可以。

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +ERROR: The password entered is incorrect, please check the file for the correct password
同样，建议采用一致的中英文表述。

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +ERROR: The password entered is incorrect, please check the file for the correct password
最新的每周更新版就是全部中文的

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +接下来，执行`docker-compose restart jenkins-a`命令重启 jenkins-a。再次使用 admin/admin 就可以登录成功了。
空格

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +执行`docker-compose up -d`启动实验环境后，发现，a 的界面与 b 的界面是不一样的。
为了方便读者按照文章介绍进行类似实验，建议把容器镜像的完整路径贴出来。

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +在 jenkins a 创建任务 x，刷新 jenkins b 的页面，jenkins b 上会不会显示出任务 x ？
> jenkins a

其他地方使用的是 jenkins-a ，建议保持一致

2019-04-20 02:39 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +最后结论：多个 Jenkins master 共享同一个 JENKINS_HOME 的方案是不可行的。
如果能给出为什么不能共享目录的原理或者原因就更好了。

2019-04-20 09:22 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +Jenkins master 的高可用是个老大难的问题。和很多人一样，笔者也想过两个 Jenkins master 共享同一个 JENKINS_HOME 的方案。了解 Jenkins 原理的人，都会觉得这个方案不可行。但是真的不可行吗？
这个，应该不是问题。下文会介绍 JENKINS_HOME 目录。而且，我见社区中不少文章也是直接这样使用的：https://wiki.jenkins.io/display/JENKINS/Securing+JENKINS_HOME

2019-04-20 09:37 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +最后结论：多个 Jenkins master 共享同一个 JENKINS_HOME 的方案是不可行的。
感觉这要对 Jenkins 整个底层都要非常熟悉才好写，我现在还不敢写。

2019-04-20 10:01 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +date: 2019-04-23
好的。

2019-04-20 11:20 UTC, LinuxSuRen requested changes

2019-04-20 11:20 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
[另外一篇文章](https://github.com/jenkins-infra/wechat/blob/master/articles/2019/03/2019-03-13-electron-pipeline-demo.md)的`审校`部分是在文末的，我们还是应该有统一的风格。可以把这个放到[sample.md](https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md)里来描述。

另外，关于人员的显示，我们是有个[参考](https://github.com/jenkins-infra/wechat/tree/master/management/contributors)的，应该遵守里面的约定。

我的显示使用 `LinuxSuRen `

2019-04-20 11:21 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
或者，我们可以把审校放到文件头部中，就跟作者类似的。这样，我们可以在社区站点上统一显示。

2019-04-20 11:51 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
因为我们现在提交的 PR 的内容会直接展示到社区站点上，所以，审校人的信息可以像你说的放在文件头部。但是，PR 的内容，还需要人工发布到公众号上。

我考虑到要发到公众号上，所以，才把用审校人的真实姓名，毕竟中文名对国人来说，可识别性会更好一些。比如，我的文章的署名当然会希望是翟志军，而不是 zacker330 。毕竟没有多少人知道 zacker330 这个 GitHub ID。

2019-04-20 11:57 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
[2019-03-13-electron-pipeline-demo](https://github.com/jenkins-infra/wechat/blob/master/articles/2019/03/2019-03-13-electron-pipeline-demo.md) 这篇文章的审校位置变更，已经提 PR

2019-04-20 12:20 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
> 我考虑到要发到公众号上，所以，才把用审校人的真实姓名，毕竟中文名对国人来说，可识别性会更好一些。

明白，但不是所有人都希望放真实的姓名，因此，才有 https://github.com/jenkins-infra/wechat/tree/master/management/contributors 这个目录中的记录。

2019-04-20 12:26 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
好的，那我改一下，改成 GitHub ID

2019-04-20 12:28 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
不是这个意思， https://github.com/jenkins-infra/wechat/blob/master/management/contributors/donhui.yml

https://github.com/jenkins-infra/wechat/blob/master/management/contributors/linuxsuren.yml

里面的文件记录了每位贡献者希望显示的名称，不是统一的，而是有各自觉得的。

2019-04-20 13:52 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
那我应该加哪个字段呢？是 nickname 字段，还是 name 字段？

2019-04-20 21:35 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
之前用的是 `nickname` 

我加个说明吧，目前 name 和 github 和一样的。

2019-04-20 21:46 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
说明 PR 已添加 #89

2019-04-20 23:09 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-master-shared-home.md
> +> 审校：[王冬辉](https://github.com/donhui)，[赵晓杰](https://github.com/LinuxSuRen)
fix

2019-04-21 02:00 UTC, LinuxSuRen approved these changes
LGTM

2019-04-22 11:40 UTC, merged

2019-04-23 01:22 UTC, donhui commented
开源中国已发：https://my.oschina.net/jenkinszh/blog/3040800

2019-04-24 10:56 UTC, zacker330 commented
简书：https://www.jianshu.com/p/3907e359ded0

2019-04-24 12:40 UTC, zacker330 commented
掘金：https://juejin.im/post/5cc058275188250aa2191c17