[原创-2019-04-23] 使用 Jenkins + Ansible 实现自动化部署 Nginx
jenkins-infra/wechat pull request #90
Opened 2019-04-21 15:18 UTC by zacker330

[类型-文章排期] 标题
### PR 类型*

- [x] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-04-22 01:49 UTC, LinuxSuRen requested changes
23号已经有了一篇原创排期了 #85

2019-04-22 07:45 UTC, zacker330 commented
> 23号已经有了一篇原创排期了 #85

将 #85 的改成 25 号了。25号没有文章排期。

2019-04-22 09:02 UTC, donhui commented
#90 和 #85 时间可不可以换一下？给 review 及修改预留点时间

2019-04-22 11:02 UTC, LinuxSuRen commented
建议给大家留下大概一周左右的 review 时间

2019-04-22 11:27 UTC, LinuxSuRen requested changes

2019-04-22 11:27 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-ansible-nginx.md
> +* Vagrant：虚拟机管理工具，通过它，我们可以使用文本来定义、管理虚拟机。
建议在提到的其他工具上，加对应官网或者其相关的链接，这样读者可以很方便地查看相关的内容，而不需要手动去搜索。

2019-04-22 11:27 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-ansible-nginx.md
> +- nginx
加上`toc` 字段可以方便自动生成目录

2019-04-22 11:27 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-ansible-nginx.md
> +     1. 本次实验，使用 Swarm 插件实现 Jenkins master  与 Jenkins agent 之间的通信，所以 Jenkins agent 需要启动 swarm 客户端。
> 实现 Jenkins master  与 Jenkins agent 之间的通

实现 Jenkins master  与 agent 之间的通

2019-04-22 11:28 UTC, zacker330 commented
> #90 和 #85 时间可不可以换一下？给 review 及修改预留点时间

可以的。那我换回来吧。

2019-04-22 11:33 UTC, zacker330 commented on articles/2019/04/2019-04-23-jenkins-ansible-nginx.md
> +     1. 本次实验，使用 Swarm 插件实现 Jenkins master  与 Jenkins agent 之间的通信，所以 Jenkins agent 需要启动 swarm 客户端。
不是很明白？

2019-04-22 11:34 UTC, LinuxSuRen commented on articles/2019/04/2019-04-23-jenkins-ansible-nginx.md
> +     1. 本次实验，使用 Swarm 插件实现 Jenkins master  与 Jenkins agent 之间的通信，所以 Jenkins agent 需要启动 swarm 客户端。
Jenkins 提一次就好了，提多次的话，念起来会感觉有点重复。

2019-04-22 11:35 UTC, LinuxSuRen commented
PR 一般是不需要关闭的，直接修改就好了。

2019-04-23 02:02 UTC, donhui commented on articles/2019/04/2019-04-25-jenkins-ansible-nginx.md
> +* [Docker Compose](https://docs.docker.com/compose/)：它是一个用于定义和运行多容器 Docker 应用程序的工具。可以使用YAML文件来配置应用程序的服务。
YAML 前后加空格

2019-04-23 09:59 UTC, donhui commented on articles/2019/04/2019-04-25-jenkins-ansible-nginx.md
> +* 简单易懂Ansible系列 —— 解决了什么：[https://showme.codes/2017-06-12/ansible-introduce/](https://showme.codes/2017-06-12/ansible-introduce/)
英文前后加空格

2019-04-24 12:21 UTC, zacker330 commented
看样子都解决了，封面图就使用第一张架构图就可以了。

2019-04-24 12:22 UTC, LinuxSuRen approved these changes

2019-04-24 12:23 UTC, merged

2019-04-25 08:39 UTC, donhui commented
开源中国：https://my.oschina.net/jenkinszh/blog/3042391
此外，发现图片目录时间命名和文章不一致，建议修改下
@zacker330

2019-04-25 08:43 UTC, LinuxSuRen commented
另外，我们的图片文件名最好是有意义的，而不是时间戳或者随机串。

2019-04-25 14:35 UTC, zacker330 commented
@donhui 好的，我改一下。

2019-04-25 14:39 UTC, zacker330 commented
@LinuxSuRen 好的。我再改一下。

2019-04-25 22:37 UTC, zacker330 commented
掘金：https://juejin.im/post/5cc2356cf265da037b61169d

简书：https://www.jianshu.com/p/607e2fc35f60