[翻译-2019-04-26]What CI/CD Tool Should I Use?
jenkins-infra/wechat pull request #91
Opened 2019-04-21 16:30 UTC by yJunS

### PR 类型*

- [ ] 原创，我申明当前 PR 中的文章是由我本人创作
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 维护

### 发布

如果在相应的社交媒体平台上发布完成，请在勾选：

- [ ] [微信公众号](https://github.com/linuxsuren)
- [ ] [开源中国](https://github.com/donhui)
- [ ] [CSDN](https://github.com/P01son6415)
- [ ] [简书](https://github.com/yJunS)
- [ ] [掘金](https://github.com/zacker330)

2019-04-22 08:59 UTC, donhui commented on management/contributors/yjuns.yml
> +nickname: 史彦军
最后加个空行，以便于 review

2019-04-22 09:30 UTC, donhui commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +- CI/CD
建议分成两个 tag：ci、cd ，并使用小写

2019-04-22 09:32 UTC, donhui commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +在我们正在进行的Kubernetes FAQ系列中，我们回答了社区中一些常见的问题，本周我们将讨论在选择 CI/CD 工具时需要考虑什么。
英文前后空格

2019-04-23 01:29 UTC, donhui commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +- 将您的上线时间从数周或数月减少到数天或数小时。通过自动化管道流水线，开发团队可以提高版本的速度以及代码的质量。以小增量连续添加的新功能和修复可以使产品具有更少的缺陷。
自动化管道流水线  --> 自动化流水线
提高版本的速度 --> 提高发布的速度  （release 在 CD 场景一般译为发布）

2019-04-23 01:32 UTC, donhui commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +3. 将图像推送到图像存储库。
这几行 image 应该翻译为镜像

2019-04-23 01:37 UTC, donhui commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +1. 在笔记本电脑上编写代码，将其推入源代码存储库(如 Git)。
存储库 --> 仓库

2019-04-23 01:45 UTC, donhui commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +#### ＃3。使用遵循操作符模式的 Kubernetes 控制器
这里的 Operator 建议不翻译

2019-04-23 01:47 UTC, donhui commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +Weave Cloud 的部署代理在集群内部运行。这意味着容器映像注册表和集群 API 的凭据永远不会离开集群的域。通过使用 Git 作为事实源，可以比较和警告所需的状态和当前状态。这不仅可以确保群集保持最新，而且还可以在群集融化时提供从灾难中快速恢复的方法。
群集 --> 集群

2019-04-23 02:05 UTC, LinuxSuRen commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +1. 在笔记本电脑上编写代码，将其推入源代码存储库(如 Git)。
https://github.com/jenkins-zh/translation-spec/pull/2/files

2019-04-23 11:29 UTC, yJunS commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +- 将您的上线时间从数周或数月减少到数天或数小时。通过自动化管道流水线，开发团队可以提高版本的速度以及代码的质量。以小增量连续添加的新功能和修复可以使产品具有更少的缺陷。
好的  👌

2019-04-23 11:49 UTC, yJunS commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +1. 在笔记本电脑上编写代码，将其推入源代码存储库(如 Git)。
ok

2019-04-24 05:40 UTC, zacker330 commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +#### ＃1。所有可以描述的内容都必须存储在 Git 中
应该是英文的 . 吧？

2019-04-24 05:40 UTC, zacker330 commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +#### ＃3。使用遵循操作符模式的 Kubernetes 控制器
应该是英文的 . 吧？

2019-04-24 05:40 UTC, zacker330 commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +#### ＃2。不要直接使用 kubectl
应该是英文的 . 吧？

2019-04-24 07:48 UTC, yJunS commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +#### ＃1。所有可以描述的内容都必须存储在 Git 中
嗯嗯。对

2019-04-25 01:21 UTC, donhui commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +- 将您的上线时间从数周或数月减少到数天或数小时。通过自动化流水线流水线，开发团队可以提高发布的速度以及代码的质量。以小增量连续添加的新功能和修复可以使产品具有更少的缺陷。
通过自动化流水线流水线
这里多了一个 流水线

2019-04-25 01:25 UTC, LinuxSuRen requested changes
我们需要一个封面图片，请参考 #101

2019-04-25 01:25 UTC, LinuxSuRen commented on management/contributors/yjuns.yml
> +nickname: 史彦军
最后只留一个空行就好

2019-04-25 01:25 UTC, LinuxSuRen commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +![](../../../images/articles/2019/04/2019-04-30-what-cicd-tool-should-i-use/5bae45390d80351e6dbdf031.png]
这个图片没有显示出来

2019-04-25 03:26 UTC, yJunS commented on articles/2019/04/2019-04-30-what-cicd-tool-should-i-use.md
> +- 将您的上线时间从数周或数月减少到数天或数小时。通过自动化流水线流水线，开发团队可以提高发布的速度以及代码的质量。以小增量连续添加的新功能和修复可以使产品具有更少的缺陷。
好的

2019-04-25 03:30 UTC, yJunS commented on management/contributors/yjuns.yml
> +nickname: 史彦军
好。现在应该对了

2019-04-25 03:47 UTC, LinuxSuRen approved these changes

2019-04-25 06:11 UTC, donhui commented
LGTM

2019-04-29 13:14 UTC, merged

2019-04-30 12:03 UTC, donhui commented
开源中国：
https://my.oschina.net/jenkinszh/blog/3044574

2019-05-05 16:12 UTC, yJunS commented
CSDN:
https://blog.csdn.net/u014249394/article/details/89859514

2019-05-05 23:31 UTC, zacker330 commented
* 简书：https://www.jianshu.com/p/b29357063aec
* 掘金：https://juejin.im/post/5ccf71ed51882540a019be91

2019-05-06 14:20 UTC, yJunS commented
CSDN：https://blog.csdn.net/u014249394/article/details/89859514

2019-05-06 14:22 UTC, yJunS commented
简书：https://www.jianshu.com/p/58e8f6cc0dc3